### ISSUE TITLE
Params with separator breaking docs

### ISSUE THREAD

**Issue by tobinbradley** [fastify/fastify-swagger#100]
I'm trying to do a route like the one specified in the Fastify docs with two params between a single set of slashes using the dash separator:

```javascript
fastify.get('/example/near/:lat-:lng/radius/:r', (request, reply) => {}))
```

My specific route is pretty close to this: '/transform_point/:lat-:lng/:srid'. This end point works fine. The Swagger docs, however, seem to break on the separator. The path ends up looking like this:

![path](https://i.imgur.com/f6ag1MC.png)

The schema populates the test form correctly with the route inputs, but after hitting execute it doesn't populate the lng and lat route parameters, seemingly treating that portion of the route as a static string.

![curl](https://i.imgur.com/Mcjy0RR.png)

My schema parameters look like this:

```javascript
params: {
    lat: {
      type: 'number',
      description: 'x coordinate'
    },
    lng: {
      type: 'number',
      description: 'y coordinate'
    },
    srid: {
      type: 'integer',
      description: 'SRID of the coordinate'
    }
  },
```

Am I doing something wrong, or are two params between a set of slashes unsupported? Am I better off making it a single parameter and regex-ing a [number][separator][number] validation?

Many thanks!

**Comment by mcollina** [comment]
This looks like a bug, either here, in fastify, or in find-my-way. Would you like to try a fix?

**Comment by tobinbradley** [comment]
I can poke around a bit. 

It smells like a Swagger thing to me. I noticed that although the route Swagger's doc (curl route etc) says it doesn't pass anything for /:var1-:var2/ - 

`http://localhost:3000/v1/transform_point/{lat-:lng}/4326?srid_return=4326`

It actually *does* pass some values in the HTTP request the docs page makes:

`http://localhost:3000/v1/transform_point/%7Blat-:lng%7D/4326?srid_return=4326`

Which I can confirm at the endponit:

`request.params = { lat: '{lat', lng: ':lng}', coords: '3,4', srid: 4326 }`

It looks like the problem originates when it creates documentation/json, as I can see the /:var-:var/ params are incorrectly translated there:

```
"/v1/transform_point/{x-:y}/{coords}/{srid}": {
      "get": {
        "summary": "transform point to new SRID",
```

That's what I have so far if any of it rings a bell. I'll keep poking.

**Comment by tobinbradley** [comment]
It's definitely happening when the Fastify route schemas are translated to Swagger. I copied the `/documentation/yaml` endpoint into a file, manually modified the yaml route from the incorrectly translated `/v1/transform_point/{lat,:lng}/{coords}/{srid}` to `/v1/transform_point/{lat}-{lng}/{srid}`, started the server with fastify-swagger in static mode, and Bob's your uncle.

I'm pretty sure the problem is where the Swagger YAML is getting dynamically created. I'll poke more.
