### ISSUE TITLE
Add support for different response content types

### ISSUE THREAD

**Issue by gyszalai** [fastify/fastify-swagger#117]
Swagger supports different content types in the response like this:

```
/health:
  get:
    responses:
      '200':
        description: Successful response
        content:
          text/plain:
            schema:
              type: string
              enum: ['UP','DOWN']
```
Currently it is not possible to define a response like this with fastify-swagger.

**Comment by mcollina** [comment]
Currently we don’t. I think we should enable this, but I’m not exactly
seeing how. Would you mind to do a proposal? A PR would even be better.

We might even be lacking support for this in fastify itself.

Il giorno mer 17 ott 2018 alle 10:22 Gyula Szalai <notifications@github.com>
ha scritto:

**Comment by climba03003** [comment]
OpenAPIv2 (aka Swagger) do not support this format. but OpenAPIv3 does.
As we added the support for OpenAPIv3. You can follow the document do achieve it.
Resolved by #333

**Comment by olafkrueger** [comment]
@climba03003 
First, many thanks for working on the OAS3 stuff!!
Maybe I overlook it, but is there any example of how we could add different `content/media types` to a particular response?
I've no idea how we could format a valid json response schema without adding a `content` object which holds the different `media types`.

Something like this (I just translated the OAS3 YAML example to JSON):
```
{
  "responses": {
    "200": {
      "description": "OK",
      "content": {
        "application/json": {
          "schema": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "fullTime": {
                "type": "boolean"
              }
            }
          }
        },
        "application/xml": {
          "schema": {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer"
              },
              "name": {
                "type": "string"
              },
              "fullTime": {
                "type": "boolean"
              }
            }
          }
        }
      }
    }
  }
}
```

Not totally sure, but after looking at the `fastify-swagger` code it seems to me that the `openapi` implementation still relies on `consumes` which has been removed since OAS3?:

https://github.com/fastify/fastify-swagger/blob/36bf4098be7a0e9c4b8ee74693e689623c4feadb/lib/spec/openapi/utils.js#L148


For the sake of completeness, just an example of the origin [OAS3 docs](https://swagger.io/docs/specification/media-types) which is about different `media types`:
```
paths:
  /employees:
    get:
      summary: Returns a list of employees.
      responses:
        '200':      # Response
          description: OK
          content:  # Response body
            application/json:   # One of media types
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  fullTime: 
                    type: boolean
            application/xml:    # Another media types
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  fullTime: 
                    type: boolean
```

Thanks!
Olaf

**Comment by climba03003** [comment]
you should use consumes and produces as it is what fastify use for.

**Comment by olafkruger** [comment]
>fastify cannot specify different response schema according to the media types with the same status code

Thank you for this clear answer and sorry for beeing not so clear... I hope I didn't waste too much of your time ;-)
However, I really wonder how it could make sense to resolve this by using `static` mode if  `fastify` itself is not able to handle it?

If it makes sense, one last question:
Is it possible to use the `static` mode for just a particular route and keep the `dynamic` mode for all other routes?

Beside all that it looks like that it's easier and more pragmatic and to split the different media types across different routes, something like this:
```
GET /my/resource/:id/pdf
GET /my/resource/:id/json
```

**Comment by olafkrueger** [comment]
>fastify cannot specify different response schema according to the media types with the same status code

Thank you for this clear answer and sorry for beeing not so clear... I hope I didn't waste too much of your time ;-)
However, I really wonder how it could make sense to resolve this by using `static` mode if  `fastify` itself is not able to handle it?

If it makes sense, one last question:
Is it possible to use the `static` mode for just a particular route and keep the `dynamic` mode for all other routes?

Beside all that it looks like that it's easier and more pragmatic to split the different media types across different routes, something like this:
```
GET /my/resource/:id/pdf
GET /my/resource/:id/json
```

**Comment by olafkrueger** [comment]
> However, I really wonder how it could make sense to resolve this by using static mode if fastify itself is not able to handle it?

Forget about this question, it makes sense ;-)

**Comment by climba03003** [comment]
> However, I really wonder how it could make sense to resolve this by using static mode if fastify itself is not able to handle it?

You can achieve it by not passing `schema.response` to disable the serialization of response.
Then you can reply with `reply.type(...).send(...)` according to your request.
In that case, you can use `static` mode to write document and show what different response will be given.

> Is it possible to use the static mode for just a particular route and keep the dynamic mode for all other routes?

No, we current do not allow to pass `path` from `dynamic` mode. Maybe a PR or Issue should raised if you need this.
I do not know if `exterenalDocs` works in this case because I never use this field.

If you have any more question. Please open a new Issue.

**Comment by olafkrueger** [comment]
Got it, thank you for your detailed explanation!

**Comment by giovanni-bertoncelli** [comment]
So right now there is no way to change a response type in the swagger documentation generated?

**Comment by climba03003** [comment]
> 
> 
> So right now there is no way to change a response type in the swagger documentation generated?

You can specify the response type, but you cannot have different type with different response schema.
e.g. `text/html` return `string` and `application/octet-stream` return `buffer`.

**Comment by matthiasg** [comment]
Where can the response type be configured so it appears in swagger ?

**Comment by climba03003** [comment]
> Where can the response type be configured so it appears in swagger ?

`produces` for response.
