### ISSUE TITLE
DefinitelyTyped ?

### ISSUE THREAD

**Issue by mhf-ir** [fastify/fastify-swagger#118]
How can i use this package using typescript ?

**Comment by cemremengu** [comment]
By sending a PR 😄 Would you like to create the typings file? 🙏

**Comment by evanshortiss** [comment]
@mhf-ir check out [fastify-url-data](https://github.com/fastify/fastify-url-data/blob/master/fastify-url-data.d.ts) for a template of how to add types for a plugin, although this plugin might need some changes. 

Off the top of my head maybe this would work?

```ts
import { RegisterOptions } from 'fastify';

declare function fastifySwagger (): void

declare namespace fastifySwagger {
  export interface FastifySwaggerOptions extends RegisterOptions {
    // Define options for the plugin
  }
}

export = fastifySwagger;
```

in use:

```ts
import * as fastify from 'fastify'
import * as swagger from 'fastify-swagger'

const server = fastify()

server.register(swagger(), { /* place valid options here */ } as swagger.FastifySwaggerOptions)
```
