### ISSUE TITLE
Documentation - Usage - SecurityDefinitions has a typo

### ISSUE THREAD

**Issue by JonPugsley** [fastify/fastify-swagger#122]
The schema name in securityDefinitions (apiKey in the ReadMe) needs to exactly match the one used in the route security (api_key in the ReadMe).  If you use the example exactly as written the Authorize button will appear in Swagger UI but no authorization header will be included in the curl for the route

See:
https://github.com/swagger-api/swagger-ui/issues/1244#issuecomment-245638234

**Comment by mcollina** [comment]
Thanks! Would you like to send a PR?

Il giorno mer 14 nov 2018 alle 19:43 Jonathan Pugsley <
notifications@github.com> ha scritto:

**Comment by JonPugsley** [comment]
Simple enough change - that should do it.
