### ISSUE TITLE
Declare an empty response for 204

### ISSUE THREAD

**Issue by tnguyen14** [fastify/fastify-swagger#13]
For 204 response (empty response), Swagger allows for its description by not specifying a `content` https://swagger.io/docs/specification/describing-responses/.

However, for `fastify-swagger`, I haven't found a way to do that yet. If I do:

```js
{
  schema: {
    response: {
      204: {
        description: 'Successfully deleted item'
      }
    }
  }
}
```

I get the following stacktrace:

```
Uncaught Exception Error: undefined unsupported
    at build (/Users/tri/project/node_modules/fast-json-stringify/index.js:80:13)
    at getValidatorForStatusCodeSchema (/Users/tri/project/node_modules/fastify/lib/validation.js:12:10)
    at /Users/tri/project/node_modules/fastify/lib/validation.js:18:21
    at Array.reduce (<anonymous>)
    at getResponseSchema (/Users/tri/project/node_modules/fastify/lib/validation.js:17:22)
    at build (/Users/tri/project/node_modules/fastify/lib/validation.js:44:28)
```

**Comment by mcollina** [comment]
This is likely a bug in fastify itself rather than this module. Would you like to submit it there?

**Comment by tnguyen14** [comment]
Sure thing. I opened https://github.com/fastify/fastify/issues/609

**Comment by cortopy** [comment]
@mcollina @tnguyen14 I'm also interested in getting this working for 302 responses. What does remain to be done? I can see this has been open for a while. Happy to complete or submit a new PR

**Comment by mcollina** [comment]
I'm not sure, check https://github.com/fastify/fastify-swagger/pull/19.

If you want to make this moving again, feel free to send a new PR.
