### ISSUE TITLE
External $ref does not work

### ISSUE THREAD

**Issue by kromol** [fastify/fastify-swagger#134]
**Description**
It doesn't work if `$ref` is pointing to the definition in another file. External references are [supported by swagger](https://swagger.io/docs/specification/using-ref/)

This code  does not work:
`$ref: './resources.yaml#/resources/User'`

**Expected result**
It should load definition from external files

**Actual result**
It fails when it tries to load the file (`GET /documentation/path-to-file`). Server responds with 404 since it's not aware about any other files except of main swagger file that is passed to the plugin.

**Comment by mcollina** [comment]
This is not supported in fastify and fastify-swagger. You'll need to load them manually.

I'd be happy to review a PR that added that support in here - there might be some work needed in Fastify to make that happen as well.

**Comment by kromol** [comment]
@mcollina I think this one can be closed since [#137 PR](https://github.com/fastify/fastify-swagger/pull/137) has been merged and this feature is available in the latest version unless you have any objections
