### ISSUE TITLE
Deprecated route

### ISSUE THREAD

**Issue by chapuletta** [fastify/fastify-swagger#14]
Hi!, i have a deprecated route in schema and defined like deprecated: true but not showing in the ui the route with the style like line-through.

This is an issue or im not defining the schema correctly?

Thx!

**Comment by scriptjs** [comment]
I can confirm the same issue by adding `deprecated: 'true'` to the schema. I would consider this a bug since `deprecated` is part of the standard that should be present and defaulted to `false`.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by delvedor** [comment]
Hi! Thank you for contributing.
Would you like to send a pr? :)

**Comment by scriptjs** [comment]
@delvedor Yeah, I forked before getting your message to fix this. There are also other bugs I am interested in fixing.

**Comment by delvedor** [comment]
@scriptjs go ahead! :)

**Comment by chapuletta** [comment]
When we have a new version of this in the npm?

**Comment by mcollina** [comment]
This is in v0.3.0, published right now.
