### ISSUE TITLE
Add a transform method for schema

### ISSUE THREAD

**Issue by Roms1383** [fastify/fastify-swagger#143]
Hello I would like to suggest an extra option to add a transform method in the plugin options for dynamic mode.
Use case : using Joi validation library we need to convert Joi schema back into a JSON schema only for Swagger documentation generation. With a transform method it would be easy to convert it with a third-party library.

**Comment by mcollina** [comment]
Seems a good idea, would you like to send a PR?

**Comment by Roms1383** [comment]
As a basic sample : https://github.com/Roms1383/fastify-swagger/commit/332f9c1922cf4f374c6a7006eb8288aea565460c

So that then for example I can change schema.params and schema.body to return compliant JSON schema instead of Joi :
```js
const convert = require('joi-to-json-schema')
const options = {
// ...
transform: schema => {
    const { params = undefined, body = undefined, ...others } = schema
    const transformed = { ...others }
    if (params) transformed.parms = convert(params)
    if (body) transformed.body = convert(body)
    return transformed
  }
}
fastify.register(require('fastify-swagger'), options)
```

**Comment by Roms1383** [comment]
Here's a bit late but I can do a proper PR tomorrow @mcollina :)

**Comment by Roms1383** [comment]
Got a working sample [here](https://github.com/Roms1383/robust-database).
Thanks very much I can't wait for the release 😊

**Comment by Roms1383** [comment]
@mcollina : as a reminder, maybe README.md should be updated here :
```js
transform: schema => {
    const {
      params = undefined,
      body = undefined,
      querystring = undefined,
      response = undefined,
      ...others
    } = schema
    const transformed = { ...others }
    if (params) transformed.params = convert(params)
    if (body) transformed.body = convert(body)
    if (querystring) transformed.querystring = convert(querystring)
    if (response) transformed.response = convert(response)
    return transformed
  }
```
To
```js
transform: schema => {
    const {
      params = undefined,
      body = undefined,
      querystring = undefined,
      ...others
    } = schema
    const transformed = { ...others }
    if (params) transformed.params = convert(params)
    if (body) transformed.body = convert(body)
    if (querystring) transformed.querystring = convert(querystring)
    return transformed
  }
```
As `response` is not meant to be used with [Joi](https://github.com/hapijs/joi) for example.
