### ISSUE TITLE
Authorize UI does appear to work when configured

### ISSUE THREAD

**Issue by scriptjs** [fastify/fastify-swagger#15]
I don't seem to be able to configure authorization properly to gain the authorize UI button in the docs as in the petstore reference implementation you see in the image below:

![screen shot 2018-01-04 at 10 51 25 pm](https://user-images.githubusercontent.com/13335501/34594278-6f7dfdd4-f1a6-11e7-8e2c-c0f2c8c5081f.png)

I have attempted by setting headers ie.
```
  headers: {
    type: 'object',
    properties: {
      'x-api-token': {
        type: 'string',
        description: 'optional api token'
      },
      'x-api-version': {
        type: 'string',
        description: 'optional api version'
      }
    }
  },
```
and 
```
  headers: {
    type: 'object',
    properties: {
      authorization: {
        type: 'string',
        description: 'api token'
      }
    },
    required: ['authorization']
  },
```
from what I was able to read from the tests.

I have also tried adding securityDefinitions within the swagger object. These are normally attached to a security object for scope ie.

```
"security": [{
  "api_key": []
}]
```

**Comment by mcollina** [comment]
Can you please upload a full example? What is this pet store implementation you are referring to?

The functionality you are loooking to might not be implemented at all in this module.

**Comment by scriptjs** [comment]
PetStore is the reference example of the swagger 2 implementation until open api has version 3 out. You can view the example at http://petstore.swagger.io/

The swagger.json is located here:  http://petstore.swagger.io/v2/swagger.json

It is not useful to have API documentation unless developers can test endpoints with a token. It appears you are doing testing for authentication headers but doing no tests to ensure this translates to the UI.

**Comment by scriptjs** [comment]
@mcollina Fixed this. Will send a pull request shortly.

**Comment by scriptjs** [comment]
Pull request #18 resolves this.

**Comment by scriptjs** [comment]
This is now in version 0.3.0

**Comment by Ch-Valentine** [comment]
**You should add to swagger config next code:**

```javascript
module.exports = {
  routePrefix: '/documentation',
  // properties...
  swagger: {
   securityDefinitions: {
      Authorization: {
        type: 'apiKey',
        name: 'Authorization',
        in: 'header'
      }
    }
  }
}
```
