### ISSUE TITLE
Fastify-Swagger introduction to a TYPESCRIPT proj doen't allow swagger details

### ISSUE THREAD

**Issue by panbhatt** [fastify/fastify-swagger#156]
While importing fastify-swagger into a fastify (ts) based project, when we are defining the schema of any method, we are restricted because of the RouteSchema defined in the fastify.d.ts. 
For Swagger we need to expand this to include other properties like documenation,tags,summary,security. 
Creating a pull reques to acheive this.

**Comment by karlos1337** [comment]
Fixed here https://github.com/fastify/fastify-swagger/pull/155 , pending merge
