### ISSUE TITLE
Rename repository to fastify-openapi

### ISSUE THREAD

**Issue by scriptjs** [fastify/fastify-swagger#16]
Swagger 2 was made OpenAPI 2 quite some time ago. Swagger is the brand name of SmartBear Software. In the spirit of the move to the open standard, the previous Swagger 2 specification became the OpenAPI 2 specification. Version 3 of the OpenAPI specification is still undergoing review.

I am recommending the repository name be changed to fastify-openapi to reflect the direction of the standard and to stop using SmartBear's proprietary branding.
  
This will require a few small changes since the higher level object is referred to as `swagger` at the moment.

**Comment by mcollina** [comment]
I'm 👍  do you want to do the PR, and we'll publish a new module?

**Comment by scriptjs** [comment]
So the three pull requests are in that I wanted to do before I do this. There are 2 left to merge. I think we should cut a release with these changes first before renaming the repo.

**Comment by scriptjs** [comment]
A fastify-openapi package exists in npm. Closing this.
