### ISSUE TITLE
How to add Dynamic Querystring Parameters ?

### ISSUE THREAD

**Issue by red1** [fastify/fastify-swagger#163]
Hello 
I'm trying to achieve the same goal than this : https://stackoverflow.com/questions/49582559/how-to-document-dynamic-query-parameter-names-in-openapi-swagger
basically trying to mix on the doc some known querystrings params with not known that can be used by the api behind dynamically : 
```
GET api/v1/users?knownParam1=value1&knownParam2=value2...&dynamicParam1=...&foo=bar
```

I tryied the object type with the additionalProperties flag : 
```
  querystring: {
    knownParam1: { type: 'string', description: 'String - bla bla ' },
    knownParam2:{ type: 'string', description: 'String - bla bla ' },
    params : {
      'type': 'object',
      'properties': {
        unknownParam1: { type: 'string' },
        unknownParam2: { type: 'string' }
      },
      'additionalProperties': true,
    },
```
But the end result still have a "params" parameter rather than listing the examples

I try really to mix known api query params and unknowparams, the free form object seems to fit my need for the unknowns but I don't know how to make that key dynamic to let the user generate the additional ones exactly as in the SOF thread
![image](https://user-images.githubusercontent.com/117082/54449003-62f83b80-474d-11e9-9007-9b71ab5f9382.png)

If Someone has any idea,
thanks

**Comment by Eomm** [comment]
Hi,
unfortunately, you can't archive your needs because the dynamic registration mode support swagger 2.0 and the SO link explain that you need Open API 3.0 (that is the successor of swagger 2.0).

You can archive what you need using the `static` registration mode.
This example works fine:

```
openapi: 3.0.0
info:
  description: "Test swagger specification"
  version: "1.0.0"
  title: "Test swagger specification"
  contact:
    email: "super.developer@gmail.com"
servers:
  - url: http://localhost:3000/
    description: Localhost (uses test data)
paths:
  /status:
    get:
      parameters:
        - in: query
          name: params
          schema:
            type: object
            additionalProperties:
              type: string
          style: form
          explode: true
```

Another way is to try the [`fastity-oas`](https://gitlab.com/m03geek/fastify-oas) plugin that could work (I didn't try it)
