### ISSUE TITLE
Multiple docs in project

### ISSUE THREAD

**Issue by eriott** [fastify/fastify-swagger#167]
Hi,
I need to make different docs for different routes in my application. I have 2 "root" routes, for example:

```
fastify.register(require('./routes/one'), {
  prefix: '/one'
})

fastify.register(require('./routes/two'), {
  prefix: '/two'
})
```
And want two documentations for subroutes of `/one` and `/two`. 
Is there any way to make it now? Or maybe add something like `subroutesOf: '/one'` parameter to plugin options to filter routes needed for each documentation?
Thanks for your time.

**Comment by mcollina** [comment]
I think you should register the swagger plugin within each module. It should work.

**Comment by eriott** [comment]
I tried it, but all routes get into both of documentations. My code:

```
fastify.register(
  (fastify, options, next) => {
    fastify.register(require('fastify-swagger'), {
      swagger: {
        info: {
          title: 'Test route one'
        },
        host: 'localhost:4001',
        schemes: ['http', 'https'],
        consumes: ['application/json'],
        produces: ['application/json']
      },
      exposeRoute: true,
      routePrefix: '/oneDocs'
    })

    fastify.get('/oneRoute', (req, reply) => reply.send({ hello: 'oneRoute' }))
    next()
  },
  { prefix: '/one' }
)

fastify.register(
  (fastify, options, next) => {
    fastify.register(require('fastify-swagger'), {
      swagger: {
        info: {
          title: 'Test route two'
        },
        host: 'localhost:4001',
        schemes: ['http', 'https'],
        consumes: ['application/json'],
        produces: ['application/json']
      },
      exposeRoute: true,
      routePrefix: '/twoDocs'
    })

    fastify.get('/twoRoute', (req, reply) => reply.send({ hello: 'twoRoute' }))
    next()
  },
  { prefix: '/two' }
)
```

And generated docs for route `/one`:

![Выделение_038](https://user-images.githubusercontent.com/8165805/54977812-40bdb380-4fc0-11e9-81a2-a4e51d1ecc6e.png)

**Comment by Eomm** [comment]
Yes, this isn't working because this plugin uses [`onRoute`](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#application-hooks) hook that is not encapsulated.

I think that this could be fixed here:

https://github.com/fastify/fastify-swagger/blob/9f90000ceb280c12bd17f364fa433a6f6ddd1706/dynamic.js#L13

with a sort of:

```js
    if( fastify.prefix === routeOptions.prefix){
      routes.push(routeOptions)
    }
```

I'm 80% sure this could work with some adjusment.. would you like to try and send a PR?

**Comment by eriott** [comment]
Yes, I'll try, thank you)

**Comment by jonnydgreen** [comment]
Looks like this is now working with the following versions and the original example:
 - `"fastify": "3.27.4",`
 - `"fastify-swagger": "5.1.0",`

Original example:

```js
"use strict";

const Fastify = require("fastify");

const fastify = Fastify();

fastify.register(
  (fastify, _options, next) => {
    fastify.register(require("fastify-swagger"), {
      swagger: {
        info: {
          title: "Test route one",
        },
        host: "localhost:4001",
        schemes: ["http", "https"],
        consumes: ["application/json"],
        produces: ["application/json"],
      },
      exposeRoute: true,
      routePrefix: "/oneDocs",
    });

    fastify.get("/oneRoute", (_request, reply) => reply.send({ hello: "oneRoute" }));
    next();
  },
  { prefix: "/one" }
);

fastify.register(
  (fastify, _options, next) => {
    fastify.register(require("fastify-swagger"), {
      swagger: {
        info: {
          title: "Test route two",
        },
        host: "localhost:4001",
        schemes: ["http", "https"],
        consumes: ["application/json"],
        produces: ["application/json"],
      },
      exposeRoute: true,
      routePrefix: "/twoDocs",
    });

    fastify.get("/twoRoute", (_request, reply) => reply.send({ hello: "twoRoute" }));
    next();
  },
  { prefix: "/two" }
);

fastify.listen(4001);
```

One:

<img width="1529" alt="Screenshot 2022-04-06 at 09 53 31" src="https://user-images.githubusercontent.com/31290910/161936583-4cf13a25-4295-460c-9558-27a247e745b9.png">

Two:

<img width="1536" alt="Screenshot 2022-04-06 at 09 53 22" src="https://user-images.githubusercontent.com/31290910/161936637-18068c70-e45e-4776-a925-667bcb60cca8.png">

**Comment by ram-you** [comment]
Hi @climba03003 
Sorry to comment on a closed issue. 
This solution works but doesn't include subroutes endpoints.

**Comment by climba03003** [comment]
> Hi @climba03003 
> Sorry to comment on a closed issue. 
> This solution works but doesn't include subroutes endpoints.

`await` the plugin for fastify@4

**Comment by ram-you** [comment]
I've done this before (await ), but still not having routes sub folders endpoints, only routes declared inside function ( oneRoute and twoRoute )
