### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by RSWilli** [fastify/fastify-swagger#168]
Fastify currently has experimental HTTP/2 support.

Is it possible to use fastify-swagger with http/2? But since I'm using Typescript, my project won't compile because the fastify-swagger types require a HTTP Server, instead of HTTP2

**Comment by mcollina** [comment]
This can definitely be used with HTTP/2. The types would need to be updated.

**Comment by RSWilli** [comment]
I created a Pull request with the updated types

See https://github.com/fastify/fastify-swagger/pull/169

**Comment by jagreehal** [comment]
@mcollina now that #169 can this be closed?

**Comment by mcollina** [comment]
yes thanks!
