### ISSUE TITLE
Best practises for handling input/output schemas?

### ISSUE THREAD

**Issue by PatrickHeneise** [fastify/fastify-swagger#174]
I have a "regular" API scenario and I'm wondering if there are any best practises for the handling of schemas.

A new entity might require a name:

```json
{
  "$id": "foo",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": { "type": "string" }
  }
}
```

when storing this entity, an `id` and `createdAt` is generated, so the output schema for GET /:id and GET / differs from the input schema:

```json
{
  "$id": "foo",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "name": { "type": "string" },
    "createdAt": { "type": "date" },
  }
}
```

both schemas are for the same entity and have shared attributes. I'm wondering if there is anything else but defining two different schemas `fooIn` and `fooOut` for example? This is kind of annoying when adding/removing/changing an attribute.

If that's the only solution, how do you name/store these schemas?

Thanks!

**Comment by Eomm** [comment]
> I'm wondering if there is anything else but defining two different schemas fooIn and fooOut for example?

Unfortunately, these are two different schemas so you would need to build 2 schema object.
So I would suggest writing a `schemaFactory()` that does your business logic for you.

Consider that there are also [json schema conditions](https://json-schema.org/understanding-json-schema/reference/conditionals.html) if you can imagine a utilization.

I wrote a [plugin](https://github.com/Eomm/fastify-schema-constraint/) to choose a different schema to apply on the request, so it should be possible to do the same in the response.

> If that's the only solution, how do you name/store these schemas?

Personally, I store all the schemas in separated `.json` files and I don't apply any additional processing so this more easy to validate the schema, changing it and so on.

**Comment by Eomm** [comment]
> Can you recommend a folder structure for storing separate files?

I use this one:

```
├─┬ my-route-plugin
│ ├─┬ schemas
│ │ ├── out-get.json
│ │ ├── in-post.json
│ │ ├── out-post.json
│ ├── index.js
```

Then I publish the plugin and in the main application, I need only to update the dependency.
A loooot of mini projects but are easy to manage

If I  need to repliacate something, I create a module 😅
