### ISSUE TITLE
Is outputting to a file supported?

### ISSUE THREAD

**Issue by bburke4** [fastify/fastify-swagger#181]
Does this plugin support saving the swagger API schema to a local file in addition to making the documentation available through the UI?

I am thinking about the case where we may want to use a swagger file with other tools, such as generating PDF documentation.

Currently, I will just browse to /documentation/json to download the swagger file.

If it is not currently supported, does that sound feasible?

**Comment by Eomm** [comment]
Yes, you can define a route that print out the yaml using this parameter:

https://github.com/fastify/fastify-swagger/blob/master/README.md#swagger-options

**Comment by bburke4** [comment]
I see that we have access to the api schema inside fastify and that we can generate routes to expose it, I think what I have in mind is a little different...

The use-case I am thinking of is for keeping an api schema file up-to-date in source-control. That way, anyone depending on your API can download the schema file from e.g. github and know that it represents the current status of the API.

How it could work is: in development, whenever you start the fastify server, it will write the api schema to a local json/yaml file. That way you can easily commit any changes to the schema as the API changes.

Maybe this is out of the scope of this project. Let me know, thanks!

**Comment by Eomm** [comment]
Yes, you want to extract a file to use it offline, when the fastify server could be totally off.
So I think it is a specific use case that you can implement by yourself using the exposed apis and storing the result in a file.

**Comment by bburke4** [comment]
Sounds good, thanks!

**Comment by mikicho** [comment]
@bburke4 I need the same. what solution did you find?

**Comment by bburke4** [comment]
@mikicho i just added this to a plugin file...

```javascript
  // only 1 worker should export api spec to a file in development mode only.
  if (process.env.NODE_ENV === 'development' && cluster.isWorker && cluster.worker.id === 1) {
    const specFile = './docs/data-api.json';

    fastify.ready(() => {
      const apiSpec = JSON.stringify(fastify.swagger(), null, 2);

      writeFile(specFile, apiSpec, (err) => {
        if (err) {
          return fastify.log.error(`failed to save api spec to ${specFile}`);
        }
        fastify.log.debug(`saved api spec to ${specFile}`);
      });
    });
  }
```

I also added a shell script to do it...

```bash
#!/bin/sh
# generate_docs.sh -- dumb/hacky way of generating html documentation for the APIs.
# requires redoc-cli to be installed

# start dev server in the background and wait for it to start
yarn dev &
sleep 5

# download api spec from swagger-ui
curl localhost:3000/docs/json > docs/data-api.json

# kill dev server
pkill -f 'yarn.js dev'

# generate static html documentation
redoc-cli bundle docs/yo-data-api.json --output docs/yo-data-api.html

```

**Comment by domengabrovsek** [comment]
> @mikicho i just added this to a plugin to write the file on server start (requires fastify-swagger or fastify-oas)...
> 
> ```js
>   // only 1 worker should export api spec to a file in development mode only.
>   if (process.env.NODE_ENV === 'development' && cluster.isWorker && cluster.worker.id === 1) {
>     const specFile = './docs/data-api.json';
> 
>     fastify.ready(() => {
>       const apiSpec = JSON.stringify(fastify.swagger(), null, 2);
> 
>       writeFile(specFile, apiSpec, (err) => {
>         if (err) {
>           return fastify.log.error(`failed to save api spec to ${specFile}`);
>         }
>         fastify.log.debug(`saved api spec to ${specFile}`);
>       });
>     });
>   }
> ```
> 
> I also added a shell script to do it...
> 
> ```shell
> #!/bin/sh
> # generate_docs.sh -- dumb/hacky way of generating html documentation for the APIs.
> # requires redoc-cli to be installed
> 
> # start dev server in the background and wait for it to start
> yarn dev &
> sleep 5
> 
> # download api spec from swagger-ui
> curl localhost:3000/docs/json > docs/data-api.json
> 
> # kill dev server
> pkill -f 'yarn.js dev'
> 
> # generate static html documentation
> redoc-cli bundle docs/data-api.json --output docs/data-api.html
> ```

Thank you @bburke4! This was a lifesaver!

**Comment by Mael-Abgrall** [comment]
I saw this from Google, just simplifying the script as this is what we use for our CI/CD with modern JS. This doesn't require running the server or shell scripts

```typescript
import { writeFile } from 'node:fs/promises';
import { app } from '../src/api-config.js';

await app.ready();

if (app.swagger === null || app.swagger === undefined) {
  throw new Error('@fastify/swagger plugin is not loaded');
}

const schema = JSON.stringify(app.swagger(), undefined, 2);
await writeFile('doc/openapi.json', schema, { flag: 'w+' });

await app.close();
```

and then call this script from package.json during your pipeline
```package.json
"scripts": {
    "gen-schema": "tsx scripts/generate-openapi-schema.ts"
  },
```
