### ISSUE TITLE
How to hide explore and link to json

### ISSUE THREAD

**Issue by Banonevar** [fastify/fastify-swagger#189]
Everything in title, but i attach additional screenshot what i want to hide.
![img](https://i.imgur.com/vnHQIDO.png)

**Comment by Eomm** [comment]
I thinkg if you can do with swagger-ui module, you could send a PR here to archive this targer

**Comment by Fdawgs** [comment]
This can be hidden by setting  `uiConfig.layout` to "BaseLayout".
See https://github.com/fastify/fastify-swagger/issues/455#issuecomment-901646025
