### ISSUE TITLE
Missing configuration support for swagger online validator

### ISSUE THREAD

**Issue by 4irmann** [fastify/fastify-swagger#191]
when runnning fastify-swagger inside a docker container - without internet access - swagger online validator can not be accessed. This causes an error message "can't read from file <host>/json" (red banner gui's bottom). The issue is well known and e.g. discussed here: https://stackoverflow.com/questions/32188386/cant-read-from-file-issue-in-swagger-ui

According to swagger-ui documentation https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md the config parameter "validatorUrl" can be set to null, or an alternative validator can be set. 

Would be great if this config parameter would be supported via fastify-swagger option

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by useo6** [comment]
I'm having the same problem atm after I deployed my project on Heroku. Any idea how to solve this?

**Comment by 4irmann** [comment]
This is issue was implicity solved via https://github.com/swagger-api/swagger-ui/issues/5710 and can be closed.
In order to disable validator, just add validatorUrl config to your fastify swagger config, e.g.:

`exposeRoute: true,
swagger : {
 // my swagger config
},
uiConfig: {
  validatorUrl: null
}`

See also https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

**Comment by jrauschenbusch** [comment]
@4irmann @mcollina Why was this issue closed? The config param `validatorUrl` is not available within `fastify-swagger` configuration options.
