### ISSUE TITLE
Capitalized header shows up twice in generated docs

### ISSUE THREAD

**Issue by JemarJones** [fastify/fastify-swagger#197]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/fastify) or [Fastify Help](https://github.com/fastify/help) and ask any questions you have or mention any problems you've had getting started with Fastify.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

When specifying a capitalized header in the schema of a request, the key shows up twice in the generated docs. Once with the capitalization, and once lowercased.  

## To Reproduce

Paste your code here:

```js
// JsonSchema for my post request
 {
  headers: {
    type: 'object',
    required: ['Authorization'],
    properties: {
      // Fastify lowercases all headers https://github.com/fastify/help/issues/71
      Authorization: { type: 'string' }
    }
  }
 // ...etc
}
```

![image](https://user-images.githubusercontent.com/6874590/63099299-cd9ee480-bf42-11e9-95f1-bd929de01709.png)

## Expected behavior

The header should only show up once. With the capitalization that is specified.

Paste the results here:

![image](https://user-images.githubusercontent.com/6874590/63099589-62a1dd80-bf43-11e9-943e-7533075e0c5a.png)

## Your Environment

- *node version*: v10.14.2
- *fastify version*: >= 2.4.1
- *os*: MacOS 10.14.6

**Comment by mcollina** [comment]
would you like to send a PR?

Il giorno gio 15 ago 2019 alle 16:00 Jemar Jones <notifications@github.com>
ha scritto:

**Comment by JemarJones** [comment]
If i can find some time then i will give it a shot!

**Comment by JemarJones** [comment]
Turned out to be an issue in fastify itself. Submitted a fix there https://github.com/fastify/fastify/pull/1806.

**Comment by Fdawgs** [comment]
@JemarJones Think this can be closed if it has been resolved? 😊
