### ISSUE TITLE
Remove dynamic requirements

### ISSUE THREAD

**Issue by scriptjs** [fastify/fastify-swagger#20]
I use webpack on the server side. ES 6 expects static imports and emits the following warnings. In general, I believe it is bad practice to include dynamic requirements in a module - even while a dynamic import is being considered in ES.

I have replaced my project path with '/path/to/project' in the traces below:
```
WARNING in /path/to/project/index.js
47:15-60 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/fastify-swagger/index.js
 @ ./es6/lib/app/index.js
 @ ./es6/index.js
```
I'll send a PR for this.

**Comment by mcollina** [comment]
This can actually be fixed, thanks!
