### ISSUE TITLE
How to export document like markdown, pdf from fastify-swagger?

### ISSUE THREAD

**Issue by yeongjet** [fastify/fastify-swagger#200]

**Comment by mcollina** [comment]
Have you tried using https://www.npmjs.com/package/swagger-spec-to-pdf? This popped up in a quick research on the interwebs.

**Comment by yeongjet** [comment]
@mcollina 
`swagger2pdf -j -s ./swagger-spec-sample.json -o ./dump/`
So, how to find json file(like swagger-spec-sample.json) for input?

**Comment by mcollina** [comment]
You should be able to get a json at /documentation/json of your server.

**Comment by climba03003** [comment]
Answered.
