### ISSUE TITLE
Dynamic decorator name

### ISSUE THREAD

**Issue by Mokto** [fastify/fastify-swagger#213]
## 🚀 Feature Proposal

Add the possibility to choose a dynamic name for `fastify.decorate('....')` (See https://github.com/fastify/fastify-swagger/blob/master/static.js#L59)

## Motivation

Being able to generate multiple documentations path within a nest app. https://github.com/nestjs/swagger/issues/234

## How to 

The idea would be to pass it as new option (`decoratorName` ?)

**Comment by mcollina** [comment]
Sure, send a PR. Note that in fastify you can achieve this by using multiple levels of plugins via encapsulation: this is an issue on the Nestjs Fastify adapter. See https://www.fastify.io/docs/latest/Decorators/#decorators-and-encapsulation.
I don’t think Nest exposes all of this.
Il 7 nov 2019, 10:41 +0100, Théo Mathieu <notifications@github.com>, ha scritto:

**Comment by Boshen** [comment]
We can close this now, the original problem is fixed in nestjs/swagger
