### ISSUE TITLE
Supply additional configuration to swagger-ui

### ISSUE THREAD

**Issue by Boshen** [fastify/fastify-swagger#228]
## 🚀 Feature Proposal

Swagger ui can be modified by supplying  additional configuration parameters.
It's documented [here](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md)

As far as I can tell, The `new SwaggerUI({...})` call is hard coded in static/index.html,
so there is currently no options to do this in fastify-swagger.

By looking at swagger-ui-express, they served a modified html, see [here](https://github.com/scottie1984/swagger-ui-express/blob/master/index.js#L120).
It this something we can do too?

**Comment by mcollina** [comment]
A PR that implemented that would be awesome!

Il giorno ven 14 feb 2020 alle ore 17:34 Boshen <notifications@github.com>
ha scritto:

**Comment by gustawdaniel** [comment]
Especially if `css` customization would be possible

https://github.com/fastify/fastify-swagger/issues/82

**Comment by giovanni-bertoncelli** [comment]
Any update on this?

**Comment by mcollina** [comment]
@giovanni-bertoncelli Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by giovanni-bertoncelli** [comment]
I can try :)

**Comment by giovanni-bertoncelli** [comment]
@mcollina There you go
