### ISSUE TITLE
SwaggerUi with PKCE

### ISSUE THREAD

**Issue by samaysar** [fastify/fastify-swagger#230]
Hi,

I am using Fastify with NestJs. I would like to use the OAuth2 framework for swagger in our non-prod environments. In fact, we do have an OAuth2 based server which enable us to use Authorization Code with PKCE. However, I am not finding an option to enable it using SwaggerModule and NestFastifyApplication.

I search through swagger documentation which suggests calling SwaggerUI init method. (https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/)

Is there a way to pass those parameters in the document builder or by other means to get this method triggered?
Or is there any on-going work that will include it in the upcoming releases? I would be happy to lend some commits if required.

Many thanks in advances.

**Comment by mcollina** [comment]
Thanks for reporting. Would you like yo send a PR to add the functionality you need? Thanks
