### ISSUE TITLE
relative redirect needed, instead of an absolute one

### ISSUE THREAD

**Issue by PavelPolyakov** [fastify/fastify-swagger#241]
## 🐛 Bug Report

Good day,

In our use case we serve services under multiple proxies.

Imagine we've a service `my-fav-service`, which serves some api AND also serves `swagger` under `my-fav-service/documentation/`. Later, we make a proxy to the service, which proxies all the requests from `https://example.com/public/api/my-fav-service` to `my-fav-service`. 
When we hit `https://example.com/public/api/my-fav-service/documentation` we are redirected to `https://example.com/documentation` because of [this](https://github.com/fastify/fastify-swagger/blob/8187bd074abfa90c30cec4240fffd611582b9240/routes.js#L18).

Which is clear - the redirect, currently, is absolute. I want to change this redirect to the relative, which will work fine, and submit PR.

So these tests should pass:
```js
t.only('/documentation should redirect to ./documentation/static/index.html', t => {
  t.plan(4)
  const fastify = Fastify()
  fastify.register(fastifySwagger, swaggerInfo)

  fastify.get('/', () => {})
  fastify.post('/', () => {})
  fastify.get('/example', opts1, () => {})
  fastify.post('/example', opts2, () => {})
  fastify.get('/parameters/:id', opts3, () => {})
  fastify.get('/example1', opts4, () => {})

  fastify.inject({
    method: 'GET',
    url: '/documentation'
  }, (err, res) => {
    t.error(err)
    t.strictEqual(res.statusCode, 302)
    t.strictEqual(res.headers.location, './documentation/static/index.html')
    t.is(typeof res.payload, 'string')
  })
})

t.only('/documentation/ should redirect to ../documentation/static/index.html', t => {
  t.plan(4)
  const fastify = Fastify()
  fastify.register(fastifySwagger, swaggerInfo)

  fastify.get('/', () => {})
  fastify.post('/', () => {})
  fastify.get('/example', opts1, () => {})
  fastify.post('/example', opts2, () => {})
  fastify.get('/parameters/:id', opts3, () => {})
  fastify.get('/example1', opts4, () => {})

  fastify.inject({
    method: 'GET',
    url: '/documentation'
  }, (err, res) => {
    t.error(err)
    t.strictEqual(res.statusCode, 302)
    t.strictEqual(res.headers.location, '../documentation/static/index.html')
    t.is(typeof res.payload, 'string')
  })
})
```

BUT, in the handler itself, it's impossible to determine which actual url was hit. In both cases `request.raw.url === /documentation`. The `request` objects are identical.

How to approach? Any thoughts? I'm ready to fix this, if there are some ways. Thank you.

## To Reproduce

It's easier to imagine.

## Expected behavior

It should redirect relative to the path which was used to hit the documentation.

## Your Environment

not relevant

**Comment by mcollina** [comment]
Go ahead and send a PR!

**Comment by Eomm** [comment]
> BUT, in the handler itself, it's impossible to determine which actual url was hit.

Not sure, but the `origin` headers could have that information, but for API could not work

**Comment by PavelPolyakov** [comment]
@mcollina 
Sorry, my bad, indeed `req.raw.originalUrl` contains the correct value when you call `/documentation` or `/documentation/`. I was just injecting the same value in the test.

I'll complete MR and send it.

@Eomm yes, some headers may be provided, but this depends on the proxy, I believe it's better to refactor it to use relative paths and be agnostic from the proxy configuration.

**Comment by PDT42** [comment]
Did the fix for this work out? I am in a very similar situation as @PavelPolyakov, trying to serve my fastify-swagger behind a proxy. I would expect that with the provided fix, requests I send to `/some-request` from a swagger instance at `my-proxy.com/fastify-app/docs` would be directed to `my-proxy.com/fastify-app/some-request`. However, this is not the case. Instead swagger directs the request to `my-proxy.com/some-request`. 

Do I get the original issue wrong? I guess I'll have to look into it some more ...
