### ISSUE TITLE
Keep custom fields that start with 'x-' intact in swagger

### ISSUE THREAD

**Issue by ionagamed** [fastify/fastify-swagger#249]
## 🚀 Feature Proposal

I propose to include all fields that start with 'x-' (as per swagger spec https://swagger.io/docs/specification/2-0/swagger-extensions/) in the final swagger specification.  Currently, such extensions in parameters, responses, bodies, etc. are included (because they are passed verbatim), but the path object only keeps properties that are specifically hard-coded.

## Motivation

That would be useful for custom schema renderers that can utilize that additional information about paths.

## Example

```js
  fastify.route({
    method: 'GET',
    url: '/path',
    schema: {
      summary: 'Some method',
      response: {
        200: '...'
      },
      'x-custom-field': 'custom info'
    },
    ...
  })
```

This code should generate something like:

```json
{
  "paths": {
    "/path": {
      "get": {
        ...,
        "x-custom-field": "custom info"
      }
    }
  }
}
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by thomasthiebaud** [comment]
Any update on that issue? I need a fix for that too and I can try to do a PR

**Comment by ionagamed** [comment]
Sorry, did not have time to do a PR, and will probably not have enough in near future. Would be cool if you implement this

**Comment by thomasthiebaud** [comment]
Awesome, I'll have a look 👍

**Comment by thomasthiebaud** [comment]
@ionagamed Should be fixed in https://github.com/fastify/fastify-swagger/pull/256
