### ISSUE TITLE
100% code coverage

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-swagger#258]
As titled!

**Comment by iandrc** [comment]
Hey @mcollina 

I would like to try this one if you don't mind. Are there any pitfalls or something else I should know about?

**Comment by mcollina** [comment]
Not that I know of! Go for it!

**Comment by iandrc** [comment]
@mcollina 

See [#267](https://github.com/fastify/fastify-swagger/pull/267)

I've done a bit of a job, though I need a review and, probably, some help from you or another team member

**Comment by zekth** [comment]
Reopening since the coverage has dropped with: https://github.com/fastify/fastify-swagger/pull/333
and the ci has coveralls landed in : https://github.com/fastify/fastify-swagger/pull/348/files

**Comment by climba03003** [comment]
Closing as it is bug from the `script`.
```Shell
tap --100 test/**/*.js
```

Missing quote for `**` will use the shell evaluation of files, and some of the system may not handle `globstar` as default (e.g. coveralls). As a result, the coverage result drops.
Fixed in #351
