### ISSUE TITLE
Type incorrectness

### ISSUE THREAD

**Issue by robcresswell** [fastify/fastify-swagger#260]
## 🐛 Bug Report

The types listed for fastify-swagger are incorrect; TypeScript complains about the plugin being invalid when calling `register`, but when type checking is disabled it loads fine.

I can push a minimal repro after work, but wanted to open this for now

## To Reproduce

```ts
import Fastify from 'fastify'; // v3.0.0.rc-4
import * as fastifySwagger from 'fastify-swagger'; // v3.1.0

const fastify = Fastify();

fastify.register(fastifySwagger, {
  exposeRoute: true,
  swagger: {
    info: {
      title: process.env.npm_package_name ?? '',
      version: process.env.npm_package_version ?? '',
      description: process.env.npm_package_description,
    },
  },
});
```

## Expected behavior
No TS compilation errors

## Your Environment

- *node version*: 12
- *fastify version*: 3.0.0.rc-4
- *fastify-swagger*: 3.1.0
- *os*: Linux

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by robcresswell** [comment]
Absolutely! Will try and make some time ASAP

**Comment by mcollina** [comment]
thanks!

**Comment by robcresswell** [comment]
I've been looking into this, and I can't really find a pleasant way of doing it that is compatible with Fastify's export style. The types as they are now define a `default` export, which is _not_ representative of the actual export. For example, a default export in ES6 would be translated to

```
module.exports = {
  default: fastifySwagger //pseudo example
}
```

but in reality the export is

```
module.exports = fastifySwagger
```

This is complicated because as far as I can tell, top level exports in ES6 modules **must** be objects, they cannot be callables. Unfortunately, digging into the issue, I realised that every repo in fastify-land seems to have this pattern.

In TypeScript this issue is solvable using ```esModuleInterop: true```, which causes TypeScript to generate a bunch of synthetic imports, but it feels very weird to me that the design of a library should enforce the project using it to be configured in a specific way.

**Comment by robcresswell** [comment]
I could start overloading the exports, but those get weird / ugly very fast, and it feels like using JS's dynamic powers for evil.
