### ISSUE TITLE
Hide a route improvement

### ISSUE THREAD

**Issue by zekth** [fastify/fastify-swagger#277]
from the documentation we can read
```
Sometimes you may need to hide a certain route from the documentation, just pass { hide: true } to the schema object inside the route declaration.
```
Problem with this implementation is when you're using other middlewares to expose your routes like https://github.com/seriousme/fastify-openapi-glue it is no possible. Open api glue verifies the swagger spec based on a json schema and validates it with AJV. Therefore, adding a property to the schema makes it crash.

A proprosal would be to use `tags` instead, which are array of strings. What do you think?

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests. Don't remove the `hide: true` behavior.

**Comment by zekth** [comment]
> Would you like to send a Pull Request to address this issue? Remember to add unit tests. Don't remove the `hide: true` behavior.

Sure but we might need to find a proper tag for it. Eg: `X-HIDDEN` or something like this. Feel free to give opinion.

**Comment by mcollina** [comment]
Whatever you think it's best!
