### ISSUE TITLE
How to hide the default route in swagger created by the under-pressure plugin /status /live or /alive

### ISSUE THREAD

**Issue by Harshitparsai** [fastify/fastify-swagger#284]
![Screenshot from 2020-08-17 15-04-34](https://user-images.githubusercontent.com/37847566/90382952-17ae2f00-e09d-11ea-94f3-062d3aaa85dd.png)
  
fastify.register(async function (fastify) {
    fastify.register(underPressure, {

      maxEventLoopDelay: fastify.config.MAX_EVENT_LOOP_DELAY,
      maxHeapUsedBytes: fastify.config.MAX_HEAP_USED_BYTES,
      maxRssBytes: fastify.config.MAX_RSS_BYTES,

      exposeStatusRoute: "/live",
    });

**Comment by mcollina** [comment]
you can do:

```js
app.register(async function yourRoutes (app) {
  app.register(swagger, ...)
  app.register(routes)
})
app.register(underPressure)
```

Another option is to send a PR to under-pressure so that in https://github.com/fastify/under-pressure/blob/213f8999a620f572531165cdec0b57255d879784/index.js#L80-L96 we pass a `hide: true` inside the schema.
