### ISSUE TITLE
Any type of object in the array I am attaching screenshot of the required 

### ISSUE THREAD

**Issue by Harshitparsai** [fastify/fastify-swagger#292]
![Screenshot from 2020-09-02 11-51-24](https://user-images.githubusercontent.com/37847566/91939180-fbec8f00-ed12-11ea-9dda-28ae53024c17.png)

## Example

I want something like this in fastify swagger how to achieve it

**Comment by climba03003** [comment]
You can switch between "Example Value" and "Model"
![image](https://user-images.githubusercontent.com/23028015/94295664-2806d300-ff94-11ea-8bc8-5e0524ef11db.png)

**Comment by Fdawgs** [comment]
@Harshitparsai Did climba's solution solve your problem?

**Comment by mcollina** [comment]
One year has passed, let's assume this.

@Fdawgs maybe we should check if stalebot is enabled everywhere, 3-6 months of inactivity seems a good measure.

**Comment by Fdawgs** [comment]
Cheers @mcollina!

Out of the 100-odd repos in the Fastify org it's only enabled for 46 from looking at https://github.com/apps/stale/installations/new, I don't have permissions to update Stale's access.
Would you be able to take a look when you get a second please?

**Comment by Fdawgs** [comment]
> Out of the 100-odd repos in the Fastify org it's only enabled for 46 from looking at https://github.com/apps/stale/installations/new, I don't have permissions to update Stale's access. Would you be able to take a look when you get a second please?

@mcollina Mind reviewing this please? Would be nice to cut down on old issues.

**Comment by Eomm** [comment]
I can do that, but it is not possible for me to configure `all the repos`. I should select all the repos manually

**Comment by Fdawgs** [comment]
Thanks @Eomm!
