### ISSUE TITLE
Available authorizations  input  token value   invalid

### ISSUE THREAD

**Issue by junbao520** [fastify/fastify-swagger#293]
![image](https://user-images.githubusercontent.com/20721833/91965816-9cf33e00-ed43-11ea-9cc8-1d78453f725b.png)

When I require, the swagger did not bring the token entered in the header

**Comment by fox1t** [comment]
Can you make a repro repository so we can look into this?

**Comment by junbao520** [comment]
ok! 
wait a moment，I will make a repro repository

**Comment by junbao520** [comment]
[Server-test-swagger-token.zip](https://github.com/fastify/fastify-swagger/files/5165797/Server-test-swagger-token.zip)

I'm very sorry that the code can't be uploaded to GitHub directly due to my local computer environment problem.
This is a test project to test and obtain the token I entered on the swagger interface.

thank you very much!

**Comment by Eomm** [comment]
Sorry but I will not download a zip file

Anyway I created a PR #295 with a working example and it is working:

![Immagine 162](https://user-images.githubusercontent.com/11404065/92301835-47977680-ef67-11ea-821e-3e4939ed0472.png)

Please share your code to other platforms like pastebin if you would like to get help for your problem.
Remember that we need to know the versions of your dep

**Comment by jherjati** [comment]
It works in swagger, thank you @Eomm !

But unfortunately when i try to upgrade to openapi, it doesn't work. I don't know why, openapi can't fill the auth header.. (?)

**Comment by mcollina** [comment]
cc @climba03003

**Comment by climba03003** [comment]
> 
> 
> It works in swagger, thank you @Eomm !
> 
> But unfortunately when i try to upgrade to openapi, it doesn't work. I don't know why, openapi can't fill the auth header.. (?)

Simple example for OpenAPI 3
```JS
const Fastify = require("fastify");
const FastifySwagger = require("fastify-swagger");

const app = Fastify();
app.register(FastifySwagger, {
  openapi: {
    security: {
      Bearer: [],
    },
    components: {
      securitySchemes: {
        Bearer: {
          type: "http",
          scheme: "bearer",
        },
      },
    },
  },
  routePrefix: "/documentation",
  exposeRoute: true,
});

app.get(
  "/",
  {
    schema: {
      security: [
        {
          Bearer: [],
        },
      ],
    },
  },
  (req, reply) => {
    reply.send("foo");
  }
);

app.listen(3000);
```

**Comment by climba03003** [comment]
Closing as examples for both swagger and openapi is provided
