### ISSUE TITLE
Address content security policy for documentation route

### ISSUE THREAD

**Issue by benediktdertinger** [fastify/fastify-swagger#294]
## 🚀 Feature Proposal

If you use e.g. `fastify-helmet` to define security related headers the current setup of the `fastify-swagger` documentation does not meet these standards. To make swagger work with helmet you have to add the following helmet options:
```
.register(helmet, {
    contentSecurityPolicy: {
        directives: {
            defaultSrc: [`'self'`],
            styleSrc: [`'self'`, `'unsafe-inline'`],
            imgSrc: [`'self'`, 'data:', 'validator.swagger.io'],
            scriptSrc: [`'self'`, `https: 'unsafe-inline'`],
        },
    },
})
```

## Motivation

To meet security standards and make implementation easier.

## Example

a) extract code into files (not possible for dynamically created images by swagger validator js)
```
styleSrc: [`'self'`, `'unsafe-inline'`], --> Move inline style in index.html (line 10) to external file
imgSrc: [`'self'`, 'data:', 'validator.swagger.io'], --> Move images to external files (!! set by swagger validator !!)
scriptSrc: [`'self'`, `https: 'unsafe-inline'`], --> Move inline js in index.html (line 38) to external file
```
b) auto add helmet (if registered) options to the related exposed `/documentation` route

**Comment by mcollina** [comment]
I think it's fine to just document these in the README.

**Comment by climba03003** [comment]
I am facing the same issue, can we compute the script and style `sha-256` hashes beforehand and place it to the fastify.
The main reason is that I do not want to use `unsafe-inline` for both script and style.
Example setting to use `sha-256`
```typescript
fastify.register(FastifyHelmet, {
    contentSecurityPolicy: {
      directives: {
        scriptSrc: [
          "'self'",
          "'sha256-iV83EgAQc1+Q++O7L1ZemfWFbYYPNv2syB2HreE5S/8='"
        ],
        styleSrc: ["'self'", 'https:', "'unsafe-inline'"],
      }
    }
  }

**Comment by Eomm** [comment]
I think the `sha` on `prepare-swagger-ui.js` would be the best approach since a static/fixed nonce seems like it doesn't exist to me.

How could we expose that `sha` so the users can use it?
It could change at any release

**Comment by climba03003** [comment]
Can we create a ```sha.json``` in ```prepare-swagger-ui.js```. Then put it in ```fastify``` through ```decorators```.
Example.
```javascript
fastify.decorate('swagger-sha', require('<location-to-json>/sha.json'))
```

**Comment by mcollina** [comment]
that works!

**Comment by climba03003** [comment]
I have created a draft PR. I think some of the area still need to be clarify before actual merge.
