### ISSUE TITLE
Response description prop is not appended correctly to schema definition

### ISSUE THREAD

**Issue by MetCoder95** [fastify/fastify-swagger#299]
## 🐛 Bug Report

When defining a response schema definition,
and compiling to swagger spec, the `description` prop is not appended correctly ending with unexpected behavior where the Swagger UI doesn't show the custom description provided

## To Reproduce

**Input**:
```js
{
   "response":{
      200:{
         "type":"object",
         "properties":{
            "hello":{
               "type":"string"
            }
         },
         "description":"some description"
      }
   }
}
```

**Output**:
```json
{
   "responses":{
      "201":{
         "schema":{
            "type":"object",
            "properties":{
               "hello":{
                  "type":"string"
               }
            },
            "description":"some description"
         },
         "description":"Default Response"
      }
   }
}
```

## Expected behavior

**Input**:
```js
{
   "response":{
      "200":{
         "type":"object",
         "properties":{
            "hello":{
               "type":"string"
            }
         },
         "description":"some description"
      }
   }
}
```

**Output**:
```json
{
   "responses":{
      "201":{
         "schema":{
            "type":"object",
            "properties":{
               "hello":{
                  "type":"string"
               }
            }
         },
         "description":"some description"
      }
   }
}
```

## Your Environment

- *node version*: 14.11
- *fastify version*: 3.4.1
- *fastify-swagger version*: 3.3.0
- *os*: Mac
- *any other relevant information*

**Comment by zekth** [comment]
Looks like this issue come from those lines : https://github.com/fastify/fastify-swagger/blob/3fb41c0ea2cc44ec917e9abfc80525e7412c30ed/dynamic.js#L168-L170

@Eomm is there a particular reason to do this?

**Comment by Eomm** [comment]
The `description` is [mandatory](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject) and it must be at `2xx` level.

Valid:
```
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
```

Invalid:

```
      responses:
        description: "Invalid supplied"
```

So this desired output would break swagger-ui I think:

```json
"responses": {
	"201": {
		"schema": {
			"type": "object",
			"properties": {
				"hello": {
					"type": "string"
				}
         	}
    	},
    	"description": "some description"
	}
}
```

**Comment by MetCoder95** [comment]
But that output is fin, isn't it?

I mean, when I have this output:
```json
"responses": {
	"201": {
		"schema": {
			"type": "object",
			"properties": {
				"hello": {
					"type": "string"
				}
         	},
         	"description": "some description"
    	},
    	"description": "Default Response"
	}
}
```

The custom `description` is under the `schema` object, where is not recognized by the swagger spec as part of the `schema` object. So, when you render the UI swagger automatically looks for the `description` prop inside of the `201` response which is the default one and not the custom one. It shouldn't break anything as it correctly works with the default and should work if we pass the custom one. Or I'm missing something?

**Comment by climba03003** [comment]
> 
> 
> The `description` is [mandatory](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject) and it must be at `2xx` level.
> 
> Valid:
> 
> ```
>       responses:
>         "400":
>           description: "Invalid ID supplied"
>         "404":
>           description: "Pet not found"
>         "405":
>           description: "Validation exception"
> ```
> 
> Invalid:
> 
> ```
>       responses:
>         description: "Invalid supplied"
> ```
> 
> So this desired output would break swagger-ui I think:
> 
> ```json
> "responses": {
> 	"201": {
> 		"schema": {
> 			"type": "object",
> 			"properties": {
> 				"hello": {
> 					"type": "string"
> 				}
>          	}
>     	},
>     	"description": "some description"
> 	}
> }
> ```

I think the main reason is we do not have a way to pass in the ```description``` for the response.
```
response: {
  "201": {  } // this is strictly passed to the schema object, thus we cannot set the description for response
}
```

**Comment by climba03003** [comment]
> 
> 
> But that output is fin, isn't it?
> 
> I mean, when I have this output:
> 
> ```json
> "responses": {
> 	"201": {
> 		"schema": {
> 			"type": "object",
> 			"properties": {
> 				"hello": {
> 					"type": "string"
> 				}
>          	},
>          	"description": "some description"
>     	},
>     	"description": "Default Response"
> 	}
> }
> ```
> 
> The custom `description` is under the `schema` object, where is not recognized by the swagger spec as part of the `schema` object. So, when you render the UI swagger automatically looks for the `description` prop inside of the `201` response which is the default one and not the custom one. It shouldn't break anything as it correctly works with the default and should work if we pass the custom one. Or I'm missing something?

I think you example indentation is weird, so the other cannot find the problem at the first glance.

**Comment by MetCoder95** [comment]
Got it! Sorry for that, I grab it directly from the terminal, I think might be because of that. Thanks for the support 🙏

**Comment by jeremy-w** [comment]
It looks like this issue is now fixed.
