### ISSUE TITLE
Cannot find module 'fastify-swagger'

### ISSUE THREAD

**Issue by incubus8** [fastify/fastify-swagger#3]
fastify-swagger module not published the latest version

```
module.js:538
    throw err;
    ^

Error: Cannot find module 'fastify-swagger'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

Project:
![screen shot 2017-11-10 at 2 06 03 pm](https://user-images.githubusercontent.com/5300674/32646736-906c7b08-c620-11e7-9dd5-0683d361679f.png)

As above screenshot is shown, I can only see one file `package.json` after installing fastify-swagger. 

Is this project well maintained?

**Comment by delvedor** [comment]
Apparently there was an issue during the publish. Try now :)

**Comment by incubus8** [comment]
ok, it works! Thank you.
