### ISSUE TITLE
Swagger extension are not included if defined at the root

### ISSUE THREAD

**Issue by thomasthiebaud** [fastify/fastify-swagger#304]
## 🐛 Bug Report

[Swagger extensions](https://swagger.io/docs/specification/2-0/swagger-extensions/) are not supported at the root of the spec

## To Reproduce

This code

```typescript
import fastifySwagger from "fastify-swagger";
fastify.register(fastifySwagger, { swagger: { "x-tension": "test" } });
```

throw a type error

```
Type '{ "x-tension": string; }' is not assignable to type 'Partial<Spec>'.
      Object literal may only specify known properties, and '"x-tension"' does not exist in type 'Partial<Spec>'
```

and I can verify that the extension is not included in the documentation.

## Your Environment

- *node version*: 12
- *fastify version*: ^3.4.1
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by thomasthiebaud** [comment]
Yes I can do that

**Comment by mcollina** [comment]
Go for it!
