### ISSUE TITLE
Unable to generate the /documentation Swagger URI

### ISSUE THREAD

**Issue by panbhatt** [fastify/fastify-swagger#31]
Hi Team,
I am testing this plugin with Fastify 1.0.0-rc-2 and even after lot of attempts unable to get the swagger UI up. The JSON representation shows that the default URL /documentation is not a part of swagger configuration that is being returned. 

{"swagger":"2.0","info":{"title":"Test swagger","description":"testing the fastify swagger api","version":"0.1.0"},"host":"localhost","schemes":["http"],"consumes":["application/json"],"produces":["application/json"],"paths":{"/":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/error":{"get":{"responses":{"200":{"description":"Default Response"}}}},"/some-route/{id}":{"put":{"summary":"qwerty","description":"post some data","tags":["user","code"],"parameters":[{"name":"body","in":"body","schema":{"type":"object","properties":{"hello":{"type":"string"},"obj":{"type":"object","properties":{"some":{"type":"string"}}}}}},{"name":"id","in":"path","required":true,"description":"user id","type":"string"}],"responses":{"201":{"schema":{"description":"Successful response","type":"object","properties":{"hello":{"type":"string"}}},"description":"Successful response"}}}},"/ram":{"get":{"responses":{"200":{"description":"Default Response"}}}}}}

This is what I am getting. All the source code is available at https://github.com/panbhatt/Fastify-api-boilerplate ( in master branch ). Please HELP.

**Comment by delvedor** [comment]
You are using `fastify-swagger-ui`, this plugin is `fastify-swagger`.
If you switch to **this** plugin you can expose the swagger ui by adding `{ exposeRoute: true }` as shown [here](https://github.com/fastify/fastify-swagger#swagger-options).

**Comment by panbhatt** [comment]
Even this one is not working. 

const fastify = require('fastify')();

fastify.register(require('fastify-swagger'), {
  swagger: {
    info: {
      title: 'Test swagger',
      description: 'testing the fastify swagger api',
      version: '0.1.0'
    },
    host: 'localhost',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    securityDefinitions: {
      apiKey: {
        type: 'apiKey',
        name: 'apiKey',
        in: 'header'
      }
    }
  }
})

fastify.put('/some-route/:id', {
  schema: {
    description: 'post some data',
    tags: ['user', 'code'],
    summary: 'qwerty',
    params: {
      type: 'object',
      properties: {
        id: {
          type: 'string',
          description: 'user id'
        }
      }
    },
    body: {
      type: 'object',
      properties: {
        hello: { type: 'string' },
        obj: {
          type: 'object',
          properties: {
            some: { type: 'string' }
          }
        }
      }
    },
    response: {
      201: {
        description: 'Successful response',
        type: 'object',
        properties: {
          hello: { type: 'string' }
        }
      }
    },
    security: [
      {
        "api_key": []
      }
    ]
  }
}, (req, reply) => {})

fastify.ready(err => {
  if (err) throw err
  console.log(JSON.stringify(fastify.swagger( { exposeRoute : true })) );
});


fastify.listen(3000, '127.0.0.1', function (err) {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})

**Comment by delvedor** [comment]
Please use [code highlighting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) when pasting code, it will be easier to read.

You should pass `exposeRoute: true` to the plugin option:
```js

fastify.register(require('fastify-swagger'), {
  swagger: {
    info: {
      title: 'Test swagger',
      description: 'testing the fastify swagger api',
      version: '0.1.0'
    },
    host: 'localhost',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    securityDefinitions: {
      apiKey: {
        type: 'apiKey',
        name: 'apiKey',
        in: 'header'
      }
    }
  },
  exposeRoute: true
})
```

**Comment by panbhatt** [comment]
Thanks a lot. it is working now. This is of Immense help. I would keep code highlighting in my mind. I Apologize for it.

**Comment by Dgdaniel** [comment]
Me also am using swaager but it still not working though the attribute exposeRoute is set to true

**Comment by Dgdaniel** [comment]
Finally I have found that the problem was that the port **_were being used_**. So I have change It and it work
