### ISSUE TITLE
Response without a body is unsupported

### ISSUE THREAD

**Issue by pelepelin** [fastify/fastify-swagger#313]
## 🐛 Bug Report

Swagger 2 allows to specify a response without a body by omitting `schema` field. 

https://swagger.io/specification/v2/#responseObject
> If this field does not exist, it means no content is returned as part of the response.

fastify + fastify-swagger do not provide a way to specify response without a body. Note that a response with empty object is not the same as no body. This is most important when used with [204 status code](https://tools.ietf.org/html/rfc7231#section-6.3.5) which must not contain a body.

## To Reproduce

```js
const schema = {
  response: {
    204: {
      description: 'Success'
    }
  }
}
```

Gives fatal error
```
Could not start server: FastifyError [FST_ERR_SCH_SERIALIZATION_BUILD]: Failed building the serialization schema for POST: /url, due to error schema is invalid: data.properties['description'] should be object,boolean
```
And
```js
const schema = {
  response: {
    204: {
      type: "object",
      description: 'Success'
    }
  }
}
```

produces Swagger schema which assumes `{}` (empty object) body.
```json
"responses":{"204":{"schema":{"type":"object","description":"Success"},"description":"Success"}}
```

And
```js
const schema = {
  response: {
    204: {
      type: "null",
      description: 'Success'
    }
  }
}
```

produces Swagger schema which is still not equal to no content
```json
"responses":{"204":{"schema":{"type":"null","description":"Success"},"description":"Success"}}}
```

## Expected behavior

Given the schema

```js
const schema = {
  response: {
    204: {
      description: 'Success'
    }
  }
}
```

Should produce Swagger schema
```json
"responses":{"204":{"description":"Success"}}
```

## Your Environment

- *node version*: 12
- "fastify": "3.7.0",
- "fastify-swagger": "3.4.0",
- *os*: Linux

## Related

#13 fist report, different error message
#19 unfinished PR
#115 report, duplicate of #13
#116 unfinished PR
fastify/fastify#609 claims this is fixed, but apparently it's not, just the error message is different. I guess that without explicit `type` fastify serialization treats "description" as a field declaration, which it is not.

Both #19 and #116 try to fix the issue using explicitly specified `type: 'null'`, which IMHO is not ideal because it should not be required unless there is no other way to disable JSON validation and serialization for such responses as they're in fact not JSON.

**Comment by pelepelin** [comment]
On the last point, the error `data.properties['description'] should be object,boolean` shows that without the `type` property `// the contract syntax` is triggered which is only casually mentioned in https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#serialization

Still, there should be some other prefered way to solve the issue than specifying `type: 'null'`, because `type: 'null'` is a valid JSON-schema type. I would propose something like `type: 'void'` or `'none'` or `false` (not a string) which would be checked before passing to fast-json-stringify.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by pelepelin** [comment]
I'm not sure I already have all parts. Solution should
- Create correct swagger spec.
- Do not create JSON serialization function and use a function which always returns undefined instead.
- Additionally, 204 is already special-cased in fastify, so if other status codes should be supported, it may need changes there.

**Comment by JacopoDaeli** [comment]
+1 on this. I may gonna look into this soonish myself.
