### ISSUE TITLE
Hide options are checked before transform

### ISSUE THREAD

**Issue by FriesFlorian** [fastify/fastify-swagger#316]
## 🐛 Bug Report

The options to hide a route from the documentation are checked before the transform function is executed. 
This prevents being able to hide a route by adding `hide: true` or the hiddenTag to `tags` in transform()

## To Reproduce

```js
exposeRoute: true,
hiddenTag: "X-HIDDEN",
transform: schema => {
  return { ...schema, hide: true, tags: ["X-HIDDEN"] };
}
```

## Expected behavior

The above example should hide all routes.

From [`dynamic.js`](https://github.com/fastify/fastify-swagger/blob/master/dynamic.js):

```js
      if (route.schema && route.schema.hide) {
        continue
      }

      if (route.schema && route.schema.tags && route.schema.tags.includes(hiddenTag)) {
        continue
      }

      const schema = transform
        ? transform(route.schema)
        : route.schema
````

I think the two conditions should be executed after the schema transform() call

## Your Environment

- *node version*: 14.4.0
- *fastify version*: ^3.7.0
- *fastify-swagger*: ^3.1.2

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by FriesFlorian** [comment]
@mcollina just did that!

**Comment by FriesFlorian** [comment]
Closing the issue since https://github.com/fastify/fastify-swagger/pull/317 has been merged
