### ISSUE TITLE
Wrong Type for StaticDocumentSpec.document in index.d.ts

### ISSUE THREAD

**Issue by radzom** [fastify/fastify-swagger#327]
Code checks for an object
https://github.com/fastify/fastify-swagger/blob/6799cd424dfb02211e514c7b5257e5c57cea04ab/static.js#L54

but it is defined as a string. 
https://github.com/fastify/fastify-swagger/blob/6799cd424dfb02211e514c7b5257e5c57cea04ab/index.d.ts#L71

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by radzom** [comment]
Sure, but i cannot promise any timeframe.

**Comment by radzom** [comment]
Unit test is already there.
https://github.com/fastify/fastify-swagger/blob/6799cd424dfb02211e514c7b5257e5c57cea04ab/test/static.js#L100

Or what test do you want me to write?

I would like to make the type a bit more strict by using the already included SwaggerSchema.Spec (OpenApiV2).
Is there also a type for OpenApiV3 i can use? 
I just found this project but am unsure to import it.
https://github.com/kogosoftwarellc/open-api/tree/master/packages/openapi-types#readme
Are there other types that should be supported then?

The easy option would be to just specify the type as 'object' but i think we should do better.
