### ISSUE TITLE
feat: add support of OpenAPI spec that ajv do not initially support

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify-swagger#343]
## 🚀 Feature Proposal

Adding the support for following types.
```
{ type: 'string', format: 'binary' }
{ type: 'string', format: 'byte' }
{ type: 'number', format: 'int32' }
{ type: 'number', format: 'int64' }
```
Example for validator can be found in here, [ajv-oai](https://github.com/oaijs/ajv-oai) or [ajv-openapi](https://github.com/touchifyapp/ajv-openapi)

## Motivation

Probably solving all the related issues #47

## Example

As `fastify` itself do not provide a way to `addFormat` in `ajv`. I mange to provide the user a custom `ajv` instance or `validatorCompiler` function which prefixed the additional fomat.

```TS
import Ajv from 'ajv'
export const ajv = new Ajv({
  removeAdditional: true, // remove additional properties
  useDefaults: true, // replace missing properties and items with the values from corresponding default keyword
  coerceTypes: true, // change data type of data to match type keyword
  nullable: true // support keyword "nullable" from Open API 3 specification.
})
ajv.addFormat('binary', { type: 'string', validate: () => true })
ajv.addFormat('byte', { type: 'string', validate: () => true })
ajv.addFormat('int32', { type: 'number', validate: () => true })
ajv.addFormat('int64', { type: 'number', validate: () => true })
export function validatorCompiler ({ schema }: any): Ajv.ValidateFunction {
  return ajv.compile(schema)
}
```

The user can use the `validatorCompiler` in `route-level` or `instance-level` and they can even extend the format support.

### Instance Level Usage
```TS
import { validatorCompiler } from 'fastify-swagger`
fastify.setValidatorCompiler(validatorCompiler)
```

### Route Level Usage
```TS
import { validatorCompiler } from 'fastify-swagger'
fastify.get(
  '/',
  {
    schema: {
      body: {
        type: 'object',
        properties: { file: { type: 'string', format: 'binary' } }
      }
    },
    validatorCompiler
  },
  ( ) => {}
)
```

### Why I do not just add the custom ajv to fastify?
The main reason I do not add the custom `ajv` to `fastify` by option is that it will cause conflict to the user custom one. And it may break all the user when upgrading this package.

**Comment by mcollina** [comment]
Given that an Ajv instance has state, I prefer a factory approach:

```js
function buildValidatorCompiler (
  const ajv = new Ajv({
    removeAdditional: true, // remove additional properties
    useDefaults: true, // replace missing properties and items with the values from corresponding default keyword
    coerceTypes: true, // change data type of data to match type keyword
    nullable: true // support keyword "nullable" from Open API 3 specification.
  })
  ajv.addFormat('binary', { type: 'string', validate: () => true })
  ajv.addFormat('byte', { type: 'string', validate: () => true })
  ajv.addFormat('int32', { type: 'number', validate: () => true })
  ajv.addFormat('int64', { type: 'number', validate: () => true })
  return function (schema) {
    return ajv.compile(schema)
  }
}
```

Another good option would be to add an option to fastify-swagger to override the schema compiler. This would make sure that only the routes that are seen by fastify-swagger see the new validator... which would be correct in the generic case.
The option to disable this behavior can be used to avoid conflicts or if the user are customizing the compiler themselves.

**Comment by Eomm** [comment]
I would add a `formats` sibling key beside the `plugins` one.
Customizing the default validator compiler seems better to me than give to the user to implement it

```
const fastify = require('fastify')({
  ajv: {
    customOptions: {
      nullable: false // Refer to [ajv options](https://ajv.js.org/#options)
    },
    plugins: [
      require('ajv-merge-patch')
      [require('ajv-keywords'), 'instanceof']
    ],
    formats: []
  }
})
```

https://www.fastify.io/docs/latest/Server/#ajv

**Comment by Adityapanther** [comment]
@mcollina  and @climba03003  made pull req for this issue, if you want any changes let me know
