### ISSUE TITLE
Error using properties and additionalProperties

### ISSUE THREAD

**Issue by Nisgrak** [fastify/fastify-swagger#347]
## 🐛 Bug Report

Using the additionalProperties and get the props to validate in "properties" keys make an error with the plugin, but it's the JSON Schema specs (and the validation works well)

![image](https://user-images.githubusercontent.com/19597708/106491352-0fb14280-64b7-11eb-9897-27bb91ad3ff4.png)
![image](https://user-images.githubusercontent.com/19597708/106491368-150e8d00-64b7-11eb-831d-cda03ff3bd22.png)

## To Reproduce

```js
fastify.get('/', {
		schema: {
			query: {
				properties: {
					limit: {
						type: "number",
						default: 100
					},
					offset: {
						type: "number",
						default: 0
					}
				},
				additionalProperties: false
			}
		}
	}, async (request, reply) => {
		return await handler.getAll(request, reply);

	});
```

## Expected behavior

To show the UI without error

## Your Environment

- *node version*: 14
- *fastify version*: 3.11.0
- *os*: Windows WSL 1
- *plugin version*: 4.0.1

**Comment by mcollina** [comment]
What options are you passing to this plugin? What version?


Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Nisgrak** [comment]
I'm using the default, nos using any custom config, last version, 4.0.1.

I don't know where to start.

**Comment by mcollina** [comment]
Maybe @climba03003 could help.

**Comment by climba03003** [comment]
Your schema should be consider as invalid. You are missing `type: 'object'` for query schema.
Please check this [link](http://json-schema.org/understanding-json-schema/reference/object.html) for object schema.

**Comment by Nisgrak** [comment]
@climba03003 now works!!! Then it's an "error" in fastify, it's should raise an error?

**Comment by Nisgrak** [comment]
I mean that the route validation without the `type: "object` works, only don't work the swagger.

Fastify should raise a error because the lacking of `type: "object` (the schema should be consider invalid), but it doesn't.

**Comment by climba03003** [comment]
Missing `type: "object"` is valid in fastify handler, fastify will consider it as `properties` layer and wrap the whole block for validation. It will consider as below in internal of fastify.
```JS
{
  type: 'object',
  properties: {
     <your specified schema>
  }
}
```
I agree that it cause problem for other plugins, but it also gain advantage for easy to use, less nested object.
