### ISSUE TITLE
OA3: global `security` configuration gets ignored

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/fastify-swagger#352]
## 🐛 Bug Report

The global `security` configuration from OA3  (Open API 3) specification doesn't get exposed in the final JSON swagger configuration.
I'm trying to define the `security` configuration globally in the plugin settings like it is shown in the first example of this page: https://swagger.io/docs/specification/authentication/bearer-authentication/. It appears to me that this field it's ignored in the final result.

## To Reproduce

```js
  await fastify.register(
    require('fastify-swagger'),
    {
      exposeRoute: true,
      openapi: {
        info: {
          // infos
        },
        servers: [
          // servers
        ],
        components: {
          securitySchemes: {
            bearerAuth: {
              type: 'http',
              scheme: 'bearer',
              bearerFormat: 'JWT'
            }
          }
        },
        // this field gets ignored :(
        security: [{
          bearerAuth: []
        }]
      }
    }
  );
```

Then call `fastify.swagger()`: the result does not have a `security` key.

## Expected behavior

The result should export the `security` key.

## Workaround

As a workaround I can define a local `security` option for each exposed route by using the `transform` function.

## Hints

I debugged the issue and it seems that, in this point, the field is not expected:

https://github.com/fastify/fastify-swagger/blob/786567810498de5e6b488edd7cd1c22019be6289/lib/spec/openapi/utils.js#L23

I haven't understand if this plugin is completely compatible with OA3 so maybe this is still work in progress...

## Your Environment

- *node version*: 14.15.1
- *fastify version*: >=2.0.0
- *os*: Mac

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by climba03003** [comment]
My bad, missed some of the fields.
