### ISSUE TITLE
Omitting `uiConfig` option crashes the html page

### ISSUE THREAD

**Issue by mukaschultze** [fastify/fastify-swagger#353]
## 🐛 Bug Report

Omitting `uiConfig` field while using static mode causes the `/uiConfig` route to return no content, this crashes the html page when it tries to parse the response JSON.

On [line 62 of `static.js`](https://github.com/fastify/fastify-swagger/blob/master/lib/mode/static.js#L62) it does not try to set the default value of `{}` when the field is missing, as it does for [`dynamic.js` on line 19](https://github.com/fastify/fastify-swagger/blob/master/lib/mode/dynamic.js#L19)

## To Reproduce

I'm actually using NestJS's swagger module, but the description above should be enough since it points to the original files.

```js
httpServer.register(load_package_util_1.loadPackage('fastify-swagger', 'SwaggerModule', () => require('fastify-swagger')), {
    swagger: document,
    exposeRoute: true,
    routePrefix: path,
    mode: 'static',
    specification: {
        document
    }
});
```

## Expected behavior

The default value for `uiConfig` should be `{}`, as stated in the documentation.

## Your Environment

- *node version*: v12.19.1
- *fastify version*: 3.11.0
- *os*: Windows, Linux
- *any other relevant information*

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
