### ISSUE TITLE
Works only once

### ISSUE THREAD

**Issue by Crypt0Graphic** [fastify/fastify-swagger#359]
When i start (npm run dev) my project, i can open swagger url first time without problem:

`http://localhost:3000/documentation/static/index.html`

But second time it seems loading forever. I start project again but nothing changes. No error just loading...

![Screen Shot 2021-02-07 at 08 55 45](https://user-images.githubusercontent.com/9743846/107137963-49a09f80-6922-11eb-8cc5-7fdc395608fa.png)

Bu this works well every time:

`http://localhost:3000/documentation/json`

Seems like there is a problem with /static/index.html

I am using fastify 3.11.0, fastify-swagger 4.1.1. Project created by fastify-cli.

![Screen Shot 2021-02-07 at 08 53 09](https://user-images.githubusercontent.com/9743846/107137932-ff1f2300-6921-11eb-9221-0465864c17d4.png)

![Screen Shot 2021-02-07 at 08 59 11](https://user-images.githubusercontent.com/9743846/107138028-c895d800-6922-11eb-9817-e5381f77e4a1.png)

When i call that url i see 2 more node and Google at port 3000:

![Screen Shot 2021-02-07 at 09 01 57](https://user-images.githubusercontent.com/9743846/107138089-4b1e9780-6923-11eb-9782-8e0b8b6120f4.png)

**Comment by climba03003** [comment]
```JS
await fastify.swagger
```
should be
```JS
await fastify.swagger()
```

**Comment by Crypt0Graphic** [comment]
> ```js
> await fastify.swagger
> ```
> 
> should be
> 
> ```js
> await fastify.swagger()
> ```

Both of them works. I updated but the problem still continues. :/

**Comment by mcollina** [comment]
I would recommend you to upload a repository to reproduce this problem.

**Comment by Crypt0Graphic** [comment]
After fastify.swagger() update i could not open it yesterday. Today i opened but couldn't see any content. Then i change it to fastify.swagger back and it's ok. Really interesting. Both of them works but just swagger without parentheses shows content.

`await fastify.swagger()`;

![Screen Shot 2021-02-09 at 11 05 27](https://user-images.githubusercontent.com/9743846/107333658-ac727200-6aad-11eb-8eb9-10eaf941fc5d.png)

`await fastify.swagger;`

![Screen Shot 2021-02-09 at 11 05 52](https://user-images.githubusercontent.com/9743846/107333685-b5634380-6aad-11eb-91fd-baaf42525e95.png)

**Comment by Crypt0Graphic** [comment]
My App.js & Config (Fastify Options)

![Screen Shot 2021-02-09 at 11 16 36](https://user-images.githubusercontent.com/9743846/107334885-31aa5680-6aaf-11eb-935f-02e24503d661.png)

![Screen Shot 2021-02-09 at 11 16 23](https://user-images.githubusercontent.com/9743846/107334896-34a54700-6aaf-11eb-99d5-a75882e7e02a.png)

**Comment by mcollina** [comment]
There is likely something it was not setup correctly in your application. It's very hard to guess what is not working by looking at screenshots.

__Please upload a runnable script that we can use to reproduce the problem you are facing__.

**Comment by Crypt0Graphic** [comment]
> There is likely something it was not setup correctly in your application. It's very hard to guess what is not working by looking at screenshots.
> 
> **Please upload a runnable script that we can use to reproduce the problem you are facing**.

I sent you an invite for github access.

**Comment by Crypt0Graphic** [comment]
O noticed something at terminal. Here are my 5 attempts. First 4 stuck at loading screen. 5. is successful. As you can see there are not /uiConfig & /json requests at first 4. I hope this helps.

STUCK AT LOADING

![failure1](https://user-images.githubusercontent.com/9743846/107344757-ddfe3400-6ad3-11eb-8308-ec67c59959b1.png)
![failure2](https://user-images.githubusercontent.com/9743846/107344760-dfc7f780-6ad3-11eb-9e8a-fb100b8df54a.png)
![Screen Shot 2021-02-09 at 12 34 29](https://user-images.githubusercontent.com/9743846/107344763-e191bb00-6ad3-11eb-8b8f-d7bcb2fdc517.png)
![Screen Shot 2021-02-09 at 12 35 59](https://user-images.githubusercontent.com/9743846/107344766-e35b7e80-6ad3-11eb-975b-ee9ab40d9596.png)

SUCCESSFUL ONE

![Success](https://user-images.githubusercontent.com/9743846/107344773-e48cab80-6ad3-11eb-9f93-4cf02703283c.png)

**Comment by mcollina** [comment]
> I sent you an invite for github repository.

I am not providing private support _for free_. Please publish some public example to reproduce.

**Comment by Crypt0Graphic** [comment]
You wanted "runnable script" and i sent you access for my real repository. Did I make a mistake? Omg. Sorry.

I wanted to show you exact code. If you think it's my problem, ok. I thought it's about library. My bad.

**Comment by mcollina** [comment]
If you want somebody to help with your problem in Open Source, please produce a simple script that reproduces your problem outside of your application. This should be public and just demonstrate the problem.

While preparing that, you'd likely discover either a) what is causing the bug or b) what differences exists in your code that causes this problem.

**Comment by Crypt0Graphic** [comment]
I provided too many things. How can i provide a simple script except the whole app? I have no a special script that cause problem. I just use fastify-cli project and fastify-swagger as you see. Can't imagine what you want sorry.

Nevermind, i can use it like this. Not a big problem for me. I just wanted to inform you about problem and provide some detail. I think I did it partially. 

Have a nice day.

**Comment by jsumners** [comment]
Please see https://github.com/fastify/fastify-swagger/issues/337 for an example of how to ask a question that others can follow. The problem needs to be exemplified in the most narrow sense possible. Screenshots of small chunks of code and program output do not generally provide any useful information.

These questions need to be in the public eye so that anyone with knowledge can provide assistance if they so desire. Also, no one should be inspecting private code without a contract guaranteeing the rights of all parties.

We welcome bug reports. But we need them to be in a format that will help us determine the issue.

**Comment by zekth** [comment]
Side note, please do not provide screenshots of the code but the code itself in the issue.
