### ISSUE TITLE
SwaggerUi: Static mode UiConfig endpoint issue

### ISSUE THREAD

**Issue by zekth** [fastify/fastify-swagger#362]
## 🐛 Bug Report

In the example the swagger ui does not load because the endpoint `/api/v2/documentation/uiConfig` does not return anything but returns 200 code, however the specs are browseable with `/api/v2/documentation/json` for example.

Might be a serialization issue as the Ui uses `fetch` and expect to parse a `json` response.

## To Reproduce

```js
  const SPECS_PATH = join(__dirname, 'assets', 'v2-spec.yaml');
  server.register(swagger, {
    mode: 'static',
    exposeRoute: true,
    routePrefix: '/api/v2/documentation',
    specification: {
      path: SPECS_PATH,
      baseDir: __dirname
    }
  });
```

## Your Environment

- *node version*: 14.15.1
- *fastify version*: 3.11.0
- *fastify swagger*: 4.1.1

**Comment by climba03003** [comment]
Update to `4.2.0` should solve the issue.
