### ISSUE TITLE
Missing schema name in swagger UI - addSchema API

### ISSUE THREAD

**Issue by guerrap** [fastify/fastify-swagger#364]
#### You have already researched for similar issues? 
Yes

#### What are you trying to achieve, or the steps to reproduce?
I'm defining schemas with the `addSchema` API, but they are displayed without a name in the swagger UI. There's an autogenerated name `def-0`.
I'm using the `openapi` option in the `register` configuration.

```js
app.addSchema({
    $id: "mySchema",
    type: "object",
    properties: {
        prop: { type: "string" },
    },
});
```

#### What was the result you received?
![image](https://user-images.githubusercontent.com/9011637/107368729-3425a400-6ae1-11eb-9896-ebb6e157d73f.png)

#### What did you expect?
To see the `$ids` of the defined schemas as names in the UI. In this case, I expected to see a `mySchema` in the schemes list.
Is there something I am missing? In the docs and in the issues I couldn't find anyone reporting this, maybe there's something I'm doing wrong.

#### Context

* *node version*: 14.8.0
* *fastify version*: 3.11.0
* *os*: Linux

**Comment by mcollina** [comment]
cc @climba03003 @eomm could you take a look

**Comment by climba03003** [comment]
You did nothing wrong, this is the current expected behavior for `fastify-swagger`.
You may keep a track on the following two issue or PR for this functionality
https://github.com/Eomm/json-schema-resolver/pull/4
https://github.com/fastify/fastify-swagger/issues/337

**Comment by guerrap** [comment]
Thank you for the quick response, I'm going to close this since it's duplicated
