### ISSUE TITLE
Fastify.all routes break the documentation generation

### ISSUE THREAD

**Issue by danielsan** [fastify/fastify-swagger#38]
In that case, the method property is an Array but it is assuming it is always a method
```
fastify-swagger/index.js:78
      const method = route.method.toLowerCase()
```

**Comment by mcollina** [comment]
Thanks! Would you like to send a PR?

**Comment by danielsan** [comment]
What should be the approach?

Ignore ```.all``` routes or Iterate the array and creating a documentation for every single HTTP method?

**Comment by mcollina** [comment]
The best approach would be to iterate the array.
