### ISSUE TITLE
CSP violation when used with fastify-helmet

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-swagger#397]
When loading this plugin in the same context as `fastify-helmet`, with that plugin's default configuration, the Swagger UI will not render due to the CSP directive set by Helmet that disallows inline scripts -- https://content-security-policy.com/examples/allow-inline-script/

**Comment by Fdawgs** [comment]
@jsumners, did you try with the settings in the readme under the [integration header](https://github.com/fastify/fastify-swagger#integration)?

**Comment by jsumners** [comment]
😬 no. That's actually going to be complicated given that I load `fastify-helmet` at a different time than I load `fastify-swagger`.

Maybe this plugin can add some `meta` elements to fix this?

**Comment by simoneb** [comment]
I believe we may have addressed something similar here: https://github.com/nearform/titus/pull/757/files. I posted this some time ago in another issue either in this repo or somewhere else but I can't find it now. Does it help?

**Comment by mcollina** [comment]
Can we land something here as well?

**Comment by simoneb** [comment]
I did not work on the PR I linked earlier so I'm not sure if what we put in place there is generic enough to be either documented or included in this package. @jsumners if you check it out and let us know whether that works we can decide what to do next.

**Comment by jsumners** [comment]
> I believe we may have addressed something similar here: [nearform/titus#757 (files)](https://github.com/nearform/titus/pull/757/files). I posted this some time ago in another issue either in this repo or somewhere else but I can't find it now. Does it help?

This is the same thing as suggested by @Fdawgs via the `fastify-swagger` README.

> Can we land something here as well?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#multiple_content_security_policies

Ugh 🙄:

> Adding additional policies can only further restrict the capabilities of the protected resource, which means that there will be no connection allowed and, as the strictest policy, connect-src 'none' is enforced.

So that negates my suggestion that this plugin add new `meta` elements to the template to adjust the CSP settings for the Swagger UI.

My next suggestion is that this plugin implement the "hack" I have done to get around this:

```js
    async function swaggerContextPlugin(fastify) {
      // This hook is only hit within the context of requests to
      // the prefix specified for fastify-swagger.
      fastify.addHook('onSend', (req, res, payload, done) => {
        const headers = res.getHeaders();
        if (headers['content-security-policy']) {
          const csp = headers['content-security-policy'].replace(
            /script-src 'self'/,
            `script-src 'self' 'unsafe-inline'`
          );
          res.header('content-security-policy', csp);
        }
        done();
      });

      fastify.register(swaggerPlugin, swaggerOptions);
    }
    swaggerContextPlugin[Symbol.for('skip-override')] = true;
```

That is not covering all of the issues addressed by the configuration specified in the README. I was just trying to get the UI to even render. So it would need to be expanded for a true solution.

If this plugin is unable to work within the default CSP configuration provided by `fastify-helmet`, by removing the inline script and localizing the other things, then this hack is what I recommend. At least via a toggle. The current "fix" is buried at the bottom of a very long README under a non-obvious heading, and is really quite cumbersome to use.

To further explain my situation:

I have an internal module, let's call it `@example/baseline-fastify`, that exports a `corePlugin`. This core plugin registers some default modules, one of them being `fastify-helmet`. So developers in my org end up writing code like:

```js
const baseline = require('@example/baseline-fastify')
const fastify = require('fastify')()

fastify.register(baseline.corePlugin)

if (process.env.ENABLE_SWAGGER) {
  fastify.register(require('fastify-swagger'), { /* swagger config */})
}
```

Yes, configuration can be passed to `corePlugin`. But then I need to make every developer in my organization aware that if they enable Swagger, they also need to copy and paste this CSP config block into their app....

I thought of another thing that is a bit easier while writing this, and I think I'll implement that to get my team functioning. However, I think making `fastify-swagger` easier to use in combination with `fastify-helmet` is a good idea. It's clearly a common problem.

**Comment by climba03003** [comment]
I think the hack you mention will create more trouble then actually fixing the issue.
I agree that we should have a better way to integrate this plugin with fastify-helmet`.

I am thinking of the two solution.
1. custom options for sending the `csp` header. It will be default as the `strictest` scenario and it will override the `fastify-helmet` csp header.
2. passing `function` for mutating the `csp` header if it is existing.

**Comment by climba03003** [comment]
I have implemented both methods I mentioned in the previous comment.
@jsumners Can you check if this help?
You can simply pass `staticCSP` in the `fastify-swagger` option to override the `fastify-helmet` default CSP.
