### ISSUE TITLE
Crashes server with fastify 2.x.x

### ISSUE THREAD

**Issue by tHBp** [fastify/fastify-swagger#398]
## 🐛 Bug Report

Crashes the server while accessing default documentation path (`/documentation`) using fastify v2.15.1

## Error log
```
/development/fastify-swagger-issue/node_modules/fastify-static/index.js:87
        return reply.raw.statusCode
                         ^

TypeError: Cannot read property 'statusCode' of undefined
    at PassThrough.get (/development/fastify-swagger-issue/node_modules/fastify-static/index.js:87:26)
    at SendStream.isCachable (/development/fastify-swagger-issue/node_modules/send/index.js:404:29)
    at SendStream.send (/development/fastify-swagger-issue/node_modules/send/index.js:636:14)
    at onstat (/development/fastify-swagger-issue/node_modules/send/index.js:729:10)
    at FSReqCallback.oncomplete (fs.js:184:5)
```

## To Reproduce

Sample repo to reproduce behavior here: https://github.com/tHBp/fastify-swagger-398

Simply uses the example, as mentioned here: https://github.com/fastify/fastify-swagger/blob/master/examples/dynamic-swagger.js

## Expected behavior

Should render the swagger doc.

## Your Environment

- *node version*: 14.16.0
- *fastify version*: 2.15.1
- *os*: Mac

## Additional information
From the looks of it, this is potentially due to underlying library `fastify-static` only supporting fastify version 2.x.x in `fastify-static@2.x.x`, but this project uses `fastify-static@4.x.x`

**Comment by tHBp** [comment]
From the looks of it, this is potentially due to underlying library `fastify-static` only supporting fastify version 2.x.x in `fastify-static@2.x.x`, but this project uses `fastify-static@4.x.x`

**Comment by mcollina** [comment]
The last version of fastify-swagger that supports fastify@2 is v2.

**Comment by tHBp** [comment]
> Supports Fastify versions >=2.0.0. Please refer to this branch and related versions for Fastify ^1.9.0 compatibility.

Maybe the documentation could be a bit more clear on that. According to this, it looks like _default_ branch supports all fastify versions 2 and above.

**Comment by mcollina** [comment]
We should really update the readme. good spot!
