### ISSUE TITLE
Allow for custom Swagger UI options to be passed in

### ISSUE THREAD

**Issue by anader123** [fastify/fastify-swagger#399]
## 🚀 Feature Proposal

It doesn't appear that fastify allows for swagger to pass in custom options for the swagger UI. If you view the swagger repo [here](https://github.com/nestjs/swagger/blob/fe498c50e6f87b685b7cf8b72c1c8fd02cd838be/lib/swagger-module.ts#L38), it looks like they can be passed to express, but not fastify

## Motivation

It would allow all the devs using fastify to customize their Swagger UIs

## Example

Here are all the properties that can be customized. 

```
export interface SwaggerCustomOptions {
    explorer?: boolean;
    swaggerOptions?: any;
    customCss?: string;
    customCssUrl?: string;
    customJs?: string;
    customfavIcon?: string;
    swaggerUrl?: string;
    customSiteTitle?: string;
    validatorUrl?: string;
    url?: string;
    urls?: Record<'url' | 'name', string>[];
}

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by climba03003** [comment]
The repo you are pointing to is using `swagger-ui-express` for the `swagger-ui`, they generate the `swagger-ui` when startup.
For this repo, we pack the `swagger-ui` when release. It is not possible for us to customize the `css` and `js` with the flexibility you mention.

Here are the supported options for `swagger-ui`.
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md
