### ISSUE TITLE
Hmm... Find a hard code here

### ISSUE THREAD

**Issue by qusiba** [fastify/fastify-swagger#4]
https://github.com/fastify/fastify-swagger/blob/7d40a7b518c93e2fd43fd2f29a915a7c0dd2f88b/static/index.html#L75

**Comment by qusiba** [comment]
Maybe can use this package https://www.npmjs.com/package/swagger-ui-dist

**Comment by delvedor** [comment]
Pr are welcome :)

**Comment by zenflow** [comment]
I think this can be closed. This URL is no longer hard-coded. This was addressed by PRs #7 & #9.

https://github.com/fastify/fastify-swagger/blob/b6b2b5fa3562cc7d75c5b06ca439d6cadfdb6fb9/static/index.html#L75

**Comment by mcollina** [comment]
Fantastic!
