### ISSUE TITLE
feat: add option to hide untagged routes

### ISSUE THREAD

**Issue by DRoet** [fastify/fastify-swagger#403]
## 🚀 Feature Proposal

Instead of adding `hide: true` to every route we want to exclude, we could make an option to hide everything that is untagged.  All the routes that we actually want to include are usually already tagged anyway.

## Motivation

One of the useful features that [fastify-oas](https://github.com/SkeLLLa/fastify-oas#plugin-options) implemented.

## Example
```js
fastify.register(require('fastify-swagger'), {
   openapi: {...},
   hideUntagged: true,
})
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by zekth** [comment]
couldn't you use `hiddenTag` option instead? see: https://github.com/fastify/fastify-swagger/pull/278

**Comment by DRoet** [comment]
I would prefer a global option to ignore everything that's not tagged, `hiddenTag` still requires tagging to opt-out... I would rather opt-in.

**Comment by DRoet** [comment]
Thanks! happy to say I was able to migrate back to `fastify-swagger` 😄
