### ISSUE TITLE
minLength causes type repeat in same line.

### ISSUE THREAD

**Issue by YanDevDe** [fastify/fastify-swagger#405]
## 🐛 Bug Report

For some reason if you're using the properties with the combination of "type: string" and "minLength: 8", it will somehow create the type "stringst" in swagger:

![image](https://user-images.githubusercontent.com/1526048/115308484-102eb080-a16b-11eb-92fc-060b05decf6a.png)

After playing around I figured out that the string has 6 chars. So any value bigger than "minLength: 6" will produce sort of "string" repeat. As example with value of 12, you get "stringstring".

## To Reproduce

```js
       schema: {
            body: {
                description: "User register information",
                additionalProperties: false,
                type: "object",
                required: ['username', 'password'],
                properties: {
                    username: { type: 'string', minLength: 2 }, //<-- this produces normal
                    password: { type: 'string', minLength: 8 }, //<-- this produces "stringst"
                    test: { type: 'string', minLength: 12 } //<-- this produces "stringstring"
                }
            }
       }
```

## Expected behavior

no matter how big the value of "minLength" is, type should be kept original, like "string".
For minLength/maxLength I would add note somewhere? I guess that's for another issue.

## Your Environment

- *node version*: 12.14.1
- *fastify version*: 3.14.2
- *fastify swagger version*: 4.6.0
- *os*: macOS

**Comment by mcollina** [comment]
We do not generate those values, they are done inside the swagger-ui itself.

**Comment by climba03003** [comment]
Example value is generated by `swagger-ui`, we do not handle this part. Please submit issue to the upstream if you do not want this behavior.
