### ISSUE TITLE
support of JSON schema examples property in generated OpenAPI json file

### ISSUE THREAD

**Issue by abarre** [fastify/fastify-swagger#421]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.16.2

### Plugin version

4.7.0

### Node.js version

14.17.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

The JSON schema used in our API contains `examples` properties as described in the [JSON schema specification](https://json-schema.org/understanding-json-schema/reference/generic.html?highlight=examples).

> The examples keyword is a place to provide an array of examples that validate against the schema. This isn’t used for validation, but may help with explaining the effect and purpose of the schema to a reader. Each entry should validate against the schema in which it resides, but that isn’t strictly required. There is no need to duplicate the default value in the examples array, since default will be treated as another example.

Example of valid JSON schema from the reference on the doc
```json
{
  "title": "Match anything",
  "description": "This is a schema that matches anything.",
  "default": "Default value",
  "examples": [
    "Anything",
    4035
  ],
  "readOnly": true,
  "writeOnly": false
}
```

I notice that the openapi file generate a malformed `examples` property. 
In [openAPI specification](https://swagger.io/docs/specification/adding-examples/), there is two properties : `example` and `examples`.

<img width="987" alt="Capture d’écran 2021-06-02 à 08 33 33" src="https://user-images.githubusercontent.com/928701/120434856-458b0880-c37d-11eb-9540-50bc904a7182.png">

The `example` contains a single value and `examples` contains an object of examples indexed by a key.

In my 

### Steps to Reproduce

I have the following json Schema for a route : 
```js
body: {
    type: 'object',
    required: ['role_name', 'sender_email', 'email', 'given_name', 'family_name'],
    properties: {
      role_name: {
        description: 'The name of the role',
        type: 'string',
        examples: ['Administrator'],
      },
      sender_email: {
        description: 'The email of the sender',
        type: 'string',
        examples: ['example@email.com'],
      },
      email: {
        description: 'The email of the invited user',
        type: 'string',
        examples: ['example@email.com'],
      },
      given_name: {
        description: 'The given name of the invited user',
        type: 'string',
        examples: ['John'],
      },
      family_name: {
        description: 'The family name of the invited user',
        type: 'string',
        examples: ['Doe'],
      },
    },
  }
```

The actual openapi json is 
```json
{
  "requestBody": {
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "required": [
            "role_name",
            "sender_email",
            "email",
            "given_name",
            "family_name"
          ],
          "properties": {
            "role_name": {
              "description": "The name of the role",
              "type": "string",
              "examples": [
                "Administrator"
              ]
            },
            "sender_email": {
              "description": "The email of the sender",
              "type": "string",
              "examples": [
                "example@email.com"
              ]
            },
            "email": {
              "description": "The email of the invited user",
              "type": "string",
              "examples": [
                "example@email.com"
              ]
            },
            "given_name": {
              "description": "The given name of the invited user",
              "type": "string",
              "examples": [
                "John"
              ]
            },
            "family_name": {
              "description": "The family name of the invited user",
              "type": "string",
              "examples": [
                "Doe"
              ]
            }
          }
        }
      }
    }
  }
}
```

### Expected Behavior

The expected openapi json should be to transform the `examples` key from the json schema in an `example` key in openapi schema with the first example :
```json
{
  "requestBody": {
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "required": [
            "role_name",
            "sender_email",
            "email",
            "given_name",
            "family_name"
          ],
          "properties": {
            "role_name": {
              "description": "The name of the role",
              "type": "string",
              "example": "Administrator"
            },
            "sender_email": {
              "description": "The email of the sender",
              "type": "string",
              "example": "example@email.com"
            },
            "email": {
              "description": "The email of the invited user",
              "type": "string",
              "example": "example@email.com"
            },
            "given_name": {
              "description": "The given name of the invited user",
              "type": "string",
              "example": "John"
            },
            "family_name": {
              "description": "The family name of the invited user",
              "type": "string",
              "example": "Doe"
            }
          }
        }
      }
    }
  }
}
```

**Comment by mcollina** [comment]
Good spot!

Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by hionnode** [comment]
Can I take this up, if it's not taken ?

**Comment by mcollina** [comment]
Go for it!

**Comment by joaopedrocampos** [comment]
Hey, sorry I'm late, but is this issue still up to be taken? Already did a PR to try to fix this but didn't open it since @hionnode said he would do it. 

Never contributed to open source and, since I use `fastify-swagger` in some projects, it would be a pleasure to start on it

**Comment by joaopedrocampos** [comment]
Hey, since nobody answered about the PR I decided to open it so you guys can check it and, if you think it's better since @hionnode said that he would like to do this fix, I can close it without any problem.

Also already would like to apologize if the implementation is not in the right direction or something like this, never contributed to opensource and decided to give it a try 🙏

**Comment by mcollina** [comment]
That's great, thanks!
