### ISSUE TITLE
Conflict with HEAD routes

### ISSUE THREAD

**Issue by zekth** [fastify/fastify-swagger#425]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.17.0

### Plugin version

4.7.0

### Node.js version

14.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

all

### Description

Using `exposeHeadRoutes` to `true` on the `fastify` instance will lead to : 

```
AssertionError [ERR_ASSERTION]: Method 'HEAD' already declared for route '/doc/static/*' with constraints '{}'
```

### Steps to Reproduce

```js
const app = fastify({ exposeHeadRoutes: false });
app.register(fastifySwagger, {
    mode: 'dynamic',
    exposeRoute: true,
    uiConfig: {},
....
  })
```

### Expected Behavior

Not crash the fastify instance

**Comment by mcollina** [comment]
Oh no, is this caused by fastify-static? We'd likely just fix it here by passing `wildcard: false` somewhere.

**Comment by zekth** [comment]
I have no idea. I'll try do dig into asap.

**Comment by climba03003** [comment]
I am using the following code for the simulate the bug, but I cannot get the same error. Maybe it is really having conflict in your project.
```js
const fastify = require("fastify");
const fastifySwagger = require("fastify-swagger");

const app = fastify({ exposeHeadRoutes: false });
app.register(fastifySwagger, {
  mode: "dynamic",
  exposeRoute: true,
});
```

**Comment by zekth** [comment]
With exactly the same config as you it shows up for me:
```
$ yarn list --pattern fastify
yarn list v1.22.4
├─ @fastify/ajv-compiler@1.1.0
├─ @fastify/forwarded@1.0.0
├─ @fastify/proxy-addr@3.0.0
├─ aws-lambda-fastify@1.5.0
├─ fastify-caching@6.1.0
├─ fastify-cookie@5.3.1
├─ fastify-cors@6.0.1
├─ fastify-env@2.1.1
├─ fastify-error@0.3.1
├─ fastify-oauth2@4.2.2
├─ fastify-plugin@3.0.0
├─ fastify-server-session@4.0.0
│  └─ fastify-plugin@2.3.4
├─ fastify-static@4.2.2
├─ fastify-swagger@4.7.0
├─ fastify-warning@0.2.0
└─ fastify@3.17.0
```

I'll try to write a working snippet. (code is currently in private repo)

**Comment by climba03003** [comment]
> 
> 
> With exactly the same config as you it shows up for me:
> 
> ```
> $ yarn list --pattern fastify
> yarn list v1.22.4
> ├─ @fastify/ajv-compiler@1.1.0
> ├─ @fastify/forwarded@1.0.0
> ├─ @fastify/proxy-addr@3.0.0
> ├─ aws-lambda-fastify@1.5.0
> ├─ fastify-caching@6.1.0
> ├─ fastify-cookie@5.3.1
> ├─ fastify-cors@6.0.1
> ├─ fastify-env@2.1.1
> ├─ fastify-error@0.3.1
> ├─ fastify-oauth2@4.2.2
> ├─ fastify-plugin@3.0.0
> ├─ fastify-server-session@4.0.0
> │  └─ fastify-plugin@2.3.4
> ├─ fastify-static@4.2.2
> ├─ fastify-swagger@4.7.0
> ├─ fastify-warning@0.2.0
> └─ fastify@3.17.0
> ```
> 
> I'll try to write a working snippet. (code is currently in private repo)

Packages list for testing. 

Note: `fastify` itself will not add `head` route if it is already specified. It is unlikely to be the issue of `fastify-static` as it specify `head` before `get`.

```
$ yarn list --pattern fastify
yarn list v1.22.10
├─ @fastify/ajv-compiler@1.1.0
├─ @fastify/forwarded@1.0.0   
├─ @fastify/proxy-addr@3.0.0  
├─ fastify-error@0.3.1
├─ fastify-plugin@3.0.0
├─ fastify-static@4.2.2
├─ fastify-swagger@4.7.0
├─ fastify-warning@0.2.0
└─ fastify@3.17.0
```

**Comment by zekth** [comment]
I cannot reproduce outside my project so i'll close the issue for now.

**Comment by schantaraud** [comment]
I can reproduce this every time with:

```js
const fastify = require('fastify'),
  swagger = require('fastify-swagger');

(async () => {

  const server = fastify({ exposeHeadRoutes: true });

  server.register(swagger, { exposeRoute: true });

  try {
    await server.ready();
  } catch (error) {
    console.error(error);
  }

})();
```

```
$ npm ls
sandbox@1.0.0 /Users/samuel/Workspaces/GitLab/PINC/pods/node-sandbox
├── fastify-swagger@4.8.3
└── fastify@3.19.1
```

Not sure the root cause is in this repository though.
