### ISSUE TITLE
Output formats like spreadsheets do not show the content example

### ISSUE THREAD

**Issue by CeliaDoolaegheAdeo** [fastify/fastify-swagger#426]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.14.0

### Plugin version

4.3.1

### Node.js version

14.16.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

34

### Description

In a controller with multiple output formats, some media types do not show the content example in swagger.
In my case, I want to retrieve an Excel file with extension `.xlsx`, but when I use the media type `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` (official mime type format for `.xlsx` files), it does not show the content example in Swagger.

### Steps to Reproduce

In a Controller file, my endpoint looks like:

```javascript
@Get()
@ApiOkResponse({
    description: "Data as Excel file",
    content: {
      "application/vnd.ms-excel": { example: "metric;query;version;score\nmetric1;query1;api1;1" },
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": {
        example: "metric;query;version;score\nmetric1;query1;api1;1",
      },
    },
  })
async getExcelFile() { ... }
```

Here the two content examples are the same, but it only shows for `application/vnd.ms-excel` and not for `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`.

### Expected Behavior

Media type `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` shows the content example to help my users use my api.

**Comment by mcollina** [comment]
I'm not sure what framework is providing those extensions, could you include a full example to reproduce with just fastify and fastify-swagger? Something we could run.

Even better, it would be great if you could open a PR to fix this.

**Comment by climba03003** [comment]
I didn't think we support the syntax like `content` for `fastify-swagger`.
Example for your reference
```js
app.register('/', {
  schema: {
    produces: ['application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
    response: {
      200: {
        type: 'string',
        example: 'metric;query;version;score\nmetric1;query1;api1;1'
      }
    }
  }
}, function() {

})
```

**Comment by CeliaDoolaegheAdeo** [comment]
I built a small project to provide an example, and it seems to be working fine ! So it may be a kind of interference with another dependency, or maybe a problem with a version... I am still inquiring on my side, I'll come back to provide the answer when I find it. Thanks for your help !

**Comment by CeliaDoolaegheAdeo** [comment]
It seems like updating dependencies' versions (nest, fastify and swagger) did solve my problem ! So it's working fine now.
Thank you for this great tool, and sorry for the inconvenience !
