### ISSUE TITLE
Make OpenAPI v3 the default in the next major version

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-swagger#429]
As titled, wdyt?

**Comment by zekth** [comment]
I agree with the idea but semantically it would be odd as the name of the repo is `fastify-swagger` (which technically is Open Api V2). What about renaming ? I don't know the chores that renaming a package involves.

**Comment by yogyrd** [comment]
@mcollina , i've used fastify-swagger with OpenAPI v3, how to create documentation with upload file? any example?

**Comment by Xhale1** [comment]
OpenAPI v3 is the future and I would personally love to see it become the new default. As far as renaming the package goes, similar packages in other ecosystem continue to use the swagger branding and changing to fastify-openapi (or similar) could cause SEO issues.

Additionally, this package would continue to user the Swagger UI regardless of OpenAPI being the default or not, thus fastify-swagger continues to make sense imo
