### ISSUE TITLE
Async transformer

### ISSUE THREAD

**Issue by Ovyerus** [fastify/fastify-swagger#446]
## 🚀 Feature Proposal

Add support for async functions/Promise returning functions to the `transform` option.

## Motivation

This would allow the use of libraries/methods of transforming schemas that are asynchronous for one reason or another. As an example, [json-schema-to-openapi-schema](https://github.com/openapi-contrib/json-schema-to-openapi-schema) is strictly async, thus it cannot be used with the current synchronous-only transform syntax.

## Example

```js
const convert = require('@openapi-contrib/json-schema-to-openapi-schema');

fastify.register(require('fastify-swagger'), {
  swagger: { ... },
  ...
  transform: async schema => {
    const {
      params = undefined,
      body = undefined,
      querystring = undefined,
      ...others
    } = schema
    const transformed = { ...others }
    if (params) transformed.params = await convert(params)
    if (body) transformed.body = await convert(body)
    if (querystring) transformed.querystring = await convert(querystring)
    return transformed
  }
}
```

---

I've tried doing this on a branch just before opening this issue, then thought it would be best to discuss this as I noticed that the way I implemented it—making the `swagger` function `async` and then changing the transform call to `await defOpts.transform(route.schema)`—would result in a pretty big breaking change as all `fastify.swagger()` calls would end up returning a Promise instead of just the schema. Perhaps instead it could only end up becoming a async function if the `transform` option is an async function as well, thus preserving existing code, or make it an option passed `fastify.swagger()`—`async: true` most likely (but then how do we handle an async transformer being called without this option being passed?)

**Comment by zekth** [comment]
I'd say this is kind of a breaking change. Having a flag to determine the output is not reliable to me. However this is a good improvement to me. I'd personnaly make `.swagger()` `async` by default on version `5.x` for example.

What do you think @climba03003  ?

**Comment by climba03003** [comment]
`.swagger` is a method for building cache and return schema. It will be run internally for the route. So, any option like async passed inside is not a good idea.

You can detect if tranform return a Promise, run async code if it is, sync code when it is not. Then it will not be a breaking change.

**Comment by mcollina** [comment]
> You can detect if tranform return a Promise, run async code if it is, sync code when it is not. Then it will not be a breaking change.

I agree, adding support for async is not breaking.


Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Ovyerus** [comment]
Sure thing, I'll add it that way
