### ISSUE TITLE
An option to disable TopBar

### ISSUE THREAD

**Issue by SleepWalker** [fastify/fastify-swagger#455]
## 🚀 Feature Proposal

Let's provide an option to hide the needless Topbar:

![image](https://user-images.githubusercontent.com/2536916/129528227-2a843a34-03fc-496c-b012-ea8c953fd8cb.png)

According to [this issue](https://github.com/swagger-api/swagger-ui/issues/3229) to remove topbar you need to modify [swagger initialization js](https://github.com/fastify/fastify-swagger/blob/master/lib/util/prepare-swagger-ui.js#L45-L52) by removing `SwaggerUIStandalonePreset` from plugins and removing `layout` prop. Current `fastify-swagger` config does not allow such modifications

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by SleepWalker** [comment]
@mcollina ok. Where is the better place to add a new config option: `config.hideTopbar` or it's better to use `config.uiConfig.hideTopbar`? The last one looks a better choice but according to docs it should contain only swagger-ui options

**Comment by mcollina** [comment]
I would place it in the uiConfig.

**Comment by SleepWalker** [comment]
Sorry, the issue can be closed. I've found out that it is enough to set `layout: 'BaseLayout'` in ui config :sweat_smile: . Previously I've sought that `SwaggerUIStandalonePreset` must be removed as well.

```js
fastify.register(require('fastify-swagger'), {
  // ...
  exposeRoute: true,
  uiConfig: {
    layout: 'BaseLayout'
  }
})
```
