### ISSUE TITLE
uiConfig -> plugins not being called

### ISSUE THREAD

**Issue by YanDevDe** [fastify/fastify-swagger#457]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.20.2

### Plugin version

4.9.0

### Node.js version

14.17.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.2.3

### Description

According from the README.md, the "uiConfig" is where you can put [Swagger Options ](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md) - but for some reason, the `plugins` seems not to be called at all. 

I've kept most simple plugins to make it easier to reproduce, see steps to reproduce.

### Steps to Reproduce

```js
const fastify = require('fastify')()

fastify.register(require('fastify-swagger'), {
  routePrefix: '/documentation',
  uiConfig: {
    plugins: [{ afterLoad: function() {console.log("hey")}}], // Should produce "hey" in swagger UI, but it wont.
  },
  staticCSP: true,
  transformStaticCSP: (header) => header,
  exposeRoute: true
})

fastify.put('/some-route/:id', {
}, (req, reply) => {})

fastify.ready(err => {
  if (err) throw err
  fastify.swagger()
})

// Run the server!
fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
```

### Expected Behavior

Produce "hey" on Swagger UI (from uiConfig -> plugins -> afterLoad)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by YanDevDe** [comment]
I wish I could help out - however currently I don't have time for it. 😢  But if I do find time, I will! (Unless other contributor is faster lol)

**Comment by climba03003** [comment]
@YanDevDe 
Any function based option is not supported currently, as we pre-bundle `swagger-ui` and the options is passed using fetch. Functions cannot be `eval` and it is not secure to use `eval` in runtime.

Allowing it to pass function means we need either runtime build `swagger-ui` or use `eval` to parse the stringify function.

**Comment by YanDevDe** [comment]
Ah pity! So see this more rather an improvement instead of bug/issue. :) I come from express-swagger and they were supporting just fine. Hence thought it was an unexpected issue.

Maybe an Idea:
At `onSend` hooks - would it be possible to inject here as js files directly from plugins configuration in payload? Or serve plugins as additional endpoint + append it in swagger script element?
https://github.com/fastify/fastify-swagger/blob/649662ea97fe7b11d3e7f50582a4baf275d1a002/lib/routes.js#L40

Yes I'm aware this is not a perfect solution either... 

---

Or another idea would be allowing re-bundle swagger-ui again with the config you wanted? Maybe either per commands or at the fastify start (perhaps toggleable in settings)?

Thanks for the fast reply! (huh, nice play word for fastify 😋 )

**Comment by mcollina** [comment]
how does expres-swagger supports them?

**Comment by YanDevDe** [comment]
It's from https://github.com/scottie1984/swagger-ui-express

And also I figured out they're using pre-built swagger-ui as well and yet it works. Their method is to replace the options into following HTML content:

```
<% swaggerOptions %>
```

More about this functionality can be found here:

https://github.com/scottie1984/swagger-ui-express/blob/master/index.js#L136

Here is the HTML Template:

https://github.com/scottie1984/swagger-ui-express/blob/5824af0db5273b5a3d631537c3f7009df62ab938/index.js#L90

Maybe something similar can be done for prebuilt swagger (with the `<% swaggerOptions %>` to be replaced) in fastify-swagger.
