### ISSUE TITLE
fastify-swagger: protect access of Swagger UI

### ISSUE THREAD

**Issue by simon-tannai** [fastify/fastify-swagger#465]
Hello ! 

I'm using [fastify-swagger ](https://github.com/fastify/fastify-swagger) to generate API documentation. 
It's working fine but I would like to protect the access to Swagger UI with a simple username / password.

Is it possible do to it with fastify-swagger ?

**Comment by kalitas** [comment]
but this will lead that this check runs on every request made to the server..no?

**Comment by fornof** [comment]
yes, that is basic authentication. Generally basic auth is saved in the browser for additional requests so it is transparent to user. 
I might store user/pass in environment variable or in a json file with hashed password, then check the hashes.
