### ISSUE TITLE
file upload schema error 400

### ISSUE THREAD

**Issue by nbalduzzi** [fastify/fastify-swagger#47]
Hi, when i define the schema consumer in endpoint /upload to 'multipart/form-data' for uploading file i dont know wich is the schema structure body for passing the base64 string or the file that i need to upload.

If y define the schema:

```
schema: {
      description: 'Upload file',
      tags: ['Info'],
      consumes: [ 'multipart/form-data' ],
      summary: 'Upload the file to the server',
      body: {
        type: 'object',
        properties: {
          file: {type: 'string'}
        }
      },
      response: {
        200: {
          description: 'Succesful response',
          type: 'boolean'
        }
      }
    }
```

when i send the post get the error:
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "body should be object"
}
```
I fetch in the dynamic.js code looking for the solution but i dont get with it.

Can you help me?

PD: Im sorry if this is not the place for this kind of issues.

Thx

**Comment by mcollina** [comment]
Are you using https://github.com/fastify/fastify-multipart to handle the multipart data? Can you upload a full example to reproduce?

**Comment by mcollina** [comment]
How do you call this? How do I replicate that error?

**Comment by chapuletta** [comment]
this is de ugly part, i did an express ejs server and a html form upload template calling the fastify upload endpoint with file blob and get that error.

Do you need to upload the form express code? i dont understand if i can upload files from swagger or this is and endpoint thay i need exclude form swagger documentation and testing using a html form.

i dont know wich is the data schema that the endpoint need to get the file. In the docs doesnt appear and i stucked.

**Comment by chapuletta** [comment]
@mcollina Done, i follow the example on fastify-multipart and get it work. Im gonna investigate if exist some strategy to upload or pass the file in any way on swagger for documenation.

Thx a lot

**Comment by mcollina** [comment]
How are you doing that?

**Comment by chapuletta** [comment]
@mcollina finnaly i could do what i looking for, now i can upload files calling an http service and not need to put the service url in the form's action.

Now for give a closure to the "issue" i need to know how i can put the upload service in the fastify-swagger and use de ui for uploading files.

Anyone know how achieve this?

**Comment by mcollina** [comment]
I’m not that expert on swagger.

**Comment by chapuletta** [comment]
In the OpenAPI 2.0 specification exists the schema config for the file uploading

```
swagger: '2.0'
info:
  title: Some API
  version: '1'
paths:
  /conversion/nmea/geojson:
    post:
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
      produces:
        - text/plain
      responses:
        '200':
          description: OK
          schema:
            type: string
            example: "File upload successful"
```

but in fastify-swagger way i dont get with the solution

**Comment by mcollina** [comment]
Have you checked the the generate swagger definition matches and includes that `consumes`?
Is swagger-ui capable of understanding that?

**Comment by chapuletta** [comment]
yeah, i cheked that, and enter in the comsumes multipart but not recognize the format property when validate the schema and fail.

For example, with this schema config:
```
schema: {
      description: 'File uploader',
      tags: ['File Manager'],
      summary: 'Upload a file to the server',
      consumes: ['multipart/form-data'],
      body: {
        type: 'object',
        properties: {
          file: {
            type: 'string',
            format: 'binary'
          }
        }
      },
      response: {
        200: {
          description: 'Succesful response',
          type: 'object',
          properties: {
            path: {type: 'string'}
          }
        },
        500: {
          description: 'Error response',
          type: 'object',
          properties: {
            error: {type: 'string'},
            message: {type: 'string'},
            statusCode: {type: 'number'}
          }
        }
      }
    }
```

I get this error: 

**Error: Error: unknown format "binary" is used in schema at path "#"**

the same ocurrs with format: byte, base64.

**Comment by mcollina** [comment]
> Error: Error: unknown format "binary" is used in schema at path "#"

Can you please get a stacktrace for that?

I think we should add a custom keyword to Fastify ajv: https://github.com/epoberezkin/ajv#defining-custom-keywords. 

We would have to replace the stock ajv instance with a custom one with the new keyword: https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#schema-compiler.

Would you like to send a PR to this module? It think it's something that we should ship.

cc @delvedor

**Comment by chapuletta** [comment]
Here is the stacktrace

```
Error: unknown format "binary" is used in schema at path "#/properties/file"
    at Object.generate_format [as code] (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/node_modules/ajv/lib/dotjs/format.js:69:15)
    at Object.generate_validate [as validate] (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/node_modules/ajv/lib/dotjs/validate.js:334:35)
    at Object.generate_properties [as code] (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/node_modules/ajv/lib/dotjs/properties.js:194:26)
    at generate_validate (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/node_modules/ajv/lib/dotjs/validate.js:334:35)
    at localCompile (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/node_modules/ajv/lib/compile/index.js:86:22)
    at Ajv.compile (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/node_modules/ajv/lib/compile/index.js:55:13)
    at Ajv._compile (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/node_modules/ajv/lib/ajv.js:353:27)
    at Ajv.compile (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/node_modules/ajv/lib/ajv.js:113:37)
    at build (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/lib/validation.js:55:27)
    at afterRouteAdded (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastify/fastify.js:513:9)
    at Object._encapsulateThreeParam (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/avvio/boot.js:348:7)
    at Boot.callWithCbOrNextTick (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/avvio/boot.js:300:5)
    at Boot._after (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/avvio/boot.js:206:26)
    at Plugin.exec (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/avvio/plugin.js:45:17)
    at Boot.loadPlugin (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/avvio/plugin.js:125:10)
    at Task.release (/home/nbalduzzi/repos/ia-dev-zemtime-back/node_modules/fastq/queue.js:127:16)
/home/nbalduzzi/repos/ia-dev-zemtime-back/src/handlers/common/error-handler.js:10
    throw Error(err)
```

**Comment by mcollina** [comment]
Thanks, the fix should be as I've described in https://github.com/fastify/fastify-swagger/issues/47#issuecomment-380051397.

**Comment by chapuletta** [comment]
@mcollina  Excelent, im gonna look the info. If i solve my issue i notice you

**Comment by chapuletta** [comment]
@mcollina i resolved my issue. Lastly i had not change any of ajv or fastify-swagger.

I dony know is the correct way for resolve the issue, but i discover that i need to have in the schema the type 'file' and the ajv dont have it in the specification, so, i only have to set the compilation schema and avoid the validation. Now i just have this:

```
schema: {
      description: 'File uploader',
      tags: ['File Manager'],
      summary: 'Upload a file to the server',
      consumes: ['multipart/form-data'],
      body: {
        type: 'object',
        properties: {
          file: {
            type: 'file'
          }
        }
      },
      response: {
        200: {
          description: 'Succesful response',
          type: 'object',
          properties: {
            path: {type: 'string'}
          }
        },
        500: {
          description: 'Error response',
          type: 'object',
          properties: {
            error: {type: 'string'},
            message: {type: 'string'},
            statusCode: {type: 'number'}
          }
        }
      }
    },
    schemaCompiler: () => {}
```

on schemaCompiler i define and void arrow function for avoid the validation. Im retry, i dont know if is the solution or the best, but works.

Do you have a better way?

Thx!

**Comment by mcollina** [comment]
You should not void `schemaCompiler`, otherwise the schema will not be validated on input.
Basically this definition is not actionable anymore.

The proper solution is in https://github.com/fastify/fastify-swagger/issues/47#issuecomment-380051397. However I have no time to implement that atm.

**Comment by chapuletta** [comment]
Yeah, i understand you but ajv dont let me create a new type, the type ‘file’.

I will be looking for an ajv way solution

**Comment by davidqqq** [comment]
@mcollina pointed to the right direction. However instead of addKeyword you @nbalduzzi should addFormat (https://github.com/epoberezkin/ajv#api-addformat):
```
  const ajv = new Ajv({
    // the fastify defaults (if needed)
    removeAdditional: true,
    useDefaults: true,
    coerceTypes: true
    // any other options
    // ...
  })
  server.setSchemaCompiler(function (schema) {
    ajv.addFormat('binary', rule)
    return ajv.compile(schema)
  })
```
I am uncertain what to go into the rule though. 
Hope this helps.

Cheers

**Comment by upnica** [comment]
I have managed to get file uploads work for my use case, its a little bit hacky.

I had a couple of issues, firstly swagger wants *type* to be *file*, but as Ajv uses that and doesn't allow custom types, there was either altering the schema post validation or altering the fastify-swagger module code to look for another property and output that as the type property.

Secondly, the multipart module didn't add the files data to the request body prior to the schema validation which caused errors about the body being expected as an object. So i created a custom content type parser to build the request body from the stream.

So far my solution seems to be working, although i have not tested it with larger files or in different scenarios.

If it helps anyone, here's my code;

`
import Ajv = require("ajv");
import Busboy = require("busboy");
import mime = require("mime");
import { isBuffer } from "util";

const ajv = new Ajv({ coerceTypes: true, removeAdditional: true, useDefaults: true });
ajv.addKeyword("isFileType", {
	compile: (schema, parent, it) => {
                // Change the schema type, as this is post validation it doesn't appear to error.
		parent.type = "file";
		delete parent.isFileType;

		return () => true;
	},
});

app.server.setSchemaCompiler((schema) => ajv.compile(schema));

app.server.addContentTypeParser("multipart/form-data", (req, done) => {
	const body = {};
	const stream = new Busboy({ headers: req.headers });

	req.on("error", (err) => {
		stream.destroy();
		done(err);
	});

	stream.on("finish", () => done(null, body));

	stream.on("file", (field, file, filename, encoding, mimetype) => {
		file.on("data", (data) => {
			if (! body[field]) {
				body[field] = [];
			}

			body[field].push(data);
		});

		file.on("end", () => {
			body[field] = Buffer.concat(body[field].map((part) => isBuffer(part) ? part : Buffer.from(part)));
		});
	});

	req.pipe(stream);
});
`

Then just added the *isFileType* property into the schema;

`
fastify.post("/upload", {
	schema: {
		body: {
			properties: {
				file: {
					isFileType: true,
					type: "object",
				},
			},
			required: [ "file" ],
			type: "object",
		},
		consumes: [ "multipart/form-data" ],
		response: {
			200: {
				properties: {
					success: {
						example: true,
						type: "boolean",
					},
				},
				type: "object",
			},
		},
	},
}, (request, reply) => {
	console.info("File", request.body.file);
	reply.code(200).send({ success: true });
});
`

**Comment by mcollina** [comment]
How can fastify-swagger better support this? I think it requires some changes in the application that are not easy to encapsulate in a module.

I think we should at least remove the need of the custom body parser. Would you like to send a PR to https://github.com/fastify/fastify-formbody so that it provides all the metadata that is needed?

**Comment by upnica** [comment]
Thanks @mcollina,

An option i was thinking was to provide a `buffer` format in the Ajv module, then fastify-swagger could look for *type: "object"* and *format: "buffer"* and use that to alter the *type* property in the swagger definition output?

I have just created a PR in fastify-formbody for the multipart content type - https://github.com/fastify/fastify-formbody/pull/35

**Comment by sarneeh** [comment]
@mcollina @Eomm Wait a second. Fastify's `schema.body` is expecting a JSON Schema, as it expects an `application/json` media type. So does `Ajv`, as it's a JSON schema validator. I think that if your route is expecting a `multipart/formdata`, you shouldn't set `schema.body`, don't you? I'd rather see an additional key in `schema`, as using the JSON-related (body, params, querystring, response) is supposed to be used by `fast-json-stringify` and `ajv`. Am I right or am I missing something?

**Comment by mcollina** [comment]
@sarneeh this is a bit beyond my familiarity with Swagger. At this point, I can't answer your question. I'm happy with whatever resolution we can converge on this issue.

**Comment by Eomm** [comment]
@sarneeh I think that adding a new key could create misunderstanding.

The content type defines "what and how" the data are written in the body of the HTTP request.
In fact, [the standard](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) talk about the "body" also with the multipart content type.

So what we do here is translating the multipart body, to the json format (that is the easiest format to read the data) and we apply the validation on it.

If we would add a new key for the multipart, we should add a key for each content-types out there and develop a validator that can manage that type of format: this could be a HUGE work.

For this reason, I think that translating the multipart to a json-body is a good compromise

**Comment by sarneeh** [comment]
@Eomm That makes total sense. Thank you for the explanation. I didn't think of the additional work it would be needed for making this all work together.

**Comment by SkeLLLa** [comment]
Here's another workaround.

First of all as it was mentioned above we should add custom `binary` format:

```js
const fastify = require('fastify')();
// ...
const ajv = new Ajv({
  // the fastify defaults (if needed)
  removeAdditional: true,
  useDefaults: true,
  coerceTypes: true,
  allErrors: true,
  nullable: true,
});
fastify.setSchemaCompiler(function(schema) {
  ajv.addFormat('binary', () => {
    // here you can do some additional checks
    return true;
  });
  return ajv.compile(schema);
});
```

Afterwards in your routes we should do some hack that will allow to pass ajv validation for string type. So we need `preValidation` hook where we'll replace what's come from user with some string, so ajv will validate it and hide original file inside non-enumerable property.
```js
fastify.post(
    '/',
    {
      preValidation: async (req) => {
        const file = {...req.body.file};
        req.body.file = '@file';
        req.body[Symbol.for('file')] = file;
      },
      schema: {
        description: `create new file`,
        tags: ['files'],
        summary: 'create file',
        consumes: ['multipart/form-data'],
        body: {
          type: 'object',
          properties: {
            file: {
              type: 'string',
              format: 'binary',
            },
          },
        },
        response: {
         '200': { description: 'ok' },
        },
      },
    },
    async (request, reply) => {
      const files = request.body[Symbol.for('file')];
      // do something with your files.
    }
  );
```

**Comment by chenchuraviteja** [comment]
still i am getting error

{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "body should be object"
}

**Comment by Eomm** [comment]
@chenchuraviteja could you open an issue with all the information needed?

**Comment by chenchuraviteja** [comment]
this is my complete schema

`schema: {
		tags: [{
			name: 'Category'
		}],
		description: 'Post category data',
		consumes: [ "multipart/form-data" ],
		body: {
			type: 'object',
			isFileType: true,
			properties: {
				name: {
					type: 'string'
				},
				thumg_url: {
					isFileType: true,
					type: 'object'
				},
				img_url: {
					isFileType: true,
					type: 'object'
				},
				status: {
					type: 'number',
					enum: [0, 1],
					default: 1
				}
			},
			required: ['name', 'thumg_url', 'img_url']
		},
		response: {
			201: {
				type: 'object',
				properties: categoryProperties
			}
		}
	},`

**Comment by chenchuraviteja** [comment]
this is my complete schema

> schema: {
		tags: [{
			name: 'Category'
		}],
		description: 'Post category data',
		consumes: [ "multipart/form-data" ],
		body: {
			type: 'object',
			isFileType: true,
			properties: {
				name: {
					type: 'string'
				},
				thumg_url: {
					isFileType: true,
					type: 'object'
				},
				img_url: {
					isFileType: true,
					type: 'object'
				},
				status: {
					type: 'number',
					enum: [0, 1],
					default: 1
				}
			},
			required: ['name', 'thumg_url', 'img_url']
		},
		response: {
			201: {
				type: 'object',
				properties: categoryProperties
			}
		}
	},

**Comment by chenchuraviteja** [comment]
this is my complete schema

schema: {
		tags: [{
			name: 'Category'
		}],
		description: 'Post category data',
		consumes: [ "multipart/form-data" ],
		body: {
			type: 'object',
			isFileType: true,
			properties: {
				name: {
					type: 'string'
				},
				thumg_url: {
					isFileType: true,
					type: 'object'
				},
				img_url: {
					isFileType: true,
					type: 'object'
				},
				status: {
					type: 'number',
					enum: [0, 1],
					default: 1
				}
			},
			required: ['name', 'thumg_url', 'img_url']
		},
		response: {
			201: {
				type: 'object',
				properties: categoryProperties
			}
		}
	},

**Comment by chenchuraviteja** [comment]
this my complete schema
`schema: {
		tags: [{
			name: 'Category'
		}],
		description: 'Post category data',
		consumes: [ "multipart/form-data" ],
		body: {
			type: 'object',
			isFileType: true,
			properties: {
				name: {
					type: 'string'
				},
				thumg_url: {
					isFileType: true,
					type: 'object'
				},
				img_url: {
					isFileType: true,
					type: 'object'
				},
				status: {
					type: 'number',
					enum: [0, 1],
					default: 1
				}
			},
			required: ['name', 'thumg_url', 'img_url']
		},
		response: {
			201: {
				type: 'object',
				properties: categoryProperties
			}
		}
	}`

**Comment by kristofferostlund** [comment]
I found another workaround based on @SkeLLLa's suggestion, where I add a small ajv plugin to fastify, which I believe might be a little bit less intrusive?

Below is a fully functioning example:

```js
const Fastify = require('fastify') // 2.11.0
const multer = require('fastify-multer') // 1.5.2
const swagger = require('fastify-swagger') // 2.5.0
const uploads = multer({ dest: '/tmp/file-uploads' })

function ajvPlugin(ajv, options) {
  ajv.addKeyword('isFileType', {
    compile: (schema, parent, it) => {
      // Change the schema type, as this is post validation it doesn't appear to error.
      parent.type = 'file'
      delete parent.isFileType
      return () => true
    },
  })

  return ajv
}

const fastify = Fastify({ logger: true, ajv: { plugins: [ajvPlugin] } })

fastify.register(multer.contentParser, { addToBody: true })
fastify.register(swagger, { exposeRoute: true })

fastify.post('/uploads', {
  schema: {
    consumes: ['multipart/form-data'],
    body: { properties: { file_1: { isFileType: true } } },
    // Shortened for the example
  },
  preHandler: uploads.single('file_1'),
  handler: async (req, reply) => req.file,
})

fastify.listen(3000)
```

**Comment by chenchuraviteja** [comment]
thanks for your reply..

**Comment by chenchuraviteja** [comment]
> Hi, when i define the schema consumer in endpoint /upload to 'multipart/form-data' for uploading file i dont know wich is the schema structure body for passing the base64 string or the file that i need to upload.
> 
> If y define the schema:
> 
> ```
> schema: {
>       description: 'Upload file',
>       tags: ['Info'],
>       consumes: [ 'multipart/form-data' ],
>       summary: 'Upload the file to the server',
>       body: {
>         type: 'object',
>         properties: {
>           file: {type: 'string'}
>         }
>       },
>       response: {
>         200: {
>           description: 'Succesful response',
>           type: 'boolean'
>         }
>       }
>     }
> ```
> 
> when i send the post get the error:
> 
> ```
> {
>   "statusCode": 400,
>   "error": "Bad Request",
>   "message": "body should be object"
> }
> ```
> 
> I fetch in the dynamic.js code looking for the solution but i dont get with it.
> 
> Can you help me?
> 
> PD: Im sorry if this is not the place for this kind of issues.
> 
> Thx

are you fix this problem?

**Comment by wolfejw86** [comment]
@kristofferostlund (or anyone else who tried it) have you noticed any side effects of doing your less intrusive technique?
at a glance it "just worked" and doesn't seem to hurt any of my other validations.

**Comment by kristofferostlund** [comment]
> i'm not familiar enough with how the ajv -> swagger doc pipeline works to know at a glance, and was curious if you got to dig in more. If not I can take a deeper look.

Neither am I really, and after getting it to work with the docs page and third party I left it at that.

I've not seen any strange side effects with my workaround yet, both the swagger client/docs page and the consumer (an android app) seems to not have any problems. However, we're not running in production yet, so I wouldn't exactly call it battle tested.

**Comment by wolfejw86** [comment]
Ha, the situation you described seems very familar 🤣 
Thanks for the update.

**Comment by SkeLLLa** [comment]
@wolfejw86 I think @kristofferostlund approach looks definitely better then mine, but I've not tested it :).

**Comment by paxvista** [comment]
For those trying use the OpenApi 3.0 schema 'format' for strings and numbers and getting an error such as:

Error: unknown format "binary|int32|int64" is used in schema at path "#"

Add the following to your fastify options:
const options = {
  ajv: {
    customOptions: {
      unknownFormats: ['binary','int32','int64']
    }
  }
}
const fastify = require('fastify')(options);

**Comment by Adityapanther** [comment]
@mcollina  is issue fixed or may I send pull req to it because I am getting same issue

**Comment by mcollina** [comment]
I don't think it's fixed. A PR would definitely be fine.

cc @Eomm @climba03003

**Comment by Adityapanther** [comment]
@mcollina ok, I will try to fix it

**Comment by climba03003** [comment]
> 
> ok, I will try to fix it

The main reason for this issue is `ajv` is a tool to validate JSON schema only. It can not handle `multipart` and `binary` natively. So, you need to customize the `ajv` instance in order to accept the custom format.

You may look into the suggestion on #343

**Comment by Adityapanther** [comment]
@climba03003  ok thanks

**Comment by chansdad** [comment]
Tried all the options , still an issue . 

> @mcollina i resolved my issue. Lastly i didn't change any of ajv or fastify-swagger.
> 
> I don't know if is the correct way for resolve the issue, but i discovered that i need to have in the schema the type 'file' and the ajv dont have it in the specification, so, i only have to set the compilation schema and avoid the validation. Now i just have this:
> 
> ```
> schema: {
>       description: 'File uploader',
>       tags: ['File Manager'],
>       summary: 'Upload a file to the server',
>       consumes: ['multipart/form-data'],
>       body: {
>         type: 'object',
>         properties: {
>           file: {
>             type: 'file'
>           }
>         }
>       },
>       response: {
>         200: {
>           description: 'Succesful response',
>           type: 'object',
>           properties: {
>             path: {type: 'string'}
>           }
>         },
>         500: {
>           description: 'Error response',
>           type: 'object',
>           properties: {
>             error: {type: 'string'},
>             message: {type: 'string'},
>             statusCode: {type: 'number'}
>           }
>         }
>       }
>     },
>     schemaCompiler: () => {}
> ```
> 
> on schemaCompiler i define and void arrow function for avoid the validation. Im retry, i dont know if is the solution or the best, but works.
> 
> Do you have a better way?
> 
> Thx!

This is the only option that worked for me . Though what is happening is when fastify server starts it is throwing error , and if in the same file if i have multiple routes , one to upload file and one to get the file , when using the get file route , fastify server crashes . so is the case even when i use file: { type: 'string', format:'binary' }, This is a serious bug that sure prevents one from makign the whole api docs complete . For now i am skipping generating doc for file upload .


When using file:{ type:'string, format:'binary'}

fastify server startup logs 
FastifyError [Error]: Failed building the validation schema for POST: /api/upload, due to error unknown format "binary" is used in schema at path "#/properties/file"

when using  file:{ type:'fle'}

FastifyError [Error]: Failed building the validation schema for POST: /api/upload, due to error schema is invalid: data.properties['file'].type should be equal to one of the allowed values, data.properties['file'].type should be array, data.properties['file'].type should match some schema in anyOf
 in both of the above cases , I see the button displayed with swagger ui .
![image](https://user-images.githubusercontent.com/3308018/201596522-d51b982c-b5d2-4fbf-8c4d-3ca7105cf7fa.png)

Able to upload the file !!!

now if i have a different route in the same file that when i call 

seeing this error 

/Users/xxx/Downloads/myproj/node_modules/fastify/lib/route.js:443
    if (err || i === functions.length) {
                               ^

TypeError: Cannot read property 'length' of undefined
....
....
..
   at Server.emit (events.js:314:20)
    at parserOnIncoming (_http_server.js:781:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
[nodemon] app crashed - waiting for file changes before starting..

**Comment by climba03003** [comment]
See the comment https://github.com/fastify/fastify-swagger/issues/47#issuecomment-902989869
And look into https://github.com/fastify/fastify-swagger/issues/343

You need to customize `ajv`.
