### ISSUE TITLE
PUT doesn't return a body even when schema is specified

### ISSUE THREAD

**Issue by yaamas** [fastify/fastify-swagger#474]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.0.0

### Plugin version

4.12.0

### Node.js version

16.9.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 11 Pro 21H2 Build 22000.168

### Description

There is no response for a PUT request with a 204 reply even when a response is sent back and the schema also needs a reply.

I have searched the issues but only found PR's/issues discussing for `type: 'null'` and making other requests status codes also work with empty body response but nothing dealing with this issue.

### Steps to Reproduce

This is my response schema: 
```js
  const getItemsOpts = {
    schema: {
      description: "xxx",
      tags: ["yyy"],
      required: ["level", "spaceid"],
      params: { ... },
      body: { ... },
      response: {
        204: {
          content: {
            "application/json": {
              type: "object",
              properties: {
                level: { type: "string" },
                spaceid: { type: "string" },
              },
              "x-consume": "application/json",
            },
          },
        },
      },
    },
    handler: someFunc
  }
```

The `content` and `x-consume` were added after reviewing the fastify-swagger webpage at the Routing section but that didn't make a difference. 

What I am returning is 

```js
reply.code(204).send({ level, spaceid });
```

Also the route
```js
fastify.put("/:level/:spaceid", getItemsOpts);
```

The response recieved is :
```js
<html>
<body>
<!--StartFragment-->

Code | Details
-- | --
204 | Response headers connection: keep-alive  content-length: 2  content-type: application/json; charset=utf-8  date: Wed,22 Sep 2021 10:14:01 GMT  keep-alive: timeout=5

<!--EndFragment-->
</body>
</html>
```

### Expected Behavior

A json object with the sent and defined properties.

**Comment by climba03003** [comment]
`204` status code do not allow to send any content even if you specified schema.

It is the correct behavior.
