### ISSUE TITLE
Dynamic DTO Schemas

### ISSUE THREAD

**Issue by kamleshkatpara** [fastify/fastify-swagger#475]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hi,

## Environment

- *node version*: 16.8.0
- *fastify version*: 3.21.3
- *os*: Widnwos

I am using fastify, i tried the following:

![Screenshot 2021-09-22 120148](https://user-images.githubusercontent.com/16983847/134293989-c169be07-1e14-4d16-8e34-a3a81354239f.png)

![Screenshot 2021-09-22 154827](https://user-images.githubusercontent.com/16983847/134326590-e1df3b33-f2b4-4e66-a304-4037545bb445.png)

![Screenshot 2021-09-22 154909](https://user-images.githubusercontent.com/16983847/134326953-a1db281d-f911-4c1e-aa03-caebf16ff75b.png)

![Screenshot 2021-09-22 154928](https://user-images.githubusercontent.com/16983847/134326996-9b952ee5-b3f6-4779-ba8f-35dabb77792b.png)

I was able to load the schemas in definitions but now paths object changed.

If I try this then I get paths but definitions are gone.

![Screenshot 2021-09-22 155624](https://user-images.githubusercontent.com/16983847/134327535-b2944a8d-0dd3-40c8-a5a3-c5e7a6c47c22.png)

![Screenshot 2021-09-22 155713](https://user-images.githubusercontent.com/16983847/134327678-89359c9a-5739-4255-9447-39b114072df3.png)

I wonder what is missing here

**Comment by zekth** [comment]
It seems your definitions are not registered in the fastify instance. In dynamic mode you don't need to put the definition in the spec itself, it resolves it from the fastify instance.

**Comment by kamleshkatpara** [comment]
@zekth, it does not resolve it from the fastify instance as I am using classes and converting them to json-schema

**Comment by zekth** [comment]
So what you want is not `dynamic` but `static` mode.

> dynamic is the default mode, if you use fastify-swagger this way API schemas will be auto-generated from route schemas:

**Comment by kamleshkatpara** [comment]
@zekth Yes dynamic schemas
