### ISSUE TITLE
Array input under multipart or upload is still single text input instead of multiple text input

### ISSUE THREAD

**Issue by rowlanddavid** [fastify/fastify-swagger#483]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.21.6

### Node.js version

14.17.4

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

Properties with array value under multipart/form-data must be multiple input text but instead swagger gave me single input text

configuration:
body: {
                    type: 'object',
                    properties: {
                        usernames: {properties: {value: {type: 'array', items: {type: 'string'}}}},
                    },
                },
                
 

### Steps to Reproduce

Under my routes configuration:

{
            config: {name: 'get.user'},
            method: 'POST',
            url: '/get-user',
            schema: {
                description: 'Get User with usernames',
                tags: ['get-user'],
                consumes: ['multipart/form-data'],
                body: {
                    type: 'object',
                    properties: {
                        usernames: {properties: {value: {type: 'array', items: {type: 'string'}}}},
                    },
                },
                security: [{'apiKey': []}],
            },
            handler: UserController(fastify).usernames,
}

under body: {
type: 'object',
                    properties: {
                        usernames: {properties: {value: {type: 'array', items: {type: 'string'}}}},
                    },
}
![Invalid Input](https://i.ibb.co/McMqLcD/Screenshot-from-2021-09-29-18-07-41.png)

is supposed to use a array input but it only shows the ordinary input text I also tried to use this configurations:
 {
type: 'object',
                    properties: {
                        usernames: {type: 'array', items: {type: 'string'}},
                    },
}
but this configuration returns me error Object is null

The expected must be array of inputs instead of single text input when not using body schema with multipart/form-data it works like on the screenshot
![Expected behavior](https://i.ibb.co/6NDLMpD/Screenshot-from-2021-09-29-18-10-03.png)

**Comment by climba03003** [comment]
Are you sure it is the correct schema?

```js
{
type: 'object',
  properties: {
    usernames: {
      properties: { value: { type: 'array', items: { type: 'string' } } }
    },
  },
}
```

**Comment by climba03003** [comment]
Simple Repro
```js
const Fastify = require("fastify").default;
const FastifySwagger = require("fastify-swagger").default;

const fastify = Fastify();
fastify.register(FastifySwagger, {
  routePrefix: "/documentation",
  exposeRoute: true,
});
fastify.route({
  method: "POST",
  url: "/",
  schema: {
    consumes: ["multipart/form-data"],
    body: {
      type: "object",
      properties: {
        usernames: {
          type: "array",
          items: { type: "string" },
        },
      },
    },
  },
  handler: async function () {
    return { foo: "bar" };
  },
});
(async function () {
  await fastify.ready();
  fastify.listen(5000);
})();
```

Behavior is as expected.
![image](https://user-images.githubusercontent.com/23028015/135255171-b295ced1-2ed1-4c76-93c8-70c33a098e47.png)

**Comment by rowlanddavid** [comment]
> Simple Repro
> 
> ```js
> const Fastify = require("fastify").default;
> const FastifySwagger = require("fastify-swagger").default;
> 
> const fastify = Fastify();
> fastify.register(FastifySwagger, {
>   routePrefix: "/documentation",
>   exposeRoute: true,
> });
> fastify.route({
>   method: "POST",
>   url: "/",
>   schema: {
>     consumes: ["multipart/form-data"],
>     body: {
>       type: "object",
>       properties: {
>         usernames: {
>           type: "array",
>           items: { type: "string" },
>         },
>       },
>     },
>   },
>   handler: async function () {
>     return { foo: "bar" };
>   },
> });
> (async function () {
>   await fastify.ready();
>   fastify.listen(5000);
> })();
> ```
> 
> Behavior is as expected. ![image](https://user-images.githubusercontent.com/23028015/135255171-b295ced1-2ed1-4c76-93c8-70c33a098e47.png)

this works without the plugin

I forgot to add the fastify-multipart plugin version 5.0.1

when submitting the form this error shows

"body.usernames should be array" or if not using array the form works without error if I use this configuration:
body: {
                    type: 'object',
                    properties: {
                        usernames: {properties: {value: {type: 'string'}}},
                    },
                },
without the array type

**Comment by climba03003** [comment]
Then, it is not the problem of `fastify-swagger`.

Please refer to `fastify-multipart` for how to set schema validation for it. And it is known that you can not match it with validation and schema for `swagger-ui`.

**Comment by rowlanddavid** [comment]
> Then, it is not the problem of `fastify-swagger`.
> 
> Please refer to `fastify-multipart` for how to set schema validation for it. And it is known that you can not match it with validation and schema for `swagger-ui`.
> 
> https://github.com/fastify/fastify-multipart#json-schema-body-validation

this configuration is not possible to fastify-swagger?

`
schemal: {
    body: {
        usernames: {properties: {value: {type: 'array'}}},
    },
}
`

**Comment by climba03003** [comment]
> 
> 
> > Then, it is not the problem of `fastify-swagger`.
> > Please refer to `fastify-multipart` for how to set schema validation for it. And it is known that you can not match it with validation and schema for `swagger-ui`.
> > https://github.com/fastify/fastify-multipart#json-schema-body-validation
> 
> this configuration is not possible to fastify-swagger?
> 
> `schema: { body: { usernames: {properties: {value: {type: 'array'}}}, }, }`
> 
> note the {value: {type: 'array'}} does not output array of input text instead single input text only

@rowlanddavid It is known that you can not match it with validation and schema for swagger-ui.
