### ISSUE TITLE
swagger + ajv-merge-patch

### ISSUE THREAD

**Issue by nlapshin** [fastify/fastify-swagger#484]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.0

### Plugin version

4.12.3

### Node.js version

16.10

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20

### Description

I found out some problem with ajv-patch-merge plugin and fastify-swagger.

I tried to use example from documentation https://www.fastify.io/docs/latest/Validation-and-Serialization/#ajv-plugins and as a result I got the following result.

I decided to create this issue, because I thought the example from the documentation should work fit and maybe I did something wrong.

ajv-merge-patch - 4.1.0 version

if this case looks like a bug, I can try make PR.

Thanks guys for your work!
![Selection_319](https://user-images.githubusercontent.com/39495311/135758572-5fdabab2-c20d-4afe-9ff3-98fc3fe5a8c1.png)

### Steps to Reproduce

```
const fastify = require('fastify')({
  ajv: {
    plugins: [
      require('ajv-merge-patch')
    ]
  }
})

fastify.register(require('fastify-swagger'), {
  routePrefix: '/documentation',
  swagger: {
    info: {
      title: 'Test swagger',
      description: 'Testing the Fastify swagger API',
      version: '0.1.0'
    },
    externalDocs: {
      url: 'https://swagger.io',
      description: 'Find more info here'
    },
    host: 'localhost',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
      { name: 'user', description: 'User related end-points' },
      { name: 'code', description: 'Code related end-points' }
    ],
    definitions: {
      User: {
        type: 'object',
        required: ['id', 'email'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: {type: 'string', format: 'email' }
        }
      }
    },
    securityDefinitions: {
      apiKey: {
        type: 'apiKey',
        name: 'apiKey',
        in: 'header'
      }
    }
  },
  uiConfig: {
    docExpansion: 'full',
    deepLinking: false
  },
  uiHooks: {
    onRequest: function (request, reply, next) { next() },
    preHandler: function (request, reply, next) { next() }
  },
  staticCSP: true,
  transformStaticCSP: (header) => header,
  exposeRoute: true
})

fastify.post('/', {
  handler (req, reply) { reply.send({ ok: 1 }) },
  schema: {
    body: {
      $patch: {
        source: {
          type: 'object',
          properties: {
            q: {
              type: 'string'
            }
          }
        },
        with: [
          {
            op: 'add',
            path: '/properties/q',
            value: { type: 'number' }
          }
        ]
      }
    }
  }
})

fastify.post('/foo', {
  handler (req, reply) { reply.send({ ok: 1 }) },
  schema: {
    body: {
      $merge: {
        source: {
          type: 'object',
          properties: {
            q: {
              type: 'string'
            }
          }
        },
        with: {
          required: ['q']
        }
      }
    }
  }
})

fastify.ready(err => {
  if (err) throw err
  fastify.swagger()
})

fastify.listen(3000)
```

**Comment by climba03003** [comment]
`$patch` and `$merge` is not a valid Swagger or OpenAPI syntax.

You should use [`transform`](https://github.com/fastify/fastify-swagger#transforms) to change the schema back to a standard one.

**Comment by nlapshin** [comment]
Ok. Thanks a lot for the answer. I explored this problem in more detail and found a solution that suits me well. I close issue.

**Comment by honzapatCZ** [comment]
Hello
@nlapshin could you share your solution for other people getting to this issue?

Thanks

**Comment by nlapshin** [comment]
> Hello @nlapshin could you share your solution for other people getting to this issue?
> 
> Thanks

My solution is pretty simple. I added to fastify method 'mergeSchema', which merge one schema to another 

```
fastify.decorate('mergeSchema', function({ source, with: target }) {
    source = source.$ref ? fastify.getSchema(source.$ref.replace('#', '')) : source

    if (!target.$id) {
      target.$id = generateId(source, counter)
    }

    return merge(source, target)
  })
}
```

**Comment by honzapatCZ** [comment]
> > Hello @nlapshin could you share your solution for other people getting to this issue?
> > Thanks
> 
> My solution is pretty simple. I added to fastify method 'mergeSchema', which merge one schema to another
> 
> ```
> fastify.decorate('mergeSchema', function({ source, with: target }) {
>     source = source.$ref ? fastify.getSchema(source.$ref.replace('#', '')) : source
> 
>     if (!target.$id) {
>       target.$id = generateId(source, counter)
>     }
> 
>     return merge(source, target)
>   })
> }
> ```

how do you make it work with the schemas? Or are you invoking the method inside of the schemas directly?

**Comment by nlapshin** [comment]
I merge two schemas and the result schema inject to endpoint. For example:

```
const me = {
    tags: ['auth'],
    headers: { $ref: 'headers.auth#' },
    response: {
      200: fastify.mergeSchema({
        source: { $ref: 'response.success#' },
        with: {
          properties: {
            data: {
              type: 'object',
              required: ['username', 'email', 'role'],
              properties: {
                username: { type: 'string' },
                email: { type: 'string' },
                role: { type: 'integer' }
              },
              additionalProperties: false
            }
          },
          example: {
            data: {
              username: 'username',
              email: 'email',
              role: 1
            }
          }
        }
      }),
      400: fastify.mergeSchema({
        source: { $ref: 'response.error.400#' },
        with: {
          properties: {
            errors: {
              items: { type: 'string', enum: [errors.USER_NOT_FOUND] }
            }
          },
          example: {
            errors: [errors.USER_NOT_FOUND]
          }
        }
      }),
      401: { $ref: 'response.error.401#' },
      500: { $ref: 'response.error#' }
    }
  }
```
