### ISSUE TITLE
Cannot use CSP Config when using import syntax

### ISSUE THREAD

**Issue by laurenzhonauer** [fastify/fastify-swagger#485]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.11.0

### Plugin version

4.12.4

### Node.js version

12-slim

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu-20.4

### Description

I tried to implement the CSP config that is described in the Readme while using typescript. (See code snipped in steps to reproduce)

While the code in that readme works for me, I would like to import fastify-helmet using the *import* syntax instead of *require* for the sake of consistency  in my typescript file. 

To my knowledge following two things should compile to the same javascript code:
`import * as helmet from "fastify-helmet"`
`const helmet = require("fastify-helmet");`

But when I use the import syntax i get following error in compilation:

``` 
No overload matches this call.
  Overload 1 of 3, '(plugin: FastifyPluginCallback<FastifyPluginOptions, Server>, opts?: FastifyRegisterOptions<FastifyPluginOptions> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof import("/home/laurenz/workspace/TruBudget/api/node_modules/fastify-helmet/index")' is not assignable to parameter of type 'FastifyPluginCallback<FastifyPluginOptions, Server>'.
      Type 'typeof import("/home/laurenz/workspace/TruBudget/api/node_modules/fastify-helmet/index")' provides no match for the signature '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>, opts: FastifyPluginOptions, done: (err?: Error | undefined) => void): void'.
  Overload 2 of 3, '(plugin: FastifyPluginAsync<FastifyPluginOptions, Server>, opts?: FastifyRegisterOptions<FastifyPluginOptions> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof import("/home/laurenz/workspace/TruBudget/api/node_modules/fastify-helmet/index")' is not assignable to parameter of type 'FastifyPluginAsync<FastifyPluginOptions, Server>'.
      Type 'typeof import("/home/laurenz/workspace/TruBudget/api/node_modules/fastify-helmet/index")' provides no match for the signature '(instance: FastifyInstance<Server, IncomingMessage, ServerResponse, FastifyLoggerInstance>, opts: FastifyPluginOptions): Promise<...>'.
  Overload 3 of 3, '(plugin: FastifyPluginCallback<FastifyPluginOptions, Server> | FastifyPluginAsync<FastifyPluginOptions, Server> | Promise<...> | Promise<...>, opts?: FastifyRegisterOptions<...> | undefined): FastifyInstance<...> & PromiseLike<...>', gave the following error.
    Argument of type 'typeof import("/home/laurenz/workspace/TruBudget/api/node_modules/fastify-helmet/index")' is not assignable to parameter of type 'FastifyPluginCallback<FastifyPluginOptions, Server> | FastifyPluginAsync<FastifyPluginOptions, Server> | Promise<...> | Promise<...>'.
      Type 'typeof import("/home/laurenz/workspace/TruBudget/api/node_modules/fastify-helmet/index")' is missing the following properties from type 'Promise<{ default: FastifyPluginAsync<FastifyPluginOptions, Server>; }>': then, catch, finally, [Symbol.toStringTag]ts(2769)
``` 

It could be possible that I just have to import helmet in a different way, but I wasnt able to find out.
Also maybe this actually belongs to fastify-helmet instead, in that case, apologies for the spam here 😄 

### Steps to Reproduce

Given that i have following registration in place (with typescript!)

```typescript
server.register(helmet, (instance) => {
    console.log(instance.swaggerCSP);
    return {
      contentSecurityPolicy: {
        directives: {
          defaultSrc: ["'self'"],
          imgSrc: ["'self'", "data:", "validator.swagger.io"],
          scriptSrc: ["'self'"].concat(instance.swaggerCSP.script),
          styleSrc: ["'self'", "https:"].concat(instance.swaggerCSP.style),
        },
      },
    };
  });
```

When I import helmet like this it works
`const helmet = require("fastify-helmet");`

when I import helmet like this I get the error mentioned in the description
`import * as helmet from "fastify-helmet"`

### Expected Behavior

Expected (or wanted) Behaviour is that I can implement the csp config without using the require syntax and only using import

**Comment by climba03003** [comment]
`const helmet = require("fastify-helmet");` and `import * as helmet from "fastify-helmet"` is totally different things in TypeScript.

You should use `default import`, `named import` or `require`.

**Comment by laurenzhonauer** [comment]
True, sorry for the mistake.

Next try:
I would expect this to give me the default export
```typescript 
import helmet from "fastify-helmet"
```

But I still get the error like this

**Comment by climba03003** [comment]
It maybe related to your TypeScript config.
It is suggested to turn on `esModuleInterop` for the TypeScript config.

**Comment by climba03003** [comment]
Can you provide a minimal repo for the issue. Maybe I can debug the configuration when I have time.

This error is mostly due to, missing import of `fastify-swagger`, import it in some file but never use that file or miss configuration of TypeScript.

**Comment by climba03003** [comment]
Close it for now. Feel free to reopen it with a minimal repo.

**Comment by laurenzhonauer** [comment]
Thanks for offering to look into this. I created a minimal repo [here](https://github.com/laurenzhonauer/fastify-typescript).

For my actual project I just went ahead and used require since the whole issue is not *that* important. But feel free to look at my repo if you have the time 😄

**Comment by climba03003** [comment]
I see the problem. Thanks for the repo.
