### ISSUE TITLE
Update openapi-types to 9.3.0 to supporto OAS 3.1

### ISSUE THREAD

**Issue by silversoul93** [fastify/fastify-swagger#499]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be nice to add the support to the openapi specification 3.1.
I quickly checked that the `openapi-types` dependency supports it from version 9.3.0 (actually the last version).

It's a minor release, so without breaking change (hopefully xD).

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by climba03003** [comment]
We do not fix the dependency version. Reinstall your dependency and it will fetch the latest.
