### ISSUE TITLE
Proposal - Enrich swagger based on JSON schema or Joi

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-swagger#5]
As titled, this could be very useful.

**Comment by mcollina** [comment]
What do you mean by enrich? This should already be generating the swagger based on JSON Schema.

**Comment by StarpTech** [comment]
Oh didn't know that, I thought the user has to define the swagger definition twice.

**Comment by delvedor** [comment]
Nope, the swagger is created with the schema of your routes :)
