### ISSUE TITLE
Add missing property refResolver to types file (index.d.ts)

### ISSUE THREAD

**Issue by pharindoko** [fastify/fastify-swagger#501]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I use typebox and fastify swagger in combination

One thing that I`m not happy with is the def-# stuff in the schema name.
I use fastify.addSchema function to add the type...

![image](https://user-images.githubusercontent.com/5619511/141019081-9827d7fa-f1e7-49b1-8ed1-0cc43dfab739.png)

<img width="616" alt="image" src="https://user-images.githubusercontent.com/5619511/141018547-1c64f262-f4ae-415d-a5f6-6097cebe31ae.png">

What I would like to have:
Be able to set a specific name for the schema e.g. in this case components/schema/UserObject

### Motivation

I would like to generate my types for the frontend from the openapi spec.
But Def-0 as type is not helpful...
![image](https://user-images.githubusercontent.com/5619511/141018973-b311ec82-d962-4626-9b18-fc971a77e7b4.png)

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by pharindoko** [comment]
Hey @mcollina,

hmm haven`t seen this.
Guess that fixes my problem...
https://github.com/fastify/fastify-swagger/blob/1a68013d9a3f02034b48b87a4902040f113a0cfa/README.md#managing-your-refs

Need to try...

**Comment by pharindoko** [comment]
seems like the refResolver is missing in the typescript index.d.ts file at this place:
https://github.com/fastify/fastify-swagger/blob/dc8e29acc488e22f6fdebcfdc64f5d61e3863a63/index.d.ts#L118

**Comment by pharindoko** [comment]
ok adding this to index.d.ts file in line 119 immediately fixed the problem but it would be nice use a better type than Object ...
```typescript
  refResolver?: Object; 
```

**Comment by pharindoko** [comment]
Created a repo where I fixed this issue with an interface extension...
https://github.com/pharindoko/fastify-prisma-ts/blob/8f43f86b12019ce8f0754cf491f121339d564e5b/index.ts#L14

@mcollina can you add the missing typing for the refResolver dependency ?

**Comment by Eomm** [comment]
This is the `refResolver` API: https://github.com/Eomm/json-schema-resolver#usage-resolve-one-schema-against-external-schemas

Would you mind adding it?

**Comment by samzilverberg** [comment]
added the missing type in https://github.com/fastify/fastify-swagger/pull/561
