### ISSUE TITLE
Fastify ( + TypeScript )  shema in routes returns error for parameters: description/tags/etc...

### ISSUE THREAD

**Issue by Lev-Shapiro** [fastify/fastify-swagger#517]
### Prerequisites

- [X] I have written a descriptive issue title
- [ ] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.2

### Plugin version

3.0.0

### Node.js version

14.16.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6

### Description

I am using Fastify, TypeScript, and Swagger together. When I write route with a shema:
     fastify.get(directory, {
          shema: {...}
     }, 
        (req, res) => {}) 

I get errors for description, tags, summary, etc... parameters

Error: Type '{ description: string; tags: string[]; summary: string; }' is not assignable to type 'FastifySchema'.
  Object literal may only specify known properties, and 'description' does not exist in type 'FastifySchema'.

### Steps to Reproduce

import { fastify } from "../app";    

fastify.post<POST>(directory, {
        schema: {
            description: 'get some data', // error here.
            tags: ['models'],
            summary: 'qwerty',
        }
    }, (req, res) => {})

**Comment by mcollina** [comment]
Can you please include a complete way to reproduce your problem, ideally in a fresh github project.

**Comment by Lev-Shapiro** [comment]
I solved my problem by adding:
    description?: string;
    tags?: string[];
    summary?: string;
    security?: any[];

to the FastifySchema at nodemoules/fastify/types/schema.d.ts

**Comment by Lev-Shapiro** [comment]
Actually looking at https://github.com/panbhatt/fastify-swagger/blob/b9ac4179c9853097820d5dcbeedb91c802847a49/index.d.ts helped me a lot.

**Comment by SomethingSexy** [comment]
@Lev-Shapiro  what did you end up doing to solve this? I am seeing the same problem.
