### ISSUE TITLE
Custom Property Replacement

### ISSUE THREAD

**Issue by PhilipWee** [fastify/fastify-swagger#518]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Sorry if this is already supported, I could not find it in the documentation

Basically users may want to specify additional swagger properties, but these additional properties may not be supported by AJV which results on errors on that end

### Motivation

Basically `type='file'` is supported by swagger and not ajv which results in a whole world a problems for multipart/form-data since ajv is more of a json validation thing

### Example

Maybe something like
```
schema: {
    consumes: ['multipart/form-data'],
    body: {
      type: "object",
      properties: {
        myFile: {
          type: "string",
          isFileType: true,
          customSwaggerProps: {
            type: "file"
          }
        }
      }
    }
  }
```

Possible implementation:

```ts
In openapi options

transform: (schema: any) => {
    // Recursively search for custom properties and add them in
    const result = recursiveCustomPropertyReplacement(schema)
    return result
  }

The function itself

function recursiveCustomPropertyReplacement(schema: any): any {
  if (typeof schema === 'object') {

    if (schema.customSwaggerProps !== undefined) {
      // Update with the custom swagger props, if any
      schema = merge(schema, schema.customSwaggerProps)
      delete schema.customSwaggerProps
    }
    // Recursively replace properties on children if required
    const fullyReplaced = Object.fromEntries(
      Object.entries(schema).map(([key, value]) => {
        // A reliable way of ensuring it is an object (May not be performant but only used in openapi)
        if (Object.prototype.toString.call(value) === '[object Object]') {
          return [key, recursiveCustomPropertyReplacement(value)]
        }

        return [key, value]
      })
    )
    return fullyReplaced
  } else {
    // No further children, return 
    return schema
  }
}
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by PhilipWee** [comment]
I don't mind, as long as you guys are okay with the implementation and its not already existing
