### ISSUE TITLE
using `const` keyword produce invalid swagger file

### ISSUE THREAD

**Issue by mikicho** [fastify/fastify-swagger#521]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.0

### Plugin version

4.13.0

### Node.js version

16.13.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

10.15.7 (19H2)

### Description

The swagger plugin produces an invalid swagger file when using the json-schema `const` keyword ([spec](http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.1.3))

### Steps to Reproduce

```
const requestBodySchema = {
  type: 'object',
  required: ['prop'],
  properties: {
    prop: { const: 'my-const' },
  },
}

export default async (fastify) => {
  fastifty.route({
  method: 'POST',
  url: '/',
  schema: {
    body: requestBodySchema,
  },
  handler,
});
};
```
produce:
```
...
schema:
  type: object
  required:
    - prop
  properties:
    prop:
      const: my-const
...
```
Swagger validator error message:
```
Structural error at paths./v1/users/.post.requestBody.content.application/json.schema.properties.prop
should NOT have additional properties
additionalProperty: const
```

### Expected Behavior

The swagger plugin will generate a valid swagger file, for example, enum with a single value when using json-schema `const` keyword

**Comment by Eomm** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mikicho** [comment]
@Eomm Do you think converting the const into an enum with a single value is a valid solution?

**Comment by Eomm** [comment]
I think it is a good workaround.
