### ISSUE TITLE
Routes not parsed (No operations defined) in static mode

### ISSUE THREAD

**Issue by makks129** [fastify/fastify-swagger#530]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.25.3

### Plugin version

4.13.1

### Node.js version

16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.2

### Description

In our project we are using `typescript-json-schema` to generate a static schemas json file.
Hence I need to use `fastify-swagger` in static mode.
However in this case routes that I declare don't get parsed and I get a "No operations defined in spec!" message.
Is this a bug or it's still possible for routes to be parsed in static mode?

### Steps to Reproduce

Fastify setup
```ts
export default fastify()
	.register(swagger, {
		mode: 'static',
		specification: {
			path: 'schemas.generated.json',
			baseDir: '',
			postProcessor: function (swaggerObject) {
				return { ...swaggerObject, swagger: "2.0" };
			},
		},
		exposeRoute: true
	.addSchema(require('../schemas.generated.json'))
	.register(routes)
	.get('/some-route', {
		schema: {
			description: 'Get some data',
			tags: ['code'],
			summary: 'foo',
		}
	}, (_req, reply) => { reply.send({ hello: `Hello` }) })
```

To generate `schemas.generated.json`:
1. Add some stub schemas to `./src/schemas`:
```
export type TestQuerystring = {
	company_id: string;
};

export type TestResponse = string;
```
2. Generate schemas json
```
npm install typescript-json-schema
typescript-json-schema --strictNullChecks=true --excludePrivate=true --required=true --id=schemas './src/schemas/**.ts' '*' > schemas.generated.json
```

### Expected Behavior

Both routes declared in `routes` and a `get` route declared in this example get parsed and added into the swagger documentation.

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by climba03003** [comment]
`static` is used for serving the existing document. It will not parse or merge any configuration on route.
So, it is `static` mode.

**Comment by makks129** [comment]
Thank you @climba03003, after some fiddling I found a way for this to work. Although the `/documentation/schemas` route seems a bit hacky.
Just want to post a solution for history:

```ts
import swagger from 'fastify-swagger';
import fp from 'fastify-plugin';

const SWAGGER_ROUTE_PREFIX = '/documentation';

async function swaggerPlugin(fastify): Promise<void> {
	fastify.register(swagger, {
		mode: 'dynamic',
		routePrefix: SWAGGER_ROUTE_PREFIX,
		swagger: {
			definitions: getGeneratedSchemas().definitions,
			info: {
				title: 'signup',
				description: 'API documentation',
				version: getAppVersion(),
			},
			schemes: ['http'],
			consumes: ['application/json'],
			produces: ['application/json'],
		},
		hideUntagged: true,
		exposeRoute: true,
	});

	fastify.get(`${SWAGGER_ROUTE_PREFIX}/schemas`, {}, async () => getGeneratedSchemas());

	fastify.addHook('onReady', async () => {
		fastify.swagger();
	});
}

const getGeneratedSchemas = () => require('../../schemas.generated.json');
const getAppVersion = () => require('../../package.json').version;

export default fp(swaggerPlugin, {
	name: 'swagger',
});

```
