### ISSUE TITLE
How to make POST body required

### ISSUE THREAD

**Issue by j-gibweb** [fastify/fastify-swagger#539]
I'm trying to figure out how to make my POST route's `body` required.

I found this relevant Giters post -> https://giters.com/fastify/fluent-json-schema/issues/132

```
const postSomethingSchema = S.object()
  .prop("fieldA", S.string())

export const postSchema = {
  operationId: "createSomething",
  body: postSomethingSchema,
  response: { 200: somethingSchema },
};
```

Today, this generates the following, (without the `required` key I'm looking for of course)

```
"post": {
  "operationId": "createSomething",
    "requestBody": {
      "required": true, // I can't figure out how to get this!
      "content": {...}
```

## Your Environment

- *node version*: 12.14.1
- *fastify version*: 3.22.1
- "fastify-swagger": 4.12.6
- *os*: Mac

**Comment by Adibla** [comment]
I tried to update this behavior in https://github.com/fastify/fastify-swagger/pull/541 . For you it can be sufficient in order to resolve the issue?

**Comment by mcollina** [comment]
Should be, thanks!

**Comment by j-gibweb** [comment]
Sorry for the horribly slow reply on my end - @Adibla I couldn't tell you why, but your PR does not appear to solve this issue.
I'll take a crack at fixing it in the lib + a PR -- in the meantime incase you're curious, my hack fix is something like this.

```
  app.get("/swagger", async (_request, reply) => {
    reply.type("application/json").code(200);

    const out: any = app.swagger();
    Object.values(out.paths).forEach((paths: any) => {
      if (paths.post?.requestBody) {
        paths.post.requestBody.required = true;
      }
    });

    return out;
  });
```

**Comment by Eomm** [comment]
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by MatteoFe** [comment]
same problem here, still doesn't seems to be fixed in v.4.17.0 yet

I see that #541 tests GET, not POST.

**Comment by MatteoFe** [comment]
same problem here, still doesn't seems to be fixed in v.4.17.0 yet

I see that #541 tests GET, not POST.

I tried the @Eomm example above, the  '/hello' with  { "filter": "aaa"} in body, doesn't work
