### ISSUE TITLE
[Suggestion] Change swagger url

### ISSUE THREAD

**Issue by doron2402** [fastify/fastify-swagger#54]
Hi,

Are you guys open for a PR that will customize the url so let's say I want to change the url from `documentation` to `docs`?

Let me know what you guys think.

Cheers.

**Comment by mcollina** [comment]
I think having it as an option would be ok.

**Comment by jumper85** [comment]
Maybe I just don't understand the question correctly, but isn't that already possible by using routePrefix?

**Comment by doron2402** [comment]
yeah I've added it on a different pr.

we can close this issue/ suggestion
