### ISSUE TITLE
Required body with optional properties

### ISSUE THREAD

**Issue by hpohlmeyer** [fastify/fastify-swagger#545]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would like to have a way to mark a request bodies as required, even if the body only has optional properties.

### Motivation

This is a follow-up to #541. While this solves part of my problem, it still does not reflect the defined schema.
The following example illustrates the problem (it uses [typebox](https://github.com/sinclairzx81/typebox) for schema generation):

```ts
// user.types.ts

export const updateUserBody = Type.Object({
  firstName: Type.Optional(Type.String()),
  lastName: Type.Optional(Type.String()),
})

export type UpdateUserRoute = {
  Body: Static<typeof updateUserBody>;
};
```

```ts
// user.routes.ts

export default (fastify) => {
  fastify.put<UpdateUserRoute>(
    "/user",
    { schema: { body: updateUserBody } },
    (request) => console.log(request.body.firstName)
  )
}
```
Because no property inside the body is required, `fastify-swagger` will not mark the request body as required.
In theory this would allow me to send a fetch request with an empty body:

```ts
const response = await fetch("http://localhost:300/user", {
  method: "put",
  headers: { "Content-Type": "application/json" },
};

console.log(await response.json()) // => [400] Body cannot be empty when content-type is set to 'application/json'
```

… but fastify always prevents this, because it is not valid JSON. You could argue, that this is not a problem, because you would never do something like this, but if you generate your frontend client with something like [`oazapfts`](https://github.com/cellular/oazapfts), you will end up with a signature that has an optional body. And not sending a body will always result in a failed request.

### Example

See above

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mcollina** [comment]
What is preventing you to mark the body as required?
