### ISSUE TITLE
build fastify-swagger scheme for multiple response data with a single 200 code

### ISSUE THREAD

**Issue by Hydrock** [fastify/fastify-swagger#546]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello. I asked a question on stekoverflow, but I didn't find any answers. Sorry that I have to create an issue.

https://stackoverflow.com/questions/71093944/build-fastify-swagger-scheme-for-multiple-response-data-with-a-single-200-code

I use **fastify-swagger** (https://github.com/fastify/fastify-swagger) for my **fastify** server. I also use the **JSEND** (https://github.com/omniti-labs/jsend) standard, which means that the data returned may be different with the same response code 200.

I do not understand how I can **build a scheme for multiple response data with a single 200 code**.

The Open Api 3 specification (which fastify-swagger supports) seems to allow you to describe this (https://swagger.io/specification /)

[![enter image description here][1]][1]

I tried this, but it doesn't work. The response from the server is simply not validated and comes as is.

```
const chema_1 = {
  description: 'description',
  type: 'object',
  properties: {
    status: {
      type: 'string',
      description: 'string'
    },
  }
}

const chema_2 = {
  description: 'description',
  type: 'object',
  properties: {
    body: {
      type: 'string',
      description: 'number'
    },
  }
}

fastify.route({
    method: 'GET',
    url: '/coursesList',
    schema: {
        response: {
        '200': {
            oneOf: [
            chema_1,
            chema_2,
            ]
        }
        }
    },
    handler: async (request, reply) => {
        // handler
    }
})
```

I also tried this. Same behavior:
```
const chema_1 = {
  response: {
    '200': {
      description: 'description',
      type: 'object',
      properties: {
        status: {
          type: 'string',
          description: 'string'
        },
      }
    }
  }
}

const chema_2 = {
  response: {
    '200': {
      description: 'description',
      type: 'object',
      properties: {
        body: {
          type: 'string',
          description: 'number'
        },
      }
    }
  }
}

fastify.route({
    method: 'GET',
    url: '/coursesList',
    schema: {
        oneOf: [
            chema_1,
            chema_2,
        ]
    },
    handler: async (request, reply) => {
        // handler
    }
})
```

There are no such examples in the documentation. Maybe someone can help me?

  [1]: https://i.stack.imgur.com/iHSpu.png

**Comment by ZhengYuTay** [comment]
Was using fastify-swagger and also faced this issue where an endpoint just might return two different type of schema
