### ISSUE TITLE
enhance url transformation and hiding options

### ISSUE THREAD

**Issue by samzilverberg** [fastify/fastify-swagger#555]
Hi there, I added a feature proposal according to your template.
If you think it'd be useful (with or without some changes), let me know and I can try and work on a PR for this.

### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

currently, the plugin supports hiding routes (line 38) and removing base path if it's part of the server path, before adding the route to the `paths` area of the spec.

https://github.com/fastify/fastify-swagger/blob/146bfb112322492b63b0927bd953ad8cde704241/lib/spec/openapi/index.js#L38-L42

I'd really like to be able to transform the url a little more, and another nice to have would be being able to hide routes based on same custom condition (predicate on the url).

### Motivation

the usecase that I'd like to support is when fastify is behing a reverse proxy and the defined routes are not the final urls that should appear in the api spec (for users that use the api through the reverse proxy).

example fastify defined routes and the wanted transformation:

- `get /public/blabla` : should be `get /api/blabla`
- `get /private/blabla` : should not be in spec
- `get /health`: should not be in spec

It'd be nice to be able to
- transform the prefix `/public` to `/api` (or more general trasnformation fn).
- hide urls with prefix `/private`, or hide anything that's not '/public', and not need to worry about tagging or using the hide flag.

### Example

example usage could be:

```
fastify.register(require('fastify-swagger'), {
  swagger: { ... },
  ...
  hideRouteFn: url => {
    return url.startsWith('/private')
  },  
  transformUrl: url => {
   return url.replace(/^(/public)/,"/api");
  }
```

**Comment by zekth** [comment]
That's a good use case an approach. I'm +1 on this. Could you write a PR for this?

The use case you're describing with the reverse proxy is an interesting approach. Is this correct?
```
get /public/blabla : should be get /api/blabla (in prod)
get /private/blabla : should not be in spec (in prod)
get /health: should not be in spec (in prod)
```

**Comment by samzilverberg** [comment]
yes i'll try to find time in the next couple of days to do this.
From the code I've seen so far I don't think it'd be too complicated to add this.
we can talk about option naming and other fixes in the PR 

The use case I'm having is not env specific.
our apps are behind a k8s ingress controller (an nginx reverse proxy under the hood), and only routes that start with a specific prefix are "public" to the world. 
the rest are internal routes.

we'd like to generate the openapi spec just for  the "public" part, programatically of courrse, manually (or writing post process scripts) would be annoying

**Comment by zekth** [comment]
> The use case I'm having is not env specific.
our apps are behind a k8s ingress controller (an nginx reverse proxy under the hood), and only routes that start with a specific prefix are "public" to the world.
the rest are internal routes.

By env i mean either environment or deployment. I was not specifically asking to rely in an env variable or anything. We should just expose a function with the route as parameter.

**Comment by samzilverberg** [comment]
I created 2 PRs, one for each option

- [hide route via function](https://github.com/fastify/fastify-swagger/pull/559)
- [transform route url via function](https://github.com/fastify/fastify-swagger/pull/560)
