### ISSUE TITLE
Blank page when backend deployed on Nginx reverse proxy

### ISSUE THREAD

**Issue by samuel-videau** [fastify/fastify-swagger#556]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

4.15.0

### Node.js version

14.15.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Hi!

We're currently facing a problem while deploying our backend using fastify-swagger. Indeed, the swagger page is working perfectly when the server is served locally. However, when it is deployed using Nginx reverse proxy, all the backend works properly, except the swagger page, which actually loads the route and the title, but keep blank and give the following set of errors: 
![image](https://user-images.githubusercontent.com/70749906/156320813-66da7388-38bb-4951-b74f-e1af77c0a535.png)
 
Do you guys have any idea where the problem can come from?

Thanks in advance!

### Steps to Reproduce

- Create any fastify app 
- Add fastify-swagger and configure it
- Serve locally (should display locally)
- Serve the backend on a VPS using PM2 and Nginx

### Expected Behavior

We expect to have a working swagger page.

**Comment by mcollina** [comment]
Is adding fastify-swagger making your application non-accesible?

**Comment by samuel-videau** [comment]
@mcollina  No, everything is working except the swagger page which stay blank

**Comment by climba03003** [comment]
Your CORS setting is not correct and may not be proxy to the client.

**Comment by climba03003** [comment]
I am closing this issue as it mostly due to mis-configure of CORS or nginx.
By default, the CORS in favor of an secure connection. You may need to alter CORS to support `http` or nginx to support `https`.
