### ISSUE TITLE
Unable to get static openapi example working

### ISSUE THREAD

**Issue by dvstans** [fastify/fastify-swagger#557]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I've transplanted the existing static mode example code and API spec into my own project and while I get no errors on start-up, it does not serve the swagger UI (at default /documentation path, or custom path). On the other hand, the dynamic example works fine. How can I verify that the existing static example works in the main fastify-swagger branch? Do I simply run the static-file.js? Is there any additional setup required? Is there a way to turn on additional logging so I can see what might be going wrong?

Thanks!

**Comment by darkgl0w** [comment]
Can you provide a minimal reproducible example ?
After testing it, the documentation example works as it should on my side.

**Comment by dvstans** [comment]
When I try running your example I get the error "Cannot find module './static/csp.json'". Does this example require a specific branch of the fastify-swagger code, some configuration, or being run from a specific directory?

Thanks

**Comment by dvstans** [comment]
I tried with the 4.17.0 fastify-swagger release as well and get the same error. Perhaps I'm misunderstanding what the "static" option is supposed to do. I need to serve a swagger UI generated from an OpenAPI specification; however, I do not want to serve any additional custom web content (this should be dynamically generated). I get the impression that the static mode expects HTML content to already exist?

**Comment by darkgl0w** [comment]
@dvstans I need a minimal reproducible example to answer your question. Setup a github repo starting from the example I linked, make the same modifications that you intend to run on your application (without leaking any sensible info) and share a link to the github repo you just setup.

For now IMO I can only guess that your are misusing the package.

__NB__: The static mode takes a `yaml` or `json` file containing your already generated openapi/swagger specs and it serves a swagger UI that exposes it.

**Comment by dvstans** [comment]
Hi, I'm no longer using any custom code - I'm simply trying to run the static example in the fastify-swagger repo. When I clone the repo, there is no 'static' directory, but when the static example is run, it seems to expect it to exist. It is very possible I'm running the example wrong - would mind clarifying how to run it? Sorry for all the trouble.

Thanks

**Comment by dvstans** [comment]
Thank you, this works. I had been trying without the "npm i" - I had just manually installed fastify. I usually see package missing errors when dependencies are missing. Sorry for the confusion.

**Comment by darkgl0w** [comment]
No problem it allowed me to spot and fix a little issue with some examples. ^^
Can I close the issue ? Have you figured how to use this functionality ?

**Comment by dvstans** [comment]
Yes, thanks - you can close this issue. I'm not sure why my initial app didn't work - it seemes only superficially different from the example, but I've commented out some other code that may have be interfering with swagger somehow.

**Comment by darkgl0w** [comment]
Ok feel free to reopen this issue if needed, but without an actual example of your running code our help will be kind of limited ^^
