### ISSUE TITLE
schema - Improper schema format being enforced / generated

### ISSUE THREAD

**Issue by roboncode** [fastify/fastify-swagger#573]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Node.js version

14.17.6

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.2.1

### Description

Fastify schema does not allow $ref property directly within schema property. This results in fastify-swagger generating incorrect results -> schema.schema.$ref instead of schema.$ref. Because of this problem, openapi client generators cannot recognize the return value resulting in untyped responses rather than returning the appropriate schema type.

### Steps to Reproduce

**users.ts**
```
schema: {
  response: {
    200: {
      type: 'object',
      description: "Successful operation",
      schema: { // this should not be required or if it is, then fastify-swagger needs to not include it in output
        $ref: '#/components/schemas/User',
      }
    }
  },
},
```
**openapi.json** - incorrect - _schema.schema.$ref_
```
"responses": {
  "default": {
    "description": "Successful operation",
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "description": "Successful operation",
          "schema": { // this is the bug, $ref should be a sibling to description
            "$ref": "#/components/schemas/Users"
          }
        }
      }
    }
  }
}
```

### Expected Behavior

**openapi.json** - should be _schema.$ref_
```
"responses": {
  "default": {
    "description": "Successful operation",
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "description": "Successful operation",
          "$ref": "#/components/schemas/Users"
        }
      }
    }
  }
}
```

**Comment by climba03003** [comment]
Not sure where is the problem. The extra `schema.schema` is not required.

```js
const fastify = require("fastify")();

fastify.register(require("fastify-swagger"), {
  openapi: true,
});

fastify.get(
  "/",
  {
    schema: {
      response: {
        200: {
          type: "object",
          description: "Successful Operation",
          $ref: "#/components/schemas/User",
        },
      },
    },
  },
  () => {}
);

fastify.ready(async function () {
  const openapi = await fastify.swagger();
  console.log(JSON.stringify(openapi, null, 2));
});
```
