### ISSUE TITLE
fastify.addSchema defines model key with anonymous name instead of model $id

### ISSUE THREAD

**Issue by roboncode** [fastify/fastify-swagger#575]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.4

### Node.js version

14.17.6

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.2.1

### Description

I am using `openapi-typescript-codegen` to generate a client from `swagger.json` generated by `fastify-swagger`. I have tried this with a few TypeScript generators thinking it may be a bug with this one but they all have the same issue. 

In `swagger.json` the output is as follows:

```json
{
  "def-0":{
     "type":"object",
     "properties":{
        "id":{
           "type":"string"
        }
     },
     "title":"User"
  }
}
```

These generators are expecting the the model to be:

```json
{
  "User":{
     "type":"object",
     "properties":{
        "id":{
           "type":"string"
        }
     },
    "title":"User"
  }
}
```

They generate the models based on the key and not the `title`. Without this the models are defined as `def-0` and referenced as such in the return usages instead of `User`

### Steps to Reproduce

```
const fastify = require("fastify")();

fastify.register(require("fastify-swagger"), {
  openapi: true,
});

fastify.register(async function() {
  fastify.addSchema({
    $id: "User",
    type: "object",
    properties: {
      id: {
        type: "string",
      },
    },
  });

fastify.ready(async function () {
  const openapi = await fastify.swagger();
  console.log(JSON.stringify(openapi, null, 2));
});
```

With a generator installed, such as the aforementioned generator:

```
npm i -g openapi-typescript-codegen
openapi --input http://path-to/swagger-ui/json --output ./generated
```

Or the one from https://openapi-generator.tech/docs/installation

```
npx @openapitools/openapi-generator-cli generate --skip-validate-spec -i http://path-to/swagger-ui/json -g typescript-fetch -o ./generated
```

### Expected Behavior

Models are defined with key as in `swagger.json`

```json
{
  "User":{
     "type":"object",
     "properties":{
        "id":{
           "type":"string"
        }
     },
    "title":"User"
  }
}
```

**Comment by climba03003** [comment]
Please read the document carefully for this case.
https://github.com/fastify/fastify-swagger#managing-your-refs

**Comment by roboncode** [comment]
Thank you
