### ISSUE TITLE
Problems with `ignoreTrailingSlash` fastify option

### ISSUE THREAD

**Issue by bojand** [fastify/fastify-swagger#58]
Hello, just taking the dynamic example and changing the fastify construction:

```
const fastify = require('fastify')({
  ignoreTrailingSlash: true
})
```

makes the url sample documentation url http://localhost:3000/documentation redirect to http://localhost:3000/documentation/documentation

Seems related to the [routes redirect](https://github.com/fastify/fastify-swagger/blob/master/routes.js#L31). But I am really not sure where the real cause and true good fix is... in this plugin, fastify or find-my-way... I can't really find where the original redirect happens in fastify or find-my-way that seems to be cause by `ignoreTrailingSlash` option.

I would think ideally if we could know the options of fastify instance we could just ignore the setup of redirect route. But I can't seem to find a nice way of knowing if that option is turned on as it or the original options do not seem to be exposed? I would be willing to do a PR with some guidance on the best approach where the fix is.

I also checked this with code in #56 and it still exhibits this issue.

![image](https://user-images.githubusercontent.com/2081100/39272829-7ff3ee12-48b3-11e8-88c8-03b7b4afc59b.png)

Thanks.

**Comment by doron2402** [comment]
Is that related to the issue when passing `prefix`?

**Comment by bojand** [comment]
Hello, no it's reproducible with just the stock "dynamic" example in master, and passing `ignoreTrailingSlash: true` to the factory function. There is no prefix involved. 

I also tried the PR referenced _just in case_ it fixed the issue; but it doesn't and looking at the code changes quickly I do not think it would.
