### ISSUE TITLE
How do I display the file upload button in a document?

### ISSUE THREAD

**Issue by niumowangorz** [fastify/fastify-swagger#581]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I tried using it this way, but it didn't work?
```
            body: {
                type: 'object',
                properties: {
                    file: { type: 'object', description: 'file' },
                },
                required: ['file'],
            },
```

**Comment by riquenunes** [comment]
OpenAPI specifies that you must declare it as such:
`file: { type: 'string', format: 'binary' },`

How it looks on swagger-ui:
![image](https://user-images.githubusercontent.com/3210804/164104891-6e64d9b5-3114-4d79-bd96-94ef1c170395.png)

reference: https://swagger.io/docs/specification/describing-request-body/file-upload/
