### ISSUE TITLE
Package name in readme still fastify-swagger

### ISSUE THREAD

**Issue by AWare** [fastify/fastify-swagger#588]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The README still uses the old package name.

**Comment by Fdawgs** [comment]
See the Work To Be Done section in https://github.com/fastify/fastify/issues/3733#issuecomment-1111188683

**Comment by AWare** [comment]
Sorry, but this should have been done before deprecating the original modules.
