### ISSUE TITLE
Not able to use parameters similar to petstore swagger sample.

### ISSUE THREAD

**Issue by varunkamra** [fastify/fastify-swagger#605]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

6.0.1

### Node.js version

14.19.3

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Petstore swagger json: https://petstore.swagger.io/v2/swagger.json

Not able to use "parameters" in request schema. Following request schema is taken from petstore swagger which shows usage of parameters which looks very consistent and not require using querystring, body and params separately.

```
      {
        "tags": [
          "pet"
        ],
        "summary": "uploads an image",
        "description": "",
        "operationId": "uploadFile",
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "ID of pet to update",
            "required": true,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "additionalMetadata",
            "in": "formData",
            "description": "Additional data to pass to server",
            "required": false,
            "type": "string"
          },
          {
            "name": "file",
            "in": "formData",
            "description": "file to upload",
            "required": false,
            "type": "file"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      }
```

In fastify-swagger it seems we always need to use params or querystring or body for adding parameters. Could you give me an example where we can use a request schema like above?

### Steps to Reproduce

Add a new endpoint with given schema in above request, once you load the swagger it will show no parameters.

### Expected Behavior

User should be able to use parameters array just like shown on petstore swagger.

**Comment by climba03003** [comment]
This plugin (dynamic mode) is using `fastify` option to generate the `swagger / openapi` json. Not the reverse way.

`param` is `path` in `parameter`.
`body` is `formData` in `parameter`.
