### ISSUE TITLE
Bring back the support for default

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-swagger#611]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

latest

### Stopped working in version

v7

### Node.js version

all

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

all

### 💥 Regression Report

After https://github.com/fastify/fastify/pull/3935, we cannot support a `default` response schema anymore. In https://github.com/fastify/fastify-swagger/pull/610 I disabled the tests here so we can ship an update module, but we'll probably need to do something to restore the default response here or in Fastify.

### Steps to Reproduce

use `default` response schema

**Comment by mcollina** [comment]
@climba03003 @Eomm how would you like to handle this?

**Comment by climba03003** [comment]
I think it need to be fixed in `fastify`.
