### ISSUE TITLE
Example dynamic-swagger.js doesn't work

### ISSUE THREAD

**Issue by zdila** [fastify/fastify-swagger#620]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.2

### Plugin version

7.3.0

### Node.js version

14.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Debian testing

### Description

`fastify.register` is not awaited at https://github.com/fastify/fastify-swagger/blob/4d69fe1d3f3c3433b99289611636d10151b710ff/examples/dynamic-openapi.js#L5

more examples may be affected

### Steps to Reproduce

run `node dynamic-openapi.js` and visit http://localhost:3000/documentation/static/index.html

### Expected Behavior

route docs should be there

**Comment by mcollina** [comment]
Take a look at https://github.com/fastify/fastify-swagger/pull/621
