### ISSUE TITLE
Fails to load index.css

### ISSUE THREAD

**Issue by alexcroox** [fastify/fastify-swagger#623]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.1.0

### Plugin version

7.4.0

### Node.js version

16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

index.css returns 404

![image](https://user-images.githubusercontent.com/1065835/175160885-9f4afd46-ee49-45da-9bb5-1969b163b68b.png)

### Steps to Reproduce

```
import swagger from '@fastify/swagger'
import fp from 'fastify-plugin'

export default fp(async fastify => {
  fastify.register(swagger, {
    openapi: {
      info: {
        title: 'Exchange REST API Documentation',
        description: 'Description here',
        version: '0.1.0'
      }
    },
    hideUntagged: false,
    exposeRoute: true
  })
})
```

Visit http://127.0.0.1:3000/documentation

**Comment by mcollina** [comment]
Just to clarify: we should not be loading that, right?

**Comment by Perfumere** [comment]
I met the same matter

**Comment by Perfumere** [comment]
I have the same matter

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Perfumere** [comment]
I just found the path "./static/index.html", but this dir was added into .gitignore file
please delete this line: `<link rel="stylesheet" type="text/css" href="index.css" />`

**Comment by Perfumere** [comment]
it seems to be the pkg `@fastify/static@6.4.0`'s  fault
