### ISSUE TITLE
Version 7 does not support fastify v3, but the docs said it does

### ISSUE THREAD

**Issue by AnthonyLzq** [fastify/fastify-swagger#624]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

7.4.0

### Node.js version

16.15.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

5.17.9-1-MANJARO

### Description

When I try to use the last version of `@fastify/swagger` with fastify v3, I got the following error:

```
FastifyError [Error]: fastify-plugin: @fastify/swagger - expected '4.x' fastify version, '3.29.0' is installed
```

The readme says:
> Supports Fastify versions >=3.0.0. For fastify@2, please refer to [branch@2.x](https://github.com/fastify/fastify-swagger/tree/2.x) and for fastify@1.9, please refer to [branch@1.x](https://github.com/fastify/fastify-swagger/tree/1.x).

### Steps to Reproduce

Install fastify v3 with the last version of `@fastify/swagger`.

### Expected Behavior

Just to work, or in other case the readme should be updated to specify which version of `@fastify/swagger` supports fastify v3.

**Comment by climba03003** [comment]
Would you like to send a PR to update the document?

**Comment by AnthonyLzq** [comment]
> Would you like to send a PR to update the document?

Sure, is there a guide for that? 👀

**Comment by climba03003** [comment]
> 
> Sure, is there a guide for that? 👀

1. Fork the repo
2. Clone it
3. Create a new branch
4. Update code and test it
5. Publish the branch
6. Open Pull Request
