### ISSUE TITLE
OAS 3.1: Examples in the open api spec schema property should be an array

### ISSUE THREAD

**Issue by avin-kavish** [fastify/fastify-swagger#625]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4

### Plugin version

7.3

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20

### Description

`schema` object in Open API spec follows the JSON Schema standard as mentioned [here](https://spec.openapis.org/oas/v3.1.0#schema-object).

`example` field is deprecated as mentioned [here](https://spec.openapis.org/oas/v3.1.0#fixed-fields-19).

`examples` field is an array as mentioned [here](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-examples) in the JSON schema spec. 

But, fastify-swagger generates the examples field as an object using this method `convertExamplesArrayToObject`, which breaks some implementations of Open API spec viewers.

Also, note, not every examples field is supposed to be an array, only when JSON schema is expected. For example, the examples of the response object are indeed an object, as mentioned [here](https://spec.openapis.org/oas/v3.1.0#media-type-object).

### Steps to Reproduce

Generate open api spec when you have validation schema like,

```ts
import { Type as t } from '@sinclair/typebox'

t.String({
  examples: [ 'haha', 'haha2' ]
})
```

generates schema like,

```
schema:
  type: string
  examples:
    haha:
      value: haha
    haha2:
      value: haha2
```

### Expected Behavior

```
schema:
  type: string
  examples:
      - haha
      - haha2
```
I think the solution would need to conditionally generate an example array in JSON Schema and an example object in other places.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by avin-kavish** [comment]
Looks like there were some changes in #616 related to this.

**Comment by mcollina** [comment]
cc @mxck

**Comment by mcollina** [comment]
All of you are significantly more expert than me on the OpenAPI spec. I defer to contributors on these OAS features

**Comment by mxck** [comment]
@avin-kavish doesn't swagger already support 3.1? 
I redesigned the examples field in the past PR for version 3.0

**Comment by avin-kavish** [comment]
> doesn't swagger already support 3.1?

I'm not sure what you mean. Do you mean this spec? https://swagger.io/specification/

**Comment by mxck** [comment]
Yes. Check this issue https://github.com/swagger-api/swagger-ui/issues/5891
I don't think there's any point in making 3.1 support if it won't work in current version of swagger?

**Comment by avin-kavish** [comment]
I see. I'm not using swagger ui. I'm using @stoplightio/elements, which only works with the 3.1 standard.

**Comment by mcollina** [comment]
To clarify: OpenAPI v3.1 has some breaking changes compared to v3.0 on the examples property?

**Comment by mxck** [comment]
Yes. In the body of the issue, there are links to the deprecation of the "example" field.
In version 3.1 they tried to be compatible with JSON schema. There the examples field is an array, was object.

**Comment by mcollina** [comment]
What other differences are there between OAS 3.0 and 3.1? We should add support to OAS v3.1 too but keep the v3.0 line as-is. Would you like to give it a go?

**Comment by trim21** [comment]
`example` it not deprecated anymore? anchor `#fixed-fields-19` is missing and I find `example` field on media object
