### ISSUE TITLE
reply.send returns `{}` when schema is provided

### ISSUE THREAD

**Issue by JosephMarotte** [fastify/fastify-swagger#640]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Plugin version

7.4.1

### Node.js version

16.10

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

Hello,

When adding schema to an endpoint, the API call return an empty object `{}` as response

### Steps to Reproduce

Repository link : https://github.com/JosephMarotte/bug-fastify-swagger (code comes from https://github.com/fastify/fastify-swagger/blob/master/examples/dynamic-swagger.js)

Step to reproduce :

```
git clone https://github.com/JosephMarotte/bug-fastify-swagger

cd bug-fastify-swagger

yarn

node server.js

curl --location --request PUT 'localhost:3000/some-route/5' --header 'Content-Type: application/json' --data-raw '{
    "hello": "world"
}'

// {}
```

### Expected Behavior

```
curl --location --request PUT 'localhost:3000/some-route/5' --header 'Content-Type: application/json' --data-raw '{
    "hello": "world"
}'

// {"hello":"Hello world"}
```

**Comment by Uzlopak** [comment]
And what response code do you expect?

**Comment by JosephMarotte** [comment]
Hello,

Thanks for your answer.
Got it I should add `reply.code(201).send(...)`

Thanks for your help and sorry for the bother.

**Comment by livthomas** [comment]
I had a similar issue with `{}` being returned. But it was caused by returned object not matching the schema.
