### ISSUE TITLE
Allow generate a swagger.json file locally

### ISSUE THREAD

**Issue by Benjamin-Latger** [fastify/fastify-swagger#645]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Hello,

fastify-swagger generate the swagger content on runtime that can be consumed on a specific url.

**Maybe I'm wrong** but I could'nt not generate the file locally and that's why I presume that's not possible.

**The proposal is :** add a way to generate a swagger.json locally

### Motivation

In my project, we would like to use an external service to beautify our API documentation based on our swagger.

**The original idea was to generate a swagger.json file with a npm script executed by a CI pipeline (like circleCI) and upload the result file on the external service to beautify and display our documentation to our users.**

The fact is that I couldn't generate this swagger.json locally, so I had to configure it in an other way (based on url).

What do you think ?

**Comment by mcollina** [comment]
This is possible and already supported, use the public API to get the swagger definition and save it to a file, take a look at https://github.com/fastify/fastify-swagger/issues/181#issuecomment-1004865393.
