### ISSUE TITLE
Wrong redirect

### ISSUE THREAD

**Issue by allevo** [fastify/fastify-swagger#65]
The redirection should be made with an absolute url and redirect to `/documentation/index.html`

https://github.com/fastify/fastify-swagger/blob/master/routes.js#L10

**Comment by mcollina** [comment]
+1! PR?

**Comment by sjorsjes** [comment]
This also prevents us from using this in the root of a project. I want mine to be on 
`http://localhost:3000` but the config below creates a redirect to `http://localhost:3000//` which leads to  an error: `Fetch error - Not Found http://localhost:3000//json`.

```js
{
    swagger: {
        info: { title: '' },
    },
    exposeRoute: true,
    routePrefix: '/',
}
```

**Comment by mcollina** [comment]
I'm currently swamped :/. It would be awesome to get a PR.
