### ISSUE TITLE
No operations defined in spec! Dynamic mode

### ISSUE THREAD

**Issue by shakeelosmani** [fastify/fastify-swagger#650]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Plugin version

7.4.1

### Node.js version

16.16.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

My controllers look like below:
```TypeScript

export const GroupController = async (fastify: FastifyInstance) => {
  fastify.get(
    "/",
    {
      schema: {
        description: 'Get all Groups in the database',
        summary: 'Get Groups',
        response: { 200: GroupsSchema },
      },
    },
    async (_req: FastifyRequest, reply: FastifyReply) => {
      const groups = await fastify.orm
        .getRepository(Group)
        .createQueryBuilder("Group")
        .getMany();
      return reply.send(groups);
    }
  );

  fastify.post<{ Body: GroupType }>(
    "/",
    { schema: { body: GroupSchema, response: { 201: GroupSchema } } },
    async (_req, reply) => {
      const group = new Group();
      group.name = _req.body.name;
      const result = await fastify.orm.getRepository(Group).save(group);
      return reply.status(201).send(result);
    }
  );
};
```

And then my schemas are defined using Typebox as such:

```TypeScript
import { Static, Type } from '@sinclair/typebox'

export const GroupSchema = Type.Object({
	id: Type.Optional(Type.Number({description: "The id of the group", examples:[1]})),
  name: Type.String({description: "Name of the group", examples:["Test1"]})
})
```

export const GroupsSchema = Type.Array(GroupSchema);

export type GroupType = Static<typeof GroupSchema>

And then the routes are defined here:

```TypeScript
import { FastifyInstance } from "fastify";
import { HealthStatusController } from '../controller/health-status-controller';
import { GroupController } from '../controller/group/group-controller';

export const Router = async(fastify: FastifyInstance) => {
  fastify.register(HealthStatusController, {prefix: '/api/v1/health-status'});
  fastify.register(GroupController, {prefix: '/api/v1/group'});
} 
```

```TypeScript
Finally swagger is registered like this:
 // swagger registration
server.register(fastifySwagger, {
  routePrefix: '/docs',
  swagger: {
    info: {
      title: 'API documentation for IT core Twitter backend',
      description: 'Swagger docs for the API',
      version: '1.0.0'
    },
    schemes: ['http']
  },
  exposeRoute:true
});
```

But when I open the documentation this is what I see:

No operations defined in spec!

### Steps to Reproduce

Create a latest fastify project with latest plugin version in TypeScript. And the routes do not work.

The structure of the project is below - The router and app is in infrastructure folder. Controllers are in controller and the server is at root. Fastify swagger is registered in app.ts

├───controller
│   └───group
├───entities
├───infrastrcuture
├───migrations
└───schemas

### Expected Behavior

Expect the swagger docs to show up.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by shakeelosmani** [comment]
Sure here is a repo

https://github.com/shakeelosmani/fastify-swagger-issue

**Comment by purbanski-deftcode** [comment]
Same issue for me, just wanted to try this plugin :D

**Comment by shakeelosmani** [comment]
By the way at my job we are fully on fastify and we use fastify swagger and
it works fine. But we have good Typescript experts who have set it up. Not
sure what they might be doing. But making sure here if there is a bug in
the new version.

**Comment by climba03003** [comment]
Please register `@fastify/swagger` before any route.
It is using `onRoute` hooks to get all routes and it means that if the route is added after the registration of this plugin. None of them will be see.

Also, you may need to `await` this plugin if you want to add route in the same level of context.

**Comment by shakeelosmani** [comment]
Thank you! that was it

**Comment by mafischer** [comment]
@climba03003 

would it be possible to add the awaiting of the plugin to the docs. This resolved my issue, but did not see any information about it until this thread.

**Comment by climba03003** [comment]
> would it be possible to add the awaiting of the plugin to the docs. This resolved my issue, but did not see any information about it until this thread.

I am not sure what you means, but the example always show you need to await. I don't knows if an explicit statement would make any difference.

![Image](https://github.com/user-attachments/assets/51bc733c-26fb-4518-8cd1-6b74ba7e79e2)

![Image](https://github.com/user-attachments/assets/e85dfe97-09a2-4907-8682-1e985cef9fd6)
