### ISSUE TITLE
typing issue trying to add x-tokenName prop on securitySchemes

### ISSUE THREAD

**Issue by fernandolguevara** [fastify/fastify-swagger#654]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

latest

### Plugin version

latest

### Node.js version

latest

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

latest

### Description

the swagger ui library, allows to configure the fieldname that will contain the jwt_token value on the auth response, using the prop `x-tokenName` on any of the securitySchemas, but the used typings on the project (`openapi-types`) does not have the definitions, giving us a type error.

```ts
 securitySchemes: {
  myAuth: {
    type: 'oauth2',
    'x-tokenName': 'my_custom_property', // * custom field name
    flows: {
      implicit: {
        authorizationUrl: `http.../login/oauth/authorize`,
        scopes: {},
      },
    },
  },
```  
workaround: cast your security scheme to `<any>`
```ts
 securitySchemes: {
  myAuth: <any>{
    type: 'oauth2',
    'x-tokenName': 'my_custom_property', // * custom field name
    flows: {
      implicit: {
        authorizationUrl: `http.../login/oauth/authorize`,
        scopes: {},
      },
    },
  },
```  

### Steps to Reproduce

use `x-tokenName` on a securityScheme definition

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.
