### ISSUE TITLE
Incompatible with TypeScript 4.8

### ISSUE THREAD

**Issue by kibertoad** [fastify/fastify-swagger#656]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x

### Plugin version

7.4.1

### Node.js version

18

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

TypeScript fails to build when using fastify-swagger 7.4.1

This is due to an upstream problem: https://github.com/kogosoftwarellc/open-api/issues/829

### Steps to Reproduce

Add and use fastify-swagger 7.4.1 in the project, try running tsc

### Expected Behavior

TypeScript 4.8 is supported

**Comment by mcollina** [comment]
I think we are in a bit of a hurry to fix this. Maybe we should consider forking the original package or vendor the openapi types?

**Comment by Uzlopak** [comment]
Well, the rules regarding to provide a PR are just ridiculous. 

https://github.com/kogosoftwarellc/open-api/pull/830

I would recoimmend to fork. Maybe call it swagger-ui-openapi-types and we can move the stuff from #655 into that project.

**Comment by mcollina** [comment]
let's wait a couple of days and then fork.

**Comment by Uzlopak** [comment]
My PR got merged. Lets see when it gets published.

We can continue if this shows a version not being 12.0.0

[![NPM version](https://img.shields.io/npm/v/openapi-types.svg?style=flat)](https://www.npmjs.com/package/openapi-types)

**Comment by Uzlopak** [comment]
The package got released. 
@kibertoad can you test again?

I assume we dont need to release a new Version, because npm should install the latest of the dev dependency.

**Comment by kibertoad** [comment]
I'll test, thank you

**Comment by corevo** [comment]
The latest published version in npm has the constraint `"openapi-types": "^11.0.0"` which would not satisfy 12.0.2.

I've added an override and that fixed it, but since dependabot already updated it in tot, then I assume you can just publish again.

**Comment by mcollina** [comment]
released
