### ISSUE TITLE
Make it possible to disable external validator

### ISSUE THREAD

**Issue by firecow** [fastify/fastify-swagger#661]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

```
await fastify.register(swaggerPlugin, {
  routePrefix: "/",
  exposeRoute: true,
  swagger: {
    validatorEnabled: false
  }
});
```

### Motivation

Validator cannot reach our swagger docs, since its behind a single sign on solution.

### Example

![image](https://user-images.githubusercontent.com/973602/188103543-6a8f4ab6-6496-4fa6-b325-df8f4b55037f.png)

**Comment by firecow** [comment]
```
    await fastify.register(swaggerPlugin, {
        routePrefix: "/",
        exposeRoute: true,
        uiConfig: {
            validatorUrl: "",
        }
    });
```

I'm an idiot sorry :smile:

**Comment by mcollina** [comment]
Can this be closed?

**Comment by firecow** [comment]
Yes, sorry :smile:
