### ISSUE TITLE
Tags property doesn't exist in FastifySchema in TypeScript

### ISSUE THREAD

**Issue by marko1010** [fastify/fastify-swagger#664]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.5.3

### Plugin version

7.5.1

### Node.js version

14.7.3

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

When trying to add 'tags' property to Fastify schema, TypeScript complains with the following error:

```
Type '{ tags: string[]; body: TObject<{ firstName: TOptional<TString>; lastName: TOptional<TString>; email: TString; password: TString; }>; }' is not assignable to type 'FastifySchema'.
  Object literal may only specify known properties, and 'tags' does not exist in type 'FastifySchema'.ts(2322)
```

### Steps to Reproduce

```
 fastify.post<{ Body: newUserType }>('/register', { schema: { tags: ['user'], body: newUserSchema } }, async (req, rep) => {
  });
```

**Comment by mcollina** [comment]
cc @fastify/typescript

**Comment by oitozero** [comment]
@marko1010 I'm having the same problem. Have you been able to solve it? cc/ @mcollina

**Comment by CNLHC** [comment]
> @marko1010 I'm having the same problem. Have you been able to solve it? cc/ @mcollina

@oitozero A quick fix: creating a global `index.d.ts` and using type augmentation

```
declare module 'fastify' {
    interface FastifySchema {
        body?: unknown;
        querystring?: unknown;
        params?: unknown;
        headers?: unknown;
        response?: unknown;
        tags?: string[]
    }
}
```

This can fix the problem but is not a good solution. 

I think we need to wait for the developer to add the missing type to the type definition.

**Comment by climba03003** [comment]
> I think we need to wait for the developer to add the missing type to the type definition.

The types exist, most of the issue related to project setup. 
And I didn't see a repro for us to debug.

**Comment by CNLHC** [comment]
> > I think we need to wait for the developer to add the missing type to the type definition.
> 
> The types exist, and most of the issues are related to project setup. And I didn't see a repro for us to debug.

oh you are right, the type can be found at https://github.com/fastify/fastify-swagger/blob/c8d675d819f7fd274f00a20144a4efdca0c55778/index.d.ts#L34

So the cause of this PR is the extra type shipped with this package is not recognized by the typescript. It does sound like a  project setup problem.

**Comment by Kislax** [comment]
Hello, I spent about 5 hours to find what the problem was, it turned out that I did not import the plugins correctly
As you wrote, it depends on the configuration of ts, namely the selected type of module/moduleResolution

Hope it helps someone

Source link 
https://github.com/fastify/fastify/issues/4122


not working 
![image](https://github.com/fastify/fastify-swagger/assets/50524488/06864455-cf80-48e2-b792-51e6ccac95ba)

worked.
![image](https://github.com/fastify/fastify-swagger/assets/50524488/84eca2a1-20d5-43dd-9457-649bdcca49ff)

need import library to file
