### ISSUE TITLE
Set params bsonType cause loading forever when call API

### ISSUE THREAD

**Issue by conduongtong** [fastify/fastify-swagger#680]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.3.0

### Plugin version

7.4.1

### Node.js version

18.5.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

![image](https://user-images.githubusercontent.com/43648013/195575476-b29303d2-3736-4d81-a17e-a8572937bfd8.png)
I required _id on params which type bson (ObjectID in mongo).

When I call API, it's not validate and keep loading forever.
![image](https://user-images.githubusercontent.com/43648013/195575850-bd3ce656-5798-4516-8a2f-f796945feec0.png)

If I change to type: string, it's work normal.

Sorry for my bad english.

### Steps to Reproduce

Change params to bsonType: 'string'.

**Comment by mcollina** [comment]
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by conduongtong** [comment]
> Thanks for reporting!
> 
> Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

1. set schema in route.
![image](https://user-images.githubusercontent.com/43648013/195636261-e751d4f9-02ba-4878-a26b-8e89385caf99.png)
2. options have params with _id: { bsonType: 'string' }
![image](https://user-images.githubusercontent.com/43648013/195636428-a623ae1d-1497-4efb-b216-94693834a1a9.png)
3. Go to swagger and try out, it's loading forever with that API.
![image](https://user-images.githubusercontent.com/43648013/195636707-aaf53ff2-ee33-48f4-95d3-6a5fe4ee90cd.png)

**Comment by Uzlopak** [comment]
A screenshot is not an appropriate reproducible example. Provide a repository which we can clone and test.

**Comment by climba03003** [comment]
`bsonType` is not a valid keyword for `swagger` and `openapi`.
I would say that it is expected behavior.

In order to get it works, you probably need to pass `transform` function to change all those unsupported `keyword` to a valid `keyword`.
