### ISSUE TITLE
Documentation route returns 404 in 8.0.0

### ISSUE THREAD

**Issue by QEDK** [fastify/fastify-swagger#685]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.9.2

### Plugin version

8.0.0

### Node.js version

18.11.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

I am getting a 404 on the documentation route when using `8.0.0`.
```json
{"message":"Route GET:/documentation not found","error":"Not Found","statusCode":404}
```
Here is my configuration:
```js
  await server.register(import('@fastify/swagger'), {
    routePrefix: '/documentation',
    openapi: {
      info: {
        title: 'API',
        description: 'This API serves the frontend',
        version: '0.0.1'
      }
    },
    uiConfig: {
      docExpansion: 'list',
      deepLinking: false
    },
    staticCSP: true,
    exposeRoute: true
  })
```
Works as expected on `7.6.1`

### Steps to Reproduce

* Upgrade to 8.0.0
* Try to open Swagger UI from the route

### Expected Behavior

It should open the Swagger UI

**Comment by kibertoad** [comment]
https://github.com/fastify/fastify-swagger/blob/master/MIGRATION.md

**Comment by QEDK** [comment]
> https://github.com/fastify/fastify-swagger/blob/master/MIGRATION.md

Thanks @kibertoad! Works as expected with the migration guide. 🥳
