### ISSUE TITLE
swagger page blank because all assets request load from HTTPS instead  of HTTP  

### ISSUE THREAD

**Issue by roninaruka** [fastify/fastify-swagger#690]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

7.4.1

### Node.js version

16.18.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

running on system ip 

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/29303378/201094311-91d6a2dd-9aad-41dc-bc22-7acd1079607d.png)
![image](https://user-images.githubusercontent.com/29303378/201098145-91ab27b0-158f-4afe-892e-15d0f739a323.png)

**Comment by climba03003** [comment]
It in intended browser behavior. We provide `upgrade-insecure-requests` in `CSP` which will automatically upgrade the `http` to `https` when the host is not `localhost`.
I don't see the need of remove it as it is a good behavior for having it.

**Comment by climba03003** [comment]
You can always use `transformStaticCSP` option to remove the unwanted part of `CSP`
