### ISSUE TITLE
Please update documentation: is necessary to install @fastify/swagger-ui plugin to add routePrefix and be able open Swagger UI

### ISSUE THREAD

**Issue by gusparr28** [fastify/fastify-swagger#695]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

**Comment by Uzlopak** [comment]
We have the migration.md

**Comment by climba03003** [comment]
The guide is exist on `@fastify/swagger-ui` and the package already mention on the top of readme.
I don't think we should do anything here as it is a repeated workload.
