### ISSUE TITLE
how to add headers in response body?

### ISSUE THREAD

**Issue by gusparr28** [fastify/fastify-swagger#697]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

**Comment by gusparr28** [comment]
I have an endpoint that doesn't response with JSON, instead it responses with some headers and with file bytes in response body. I would like to add that spec to my Swagger docs, but haven't found a clear solution

**Comment by climba03003** [comment]
I don't know how you check the document, but it do have a section on `response headers`.
https://github.com/fastify/fastify-swagger#response-headers

Please provide a minimal reproducible code if that doesn't work.
