### ISSUE TITLE
Type error on passing JSON schema to openapi.components.schema

### ISSUE THREAD

**Issue by benevbright** [fastify/fastify-swagger#705]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

-

### Node.js version

18.12.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

13.0

### Description

I get type error when passing a JSON schema to register option `openapi.components.schema`. (I create the json schema using Typebox)

fastify-swagger is using openapi-types for TS type. But we(fastify-swagger) don't have their change that they've made for OpenApi 3.1 https://github.com/kogosoftwarellc/open-api/pull/757 and now they have `OpenAPIV3_1.Document`. 

So we would need to apply this to here https://github.com/fastify/fastify-swagger/blob/49f16423a5d7b0b315d8c145d8fbda9ef11f6b37/index.d.ts#L116 somehow, using OR or something. 

### Steps to Reproduce

Try this on [TS playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeTAUwHYEEAKBJANQGYAaFdbfYgfQEY4BfOAMyghDgCIIKBDMYAFoYAT3QBnTgCgpAellw0UNlABccACpi0cAOScMAVwA2xzrrjBxcDBHi9x44AHMMvAEbGdMCHFHo9ADkIbGVeEQBlAGMACzQQXmR3ACs0KJgtAIAfOEMMABM0ZmAMNHzdADoACgAmIhqagEopKJDxeABVcSVadVRMXEIiCui4hKTU9LgAXkQpOD9tdW4UtJhOEnm4MDZ0WGA0cXUELYW3EDRjxfRl9qgS505GTYWFqOBRY9PX3gwRZGY6gA2kh-JcuEZTE8GGRQUsuHcHtCALovV4wrYYhgAbhk8jgEAA1i02p1ulAan0KIMaLQRrF4olVlNZicFmDlhBmes0TseEoYAcjnNXjZeBcrhyETB7hhHs9vu9PiLRXBfv9AXAQddwQYTGZnogdbcZUjGKjvhiFla4FA0ABHQzAO35YF6c5oCzIqQ4oA)
```
import { OpenAPIV3, OpenAPIV3_1 } from "openapi-types"

// error: Type '"null"' is not assignable to type 'NonArraySchemaObjectType | undefined'.(2322)
const User1: OpenAPIV3.SchemaObject = {
  type: "object",
  properties: {
    name: { type: "string" },
    city: {
      anyOf: [{ type: "null" }, { type: "string" }],
    },
  },
};

// ok
const User2: OpenAPIV3_1.SchemaObject = {
  type: "object",
  properties: {
    name: { type: "string" },
    city: {
      anyOf: [{ type: "null" }, { type: "string" }],
    },
  },
};
```

Also, it's reproducible when passing this object to `openapi.components.schema` option on `fastify.register`.

**Comment by benevbright** [comment]
related to https://github.com/fastify/fastify-swagger/issues/499

**Comment by nidhi-kala** [comment]
If no one has taken this yet, I'm happy to send a pull request for this.
