### ISSUE TITLE
Add Redoc UI plugin 

### ISSUE THREAD

**Issue by MeowningMaster** [fastify/fastify-swagger#710]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Separating the spec generation from the UI was a great idea! Are there plans to add a plugin with [Redoc UI](https://github.com/Redocly/redoc)?

### Motivation

It's open source and has basic support for OpenAPI 3.1 which fits very well in fastify/typebox/Ajv stack.

**Comment by mcollina** [comment]
Why don't you work on one?

**Comment by MeowningMaster** [comment]
It's difficult for me to find free time now. But maybe later I do

**Comment by Fdawgs** [comment]
FYI you don't need a plugin for this.

1. Register the @fastify/swagger plugin
2. Have a route that sends the swagger function; [example](https://github.com/Fdawgs/ydh-community-contacts-api/blob/main/src/routes/docs/openapi/index.js#L41)
3. Point to the route in the Redoc config; [example](https://github.com/Fdawgs/ydh-community-contacts-api/blob/main/src/routes/docs/index.html#L34)
