### ISSUE TITLE
`formatParamUrl` should be exposed

### ISSUE THREAD

**Issue by marcopiraccini** [fastify/fastify-swagger#747]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

The `formatParamUrl` function [HERE](https://github.com/fastify/fastify-swagger/blob/master/lib/util/common.js#L105) translates path in the fastify router format to openapi. 
It would be great to have it exposed as decorator, so it could be used from the same purpose on other projects.

### Motivation

I need to do exactly what this function does, but is not exposed from this module.

**Comment by Uzlopak** [comment]
Should it really be a decorator? And if you how name it?
Cant we just expose it to be requirable?

**Comment by mcollina** [comment]
We can also expose it to be requirable, it would work well for us too.

**Comment by Uzlopak** [comment]
I think exposing would be cleaner.

**Comment by Uzlopak** [comment]
see #748

**Comment by marcopiraccini** [comment]
Yes, requirable is OK.
