### ISSUE TITLE
Automatically generate path params definition

### ISSUE THREAD

**Issue by ivan-tymoshenko** [fastify/fastify-swagger#750]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

It would be nice if @fastify/swagger would generate a default schema for path params.

```js
  fastify.get('/example/*', async (request, reply) => {})
```

Something like this:

```json
"/{param}": {
  "get": {
    "params": {
      "param": {
        "type": "string"
      }
    },
    "responses": {
      "200": {
        "description": "Default Response"
      }
    }
  }
}
```

Instead of this:

```json
"/{param}": {
  "get": {
    "responses": {
      "200": {
        "description": "Default Response"
      }
    }
  }
}
```

**Comment by Uzlopak** [comment]
I am not sure.

If we do this, the swagger could be correct. But on the other hand, path params schema is not effected by this.

**Comment by ivan-tymoshenko** [comment]
Sorry, I don't undersand what do you mean

**Comment by Uzlopak** [comment]
```js
fastify.get('/example/{param}', {schema: { params: {} /* what? */ } }, async (request, reply) => {})
```

**Comment by ivan-tymoshenko** [comment]
Oh, I see. Can we resolve it on a fastify level?

**Comment by Uzlopak** [comment]
idk. I would personally expect that schema gets validated against the path.

**Comment by mcollina** [comment]
@Uzlopak I don't understand

**Comment by ivan-tymoshenko** [comment]
I would say, let's generate default param schema only if user doesn't specify a schema for param at all. If there is something, even with missing params like in your example, we should not modify it.

**Comment by Uzlopak** [comment]
I agree.

**Comment by mcollina** [comment]
This would be amazing to have

**Comment by msebastianb** [comment]
I'd like to pick up this.

**Comment by mcollina** [comment]
go for it!
