### ISSUE TITLE
Generate json without swagger-ui

### ISSUE THREAD

**Issue by dennys** [fastify/fastify-swagger#759]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I can use fastify-swagger with fastify-swagger-ui now, but I want to remove swagger-ui and generate json for RapicDoc.
Based on the [hint](https://github.com/fastify/fastify-swagger/pull/672#issuecomment-1739871089), I can use `fastify.swagger()` to generate a json without swagger-ui.
```
 fastify.get('/doc', opts, async (request, reply) => {
      reply.send(fastify.swagger())
    });
```

Then I can integrate it to [RapiDoc](https://rapidocweb.com/)
```
<!doctype html> <!-- Important: must specify -->
<html>
  <head>
    <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 characters -->
    <script type="module" src="rapidoc-min.js"></script>
  </head>
  <body>
    <rapi-doc spec-url = "http://localhost:3000/doc"> </rapi-doc>
  </body>
</html>
```

Is this a correct/good solution?

**Comment by mcollina** [comment]
Yes
