### ISSUE TITLE
Missing description when using $ref

### ISSUE THREAD

**Issue by melroy89** [fastify/fastify-swagger#795]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

8.14.0

### Node.js version

20.11.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux Mint 23.1

### Description

When adding shared schemas via `fastify.addSchema()` for response objects and using the id to access the schema like so: `422: { $ref: 'internalServerErrorResponse#' }`, result in a missing description.

Instead of the description displayed from the added schema, you will keep seeing "Default Response". When not using shared ref schemas, but adding the schema to the route schema, the description is taking into account. So it only doesn't work when using ref.

### Steps to Reproduce

1. Add shared schema for a response including a description, like this:

```js
import fastify from 'fastify'
import fastifySwagger from '@fastify/swagger'
import fastifySwaggerUi from '@fastify/swagger-ui'

const fastify = fastify()

fastify.addSchema({
  $id: 'validationError',
  description: 'Validation Error',
  type: 'object',
  properties: {
    statusCode: { type: 'number' },
    code: { type: 'string' },
    error: { type: 'string' },
    message: { type: 'string' }
  }
})

// Use OpenAPI v3 spec
await fastify.register(fastifySwagger, {
      mode: 'dynamic',
      openapi: { }
})
// Also add Swagger-UI plugin
await fastify.register(fastifySwaggerUi, {
  routePrefix: '/docs',
})
```

Using this schema by ID:

```js
fastify.delete('/:id', { schema: {
  description: 'Delete an object (example)',
  response: {
    422: {
      $ref: 'validationError#'
    },
}, async (req, reply) => {
  // ...
})
```

Going to the `/docs` for swagger, you will see:

![image](https://github.com/fastify/fastify-swagger/assets/628926/8c9d08f9-0455-43a1-8a5e-4e7500b44db7)

### Expected Behavior

The description of the schema should be put in the response description as well, instead of showing "Default Response" (which is the fallback description text).

### Code

I don't know the codebase, and `utils.js` is quite complex code. But I suspect to look around there: https://github.com/fastify/fastify-swagger/blob/fedf75c4f314fe9b37c81c88525f1ee1874335fa/lib/spec/openapi/utils.js#L342

**Comment by melroy89** [comment]
I also tried Scalar, I see the same "Default response" message (instead of using the description) when using Scalar api reference interface with `$ref` responses:

![image](https://github.com/fastify/fastify-swagger/assets/628926/697de475-03bd-4ebc-ac45-74c4baa8f252)

**Comment by melroy89** [comment]
@jean-michelet Would you be willing to help me with this issue? To briefly explain the issue. You can use Fastify with swagger as you know, using schemas. 

So I'm using `fastify.addSchema()` to add multiple shared schemas, right? Nothing wrong there. Then you can access those shared schemas using this $ref notation like so:

```
    422: {
      $ref: 'validationError#'
    },
```

However, for some reason when going to the Fastify Swagger docs, the response description is not copied correctly and all the shared schemas will just show "Default Response" no matter what.. The reason you didn't saw this problem in your demo repo is because you aren't using `addSchema` feature: https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/#adding-a-shared-schema

**Comment by jean-michelet** [comment]
Should we use `addSchema` in the demo?

**Comment by jean-michelet** [comment]
If not, I don't know if I have time to fix this. Fastify mainteners usually don't fix bugs that don't affect them directly, expect security issues I guess. Can you push a PR with unit tests?

**Comment by melroy89** [comment]
> Should we use `addSchema` in the demo?

Maybe not a bad idea.. It's a good example how you could re-use schemas in Fastify.

**Comment by Nelspike** [comment]
I just went ahead and opened a PR to solve this - Hopefully it helps! 🎉 https://github.com/fastify/fastify-swagger/pull/826

**Comment by jean-michelet** [comment]
Thanks @Nelspike!
