### ISSUE TITLE
fastify.ready() with fastify-cli

### ISSUE THREAD

**Issue by lgertel** [fastify/fastify-swagger#80]
Hello everyone.
I'm using fastify-cli to run my project, and don't know where to add the configuration: 

```
fastify.ready(err => {
  if (err) throw err
  fastify.swagger()
})
```
Thanks!

**Comment by mcollina** [comment]
I'm a bit lost. What do you mean? Can you make a full example?

**Comment by lgertel** [comment]
I'm trying to add fastify-swagger on my project. The project was created with fastify-cli!
This is my app.js:
```
module.exports = function (fastify, opts, next) {

  fastify.register(require('@now-ims/fastify-firestore'), {
    projectId: 'nomikos-544df',
    keyFilename: './nomikos-78ff516da5d8.json'
  })

  fastify.register(require('fastify-swagger'), {
    swagger: {
      info: {
        title: 'Test swagger',
        description: 'testing the fastify swagger api',
        version: '0.1.0'
      },
      routePrefix: '/documentation',
      host: 'localhost',
      schemes: ['http'],
      consumes: ['application/json'],
      produces: ['application/json'],
      securityDefinitions: {
        apiKey: {
          type: 'apiKey',
          name: 'apiKey',
          in: 'header'
        }
      }
    }
  })

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'plugins')
  })

  // This loads all plugins defined in services
  // define your routes in one of these
  fastify.register(AutoLoad, {
    dir: path.join(__dirname, 'services')
  })

  // Make sure to call next when done
  next()
}

**Comment by mcollina** [comment]
`fastify.swagger()` will just return the swagger definition. You do not have to do much, just navigate to `/documentation` and your swagger-ui should appear.

Is it working?

**Comment by lgertel** [comment]
But where to add the ```fastify.swagger()``` ? On the route?
```
// 20180611161700
// http://localhost:3000/documentation

{
  "statusCode": 404,
  "error": "Not Found",
  "message": "Not Found"
}
```

**Comment by mcollina** [comment]
Oh, you'll need the `  exposeRoute: true` option.

**Comment by lgertel** [comment]
Great, working now!
One little thing: On the Usage section on README.md - there is a extra {}

```
fastify.register(require('fastify-swagger'), {
  swagger: {
    info: {
      title: 'Test swagger',
      description: 'testing the fastify swagger api',
      version: '0.1.0'
    },
    routePrefix: '/documentation',
    host: 'localhost',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    securityDefinitions: {
      apiKey: {
        type: 'apiKey',
        name: 'apiKey',
        in: 'header'
      }
    }
  }
})
```
This doesn't work!

Here is my version:
```
fastify.register(require('fastify-swagger'), {
    swagger: {
      info: {
        title: 'EDS Cognitive',
        description: 'Testing the fastify swagger api',
        version: '0.1.0'
      },
    },
    exposeRoute: true,
    routePrefix: '/documentation'
  })
```

Not sure why but....
Thanks a lot.
 We will start to use fastify on a big enterprise project, you'll see me a lot here...lol

cya

**Comment by mcollina** [comment]
@lgertel would you like to send a PR to update the README?

I'm glad you picked fastify!

**Comment by lgertel** [comment]
@mcollina yeah! sure!
I'll work on this and send news asap.

Who knows, maybe sometime I'll be able to work on the core too :)

**Comment by radvansky-tomas** [comment]
![screen shot 2019-01-22 at 11 30 32 am](https://user-images.githubusercontent.com/12473664/51502064-3274df00-1e39-11e9-94ef-f539eea0ea37.png)

**Comment by radvansky-tomas** [comment]
If I add any schema definition to services/auth/index,js there are not part of swagger generated docs

**Comment by mcollina** [comment]
that needs to be loaded before the autoload calls. There is a comment at the top where to add your plugins.

**Comment by radvansky-tomas** [comment]
Thank you, works. Please try to add this to main example, as this is what you will get if you follow guides :D

**Comment by Armania** [comment]
This also worked for me,

I was trying to install @fastify/swagger-ui but was getting an error.
-> AssertionError [ERR_ASSERTION]: The dependency '@fastify/swagger' of plugin '@fastify/swagger-ui' is not registered

I tried just registering fastify-swagger, via "autoload" but adding a file for swagger. but that did not work. But i did not have the   exposeRoute: true option. 

/app.js
`
// ...
fastify.register(require("@fastify/swagger"), {
    swagger: {
      info: {
        title: "Armani Machines",
        description: "Api documentation test using Swagger/Swaggerui",
        version: "0.1.0",
      },
   },
    exposeRoute: true,
    routePrefix: "/documentation",
    uiConfig: {
      docExpansion: "full",
      deepLinking: false,
    },
  });
// ...
`

This code worked for me

**Comment by ChristoPy** [comment]
Hi, been facing the same challenge to use `@fastify/swagger` plugin while in a project generated via the CLI.

Here is my `app.ts`code:
```ts
import { join } from 'path';
import AutoLoad, {AutoloadPluginOptions} from '@fastify/autoload';
import { FastifyPluginAsync, FastifyServerOptions } from 'fastify';

export interface AppOptions extends FastifyServerOptions, Partial<AutoloadPluginOptions> {

}
// Pass --options via CLI arguments in command to enable these options.
const options: AppOptions = {
}

const app: FastifyPluginAsync<AppOptions> = async (
    fastify,
    opts
): Promise<void> => {
  // Place here your custom code!
  fastify.register(require('@fastify/swagger'), {
    swagger: {
      info: {
        title: 'My API',
        description: 'Testing the fastify swagger api',
        version: '0.0.1'
      },
    },
    exposeRoute: true,
    routePrefix: '/documentation'
  })

  // Do not touch the following lines

  // This loads all plugins defined in plugins
  // those should be support plugins that are reused
  // through your application
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'plugins'),
    options: opts
  })
  void fastify.register(AutoLoad, {
    dir: join(__dirname, 'modules'),
    maxDepth: 1
  })

  // fastify.ready(err => {
  //   if (err) throw err
  //   fastify.swagger()
  // })
};

export default app;
export { app, options }
```

I need to call `fastify.swagger()` after defining the routes and when fastify is ready as stated in the README.
But if I do it (by uncommenting the code), this error gets logged into the console:
```
[App] Error: .swagger() must be called after .ready()
[App] [fastify-cli] app crashed - waiting for file changes before starting...
```

What is the proper way to use the plugin in this scenario?
I tried using `exposeRoute` and `routePrefix` options like in the previous answers but with no luck.
