### ISSUE TITLE
Customize HTML and CSS

### ISSUE THREAD

**Issue by KonstantinVlasov** [fastify/fastify-swagger#82]
Hi! Is it possible to customize generated documentation?

**Comment by delvedor** [comment]
Hi! We are using [swagger-ui](https://swagger.io/tools/swagger-ui/), I'm not sure if you can customize it.
Probably you should look into their docs, and if it is possible, pr are welcome! :)

**Comment by KonstantinVlasov** [comment]
Thanks! Will dig into it

**Comment by cemremengu** [comment]
Closing as resolved. Feel free to reopen if there are any updates

**Comment by marcelo-agil** [comment]
> Thanks! Will dig into it

Have you done it?
