### ISSUE TITLE
Support `tags` and `externalDocs` in dynamic mode

### ISSUE THREAD

**Issue by ofavre** [fastify/fastify-swagger#85]
As per OpenAPI 2.0 specification, you are missing 2 top-level fields described here https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields:
- `tags`
- `externalDocs`

Because you are reconstructing `swaggerObject` from `opts.swagger` in `dynamic.js` even if those fields are given, they are stripped in the output.

I'm filing this issue because I found that `tags` was missing, but there may be more fields that are lacking deeper down, I didn't check.

**Comment by mcollina** [comment]
Thanks for reporting this! Would you like to send a PR?
