### ISSUE TITLE
Support openapi 3.0 for dynamic configuration

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/fastify-swagger#87]
Seems underlying module `swagger-parser` already supports new openapi v3 specifications. So I think it would be good if this module will support it as well. 

The main idea just to make https://github.com/fastify/fastify-swagger/blob/master/dynamic.js#L59 configurable through options.

However it will also require to refactor some things like `securityDefinitions`, because in 3.0 they moved to other sections of config file.

I'm not sure that fastify schemas are compatible with openapi v3 specs.

**Comment by sjorsjes** [comment]
Does this include Bearer auth aswell? https://swagger.io/docs/specification/authentication/bearer-authentication/
