### ISSUE TITLE
Support passing swagger definition in static mode

### ISSUE THREAD

**Issue by kamilmysliwiec** [fastify/fastify-swagger#97]
Currently, in `static` mode, there is no way to pass a *content* of the file directly. You need to pass the path to the file instead.

## Current behavior
```
mode: 'static',
specification: {
    path: './examples/example-static-specification.yaml'
},
```

## New feature request
```
mode: 'static',
specification: {
    doc: {
        ...real swagger document... (content of the specification file)
    }
},
```

## Why?
We use `fastify-swagger` to provide a fastify integration with NestJS (and Swagger module exposed by `@nestjs/swagger`). Unluckily, we cannot fully support this platform since there is no way to pass swagger definition's object directly (you always have to pass a path to the file in static mode). Would it be a big deal to provide such possibility in the future?

**Comment by mcollina** [comment]
Would you like to send a PR for this feature? It seems interesting.
